/**
 * Handlungsschritt 2: IT-Arbeitsplatz nach Kundenwunsch ausstatten.
 * Themen: Hardwarekomponenten, Leistungskennwerte, Speichereinheiten, Peripherie,
 * Drucker, Monitore, Betriebssysteme, Software, Lizenzmodelle, Ergonomie/Arbeitsschutz,
 * Barrierefreiheit, Green IT, Thin/Fat Client, Virtualisierung, Cloud, Kaufmännisches.
 */
import type { Question } from '../../../shared/types.js';

export const questions: Question[] = [
  /* ===================== Multiple Choice (3 Punkte) ===================== */
  {
    id: 'ap-mc-001',
    section: 'arbeitsplatz',
    topic: 'speichereinheiten',
    type: 'multiple_choice',
    title: 'Binär- und Dezimalpräfixe',
    scenario: 'Ein Kunde der Systemhaus Weber GmbH beschwert sich, dass seine neue 2-TB-Festplatte im Betriebssystem nur etwa 1,82 TB anzeigt.',
    text: 'Welche Aussagen zu Speichereinheiten sind korrekt? (Mehrere Antworten möglich)',
    points: 3,
    difficulty: 2,
    options: [
      { id: 'a', text: '1 KiB (Kibibyte) entspricht 1.024 Byte, 1 kB (Kilobyte) entspricht 1.000 Byte.' },
      { id: 'b', text: 'Festplattenhersteller rechnen üblicherweise mit Dezimalpräfixen (1 TB = 10^12 Byte).' },
      { id: 'c', text: 'Die Differenz zwischen 2 TB und 1,82 TiB entsteht durch defekte Sektoren auf der Festplatte.' },
      { id: 'd', text: '1 GiB ist kleiner als 1 GB.' },
      { id: 'e', text: 'Windows zeigt Kapazitäten binär (Basis 1024) an, beschriftet sie aber häufig mit GB/TB.' },
    ],
    correct: ['a', 'b', 'e'],
    multi: true,
    explanation:
      '2 × 10^12 Byte ÷ 1024^4 ≈ 1,82 TiB – das ist reine Umrechnung, keine defekten Sektoren. 1 GiB (1.073.741.824 Byte) ist größer als 1 GB (10^9 Byte).',
  },
  {
    id: 'ap-mc-002',
    section: 'arbeitsplatz',
    topic: 'lizenzmodelle',
    type: 'multiple_choice',
    title: 'Open-Source-Lizenzen',
    scenario: 'Die Softwarefirma CodeCraft GmbH möchte eine Open-Source-Bibliothek in ihr kommerzielles, proprietäres Produkt einbinden und prüft die Lizenzbedingungen.',
    text: 'Welche Aussagen zu Open-Source-Lizenzen sind korrekt? (Mehrere Antworten möglich)',
    points: 3,
    difficulty: 3,
    options: [
      { id: 'a', text: 'Die GPL verlangt bei Weitergabe eines abgeleiteten Werks, dass dieses ebenfalls unter der GPL mit Quellcode veröffentlicht wird (Copyleft).' },
      { id: 'b', text: 'Die MIT-Lizenz erlaubt die Verwendung in proprietärer Software, sofern der Lizenz- und Copyright-Hinweis beibehalten wird.' },
      { id: 'c', text: 'Open-Source-Software darf grundsätzlich nicht kommerziell genutzt werden.' },
      { id: 'd', text: 'Open Source bedeutet, dass die Software keinem Urheberrecht unterliegt.' },
      { id: 'e', text: 'Bei Open-Source-Software ist der Quellcode einsehbar und darf unter den Bedingungen der Lizenz verändert und weitergegeben werden.' },
    ],
    correct: ['a', 'b', 'e'],
    multi: true,
    explanation:
      'Copyleft-Lizenzen (GPL) verpflichten abgeleitete Werke zur gleichen Lizenz; permissive Lizenzen (MIT, BSD, Apache) erlauben die Einbindung in proprietäre Produkte. Open Source ist urheberrechtlich geschützt und darf kommerziell genutzt werden.',
  },
  {
    id: 'ap-mc-003',
    section: 'arbeitsplatz',
    topic: 'thin-client',
    type: 'multiple_choice',
    title: 'Thin Client oder Fat Client',
    scenario: 'Das Callcenter der Versicherung NordSecur AG will 80 Arbeitsplätze neu ausstatten. Diskutiert wird der Einsatz von Thin Clients mit Terminalserver statt klassischer PCs.',
    text: 'Welche Aussagen zu Thin Clients sind korrekt? (Mehrere Antworten möglich)',
    points: 3,
    difficulty: 2,
    options: [
      { id: 'a', text: 'Thin Clients haben in der Regel einen geringeren Energieverbrauch und geringere Anschaffungskosten je Gerät als Fat Clients.' },
      { id: 'b', text: 'Bei Thin Clients laufen die Anwendungen lokal auf dem Gerät; der Server dient nur der Datenspeicherung.' },
      { id: 'c', text: 'Die zentrale Administration (Updates, Softwareverteilung) ist bei Thin Clients einfacher, da die Anwendungen auf dem Terminalserver laufen.' },
      { id: 'd', text: 'Thin Clients sind ohne funktionierende Netzwerkverbindung zum Server praktisch nicht arbeitsfähig.' },
      { id: 'e', text: 'Thin Clients eignen sich besonders für grafikintensive Anwendungen wie CAD und Videoschnitt.' },
    ],
    correct: ['a', 'c', 'd'],
    multi: true,
    explanation:
      'Thin Clients stellen nur Ein-/Ausgabe bereit; Rechenleistung liegt zentral. Vorteile: geringe Kosten, zentrale Wartung, Sicherheit. Nachteile: Abhängigkeit vom Netz und Server, ungeeignet für grafikintensive Anwendungen.',
  },
  {
    id: 'ap-mc-004',
    section: 'arbeitsplatz',
    topic: 'cloud',
    type: 'multiple_choice',
    title: 'Cloud-Servicemodelle',
    scenario: 'Die Werbeagentur PixelPark möchte ihre Buchhaltungssoftware künftig nicht mehr selbst betreiben, sondern über den Browser als fertige Anwendung nutzen; Wartung und Updates soll der Anbieter übernehmen.',
    text: 'Welches Cloud-Servicemodell entspricht diesem Wunsch?',
    points: 3,
    difficulty: 2,
    options: [
      { id: 'a', text: 'IaaS – der Anbieter stellt virtuelle Server, Speicher und Netzwerk bereit; die Agentur installiert Betriebssystem und Anwendung selbst.' },
      { id: 'b', text: 'PaaS – der Anbieter stellt eine Laufzeit- und Entwicklungsumgebung bereit, in der die Agentur eigene Anwendungen betreibt.' },
      { id: 'c', text: 'SaaS – der Anbieter betreibt die vollständige Anwendung inklusive Wartung; die Agentur nutzt sie über den Browser.' },
      { id: 'd', text: 'On-Premises – die Software wird auf eigenen Servern im Rechenzentrum der Agentur betrieben.' },
    ],
    correct: ['c'],
    multi: false,
    explanation:
      'Bei Software as a Service liegt die gesamte Betriebsverantwortung (Infrastruktur, Plattform, Anwendung) beim Anbieter; der Kunde konfiguriert und nutzt nur noch.',
  },
  {
    id: 'ap-mc-005',
    section: 'arbeitsplatz',
    topic: 'ergonomie',
    type: 'multiple_choice',
    title: 'Ergonomie am Bildschirmarbeitsplatz',
    scenario: 'Die Steuerkanzlei Bergmann & Partner richtet vier neue Büroarbeitsplätze ein und bittet Sie um eine Prüfung nach der Arbeitsstättenverordnung (Anhang Bildschirmarbeit).',
    text: 'Welche Aussagen zur ergonomischen Gestaltung eines Bildschirmarbeitsplatzes sind korrekt? (Mehrere Antworten möglich)',
    points: 3,
    difficulty: 2,
    options: [
      { id: 'a', text: 'Der Bildschirm soll so aufgestellt werden, dass die Blickrichtung parallel zur Fensterfront verläuft, um Blendung und Spiegelung zu vermeiden.' },
      { id: 'b', text: 'Die oberste Bildschirmzeile sollte etwa auf Augenhöhe oder leicht darunter liegen.' },
      { id: 'c', text: 'Der Bildschirm soll direkt vor dem Fenster stehen, damit möglichst viel Tageslicht auf die Anzeige fällt.' },
      { id: 'd', text: 'Ober- und Unterarme sowie Ober- und Unterschenkel sollen beim Sitzen jeweils etwa einen rechten Winkel bilden.' },
      { id: 'e', text: 'Die Tastatur muss fest mit dem Bildschirm verbunden sein, um eine einheitliche Ausrichtung zu gewährleisten.' },
    ],
    correct: ['a', 'b', 'd'],
    multi: true,
    explanation:
      'Blickrichtung parallel zum Fenster, Sehabstand ca. 50–70 cm, oberste Zeile auf Augenhöhe, 90°-Regel für Arme und Beine. Die Tastatur muss vom Bildschirm getrennt und neigbar sein.',
  },
  {
    id: 'ap-mc-006',
    section: 'arbeitsplatz',
    topic: 'virtualisierung',
    type: 'multiple_choice',
    title: 'Hypervisor-Typen',
    scenario: 'Die Systemhaus Weber GmbH plant für einen Kunden einen Virtualisierungsserver, auf dem mehrere Server-VMs ohne zusätzliches Host-Betriebssystem laufen sollen.',
    text: 'Welche Aussage zu Hypervisoren ist korrekt?',
    points: 3,
    difficulty: 2,
    options: [
      { id: 'a', text: 'Ein Typ-1-Hypervisor (Bare Metal) läuft direkt auf der Hardware und eignet sich für den Serverbetrieb, z. B. VMware ESXi, Microsoft Hyper-V oder Proxmox VE.' },
      { id: 'b', text: 'Ein Typ-2-Hypervisor läuft direkt auf der Hardware; ein Typ-1-Hypervisor wird als Anwendung in einem Host-Betriebssystem installiert.' },
      { id: 'c', text: 'Container (z. B. Docker) sind Typ-1-Hypervisoren, da sie ein eigenes Betriebssystem je Container virtualisieren.' },
      { id: 'd', text: 'Ein Typ-2-Hypervisor wie VirtualBox bietet stets eine höhere Leistung als ein Typ-1-Hypervisor, da er das Host-Betriebssystem nutzt.' },
    ],
    correct: ['a'],
    multi: false,
    explanation:
      'Typ 1 = Bare Metal (direkt auf der Hardware, effizient, für Server); Typ 2 = Hosted (als Anwendung im Host-OS, z. B. VirtualBox, VMware Workstation). Container teilen sich den Kernel des Hosts und sind keine Hypervisoren.',
  },

  /* ===================== Multiple Choice (2 Punkte) ===================== */
  {
    id: 'ap-mc-007',
    section: 'arbeitsplatz',
    topic: 'gewaehrleistung',
    type: 'multiple_choice',
    title: 'Gewährleistung und Garantie',
    scenario: 'Ein Notebook, das die Gärtnerei Grünwald vor 14 Monaten bei einem Händler gekauft hat, zeigt einen Defekt am Display.',
    text: 'Welche Aussage zu Gewährleistung und Garantie ist korrekt?',
    points: 2,
    difficulty: 2,
    options: [
      { id: 'a', text: 'Die Gewährleistung ist eine freiwillige Leistung des Herstellers; die Garantie ist gesetzlich vorgeschrieben.' },
      { id: 'b', text: 'Die gesetzliche Gewährleistung beträgt beim Kauf zwischen Unternehmen in der Regel zwei Jahre ab Übergabe und richtet sich gegen den Verkäufer.' },
      { id: 'c', text: 'Die Gewährleistung deckt auch Mängel ab, die erst nach dem Kauf durch unsachgemäße Nutzung entstanden sind.' },
      { id: 'd', text: 'Gewährleistungsansprüche bestehen immer gegenüber dem Hersteller, nie gegenüber dem Händler.' },
    ],
    correct: ['b'],
    multi: false,
    explanation:
      'Gewährleistung (Sachmängelhaftung, BGB) ist gesetzlich, gilt gegenüber dem Verkäufer und betrifft Mängel, die bei Übergabe bereits vorlagen. Garantie ist eine freiwillige, zusätzliche Zusage (meist des Herstellers).',
  },
  {
    id: 'ap-mc-008',
    section: 'arbeitsplatz',
    topic: 'massenspeicher',
    type: 'multiple_choice',
    title: 'NVMe-SSD und SATA-SSD',
    scenario: 'Für eine Videoschnitt-Workstation der Filmproduktion Lichtspiel GmbH sollen Sie den Massenspeicher auswählen.',
    text: 'Welche Aussage zum Vergleich von NVMe-SSDs und SATA-SSDs ist korrekt?',
    points: 2,
    difficulty: 2,
    options: [
      { id: 'a', text: 'NVMe-SSDs werden über PCI Express angebunden und erreichen deutlich höhere Übertragungsraten als SATA-SSDs, die auf ca. 600 MB/s begrenzt sind.' },
      { id: 'b', text: 'SATA-SSDs sind grundsätzlich schneller, da SATA speziell für SSDs entwickelt wurde.' },
      { id: 'c', text: 'NVMe-SSDs enthalten rotierende Magnetscheiben und sind deshalb stoßempfindlicher als SATA-SSDs.' },
      { id: 'd', text: 'NVMe und SATA bezeichnen ausschließlich die Bauform (M.2 bzw. 2,5 Zoll), nicht die Schnittstelle.' },
    ],
    correct: ['a'],
    multi: false,
    explanation:
      'NVMe ist ein Protokoll für Flash-Speicher über PCIe (mehrere GB/s), SATA III ist auf 6 Gbit/s (ca. 600 MB/s) begrenzt. M.2 ist nur eine Bauform, die sowohl SATA- als auch NVMe-SSDs aufnehmen kann.',
  },
  {
    id: 'ap-mc-009',
    section: 'arbeitsplatz',
    topic: 'drucker',
    type: 'multiple_choice',
    title: 'Druckerauswahl',
    scenario: 'Die Anwaltskanzlei Roth & Kollegen druckt monatlich rund 8.000 Seiten Schriftsätze in Schwarz-Weiß und sucht einen geeigneten Arbeitsplatzdrucker.',
    text: 'Welcher Druckertyp ist für diesen Einsatz am besten geeignet und warum?',
    points: 2,
    difficulty: 1,
    options: [
      { id: 'a', text: 'Ein Tintenstrahldrucker, weil die Anschaffungskosten am niedrigsten sind und der Seitenpreis bei hohem Volumen sinkt.' },
      { id: 'b', text: 'Ein Laserdrucker, weil er bei hohem Textdruckvolumen einen niedrigen Seitenpreis, hohe Druckgeschwindigkeit und dokumentenechten Ausdruck bietet.' },
      { id: 'c', text: 'Ein Thermodrucker, weil er ohne Toner und Tinte auskommt und deshalb die niedrigsten Betriebskosten hat.' },
      { id: 'd', text: 'Ein Fotodrucker mit sechs Tintentanks, weil er die höchste Auflösung liefert.' },
    ],
    correct: ['b'],
    multi: false,
    explanation:
      'Laserdrucker haben höhere Anschaffungskosten, aber bei großem Volumen deutlich geringere Seitenpreise, hohe Geschwindigkeit und wisch- sowie lichtbeständige Ausdrucke. Tintenstrahl lohnt sich bei geringem Volumen oder Fotodruck.',
  },
  {
    id: 'ap-mc-010',
    section: 'arbeitsplatz',
    topic: 'software',
    type: 'multiple_choice',
    title: 'System- und Anwendungssoftware',
    scenario: 'Sie erstellen für die Bäckereikette Kornblume eine Softwareliste für die neuen Filial-PCs und sollen die Programme nach Softwarearten gruppieren.',
    text: 'Welche der folgenden Programme zählen zur Systemsoftware?',
    points: 2,
    difficulty: 1,
    options: [
      { id: 'a', text: 'Textverarbeitung, Tabellenkalkulation und E-Mail-Programm' },
      { id: 'b', text: 'Betriebssystem, Gerätetreiber und Dienstprogramme wie Backup- oder Defragmentierungstools' },
      { id: 'c', text: 'Kassensoftware und Warenwirtschaftssystem' },
      { id: 'd', text: 'Browser, Bildbearbeitung und Videokonferenzsoftware' },
    ],
    correct: ['b'],
    multi: false,
    explanation:
      'Systemsoftware (Betriebssystem, Treiber, Utilities) betreibt und verwaltet die Hardware; Anwendungssoftware löst fachliche Aufgaben der Benutzer (Standard- oder Individualsoftware).',
  },
  {
    id: 'ap-mc-011',
    section: 'arbeitsplatz',
    topic: 'barrierefreiheit',
    type: 'multiple_choice',
    title: 'Barrierefreie Arbeitsplatzausstattung',
    scenario: 'Die Stadtverwaltung Lindenau stellt eine stark sehbehinderte Sachbearbeiterin ein. Ihr Arbeitsplatz soll barrierefrei ausgestattet werden.',
    text: 'Welche Maßnahme ist für diesen Arbeitsplatz am wichtigsten?',
    points: 2,
    difficulty: 1,
    options: [
      { id: 'a', text: 'Eine Screenreader-Software und/oder Bildschirmvergrößerung sowie eine Braillezeile in Kombination mit barrierefrei gestalteten Anwendungen (z. B. nach BITV/WCAG).' },
      { id: 'b', text: 'Ein besonders großer 4K-Monitor mit maximaler Auflösung, damit mehr Inhalt gleichzeitig dargestellt werden kann.' },
      { id: 'c', text: 'Ein Headset mit Geräuschunterdrückung für Videokonferenzen.' },
      { id: 'd', text: 'Eine ergonomische Maus mit programmierbaren Tasten.' },
    ],
    correct: ['a'],
    multi: false,
    explanation:
      'Assistive Technologien (Screenreader, Vergrößerung, Braillezeile) funktionieren nur, wenn auch die Software barrierefrei ist (semantische Struktur, Alternativtexte, Tastaturbedienung). Eine höhere Auflösung verkleinert Inhalte sogar.',
  },

  /* ===================== Zuordnung (4 Punkte) ===================== */
  {
    id: 'ap-ma-001',
    section: 'arbeitsplatz',
    topic: 'hardware',
    type: 'matching',
    title: 'Aufgaben von Hardwarekomponenten',
    scenario: 'Ein neuer Auszubildender der Systemhaus Weber GmbH soll beim Zusammenbau einer Workstation die Funktion der einzelnen Komponenten kennenlernen.',
    text: 'Ordnen Sie jeder Beschreibung die passende Hardwarekomponente zu.',
    points: 4,
    difficulty: 1,
    left: [
      { id: 'l1', text: 'Führt die Befehle der Programme aus; Leistung hängt u. a. von Taktfrequenz und Kernanzahl ab' },
      { id: 'l2', text: 'Flüchtiger Arbeitsspeicher, in dem laufende Programme und Daten gehalten werden' },
      { id: 'l3', text: 'Berechnet die Bildausgabe und beschleunigt parallele Berechnungen, z. B. für 3D und KI' },
      { id: 'l4', text: 'Zentrale Platine, die alle Komponenten über Chipsatz, Sockel und Steckplätze verbindet' },
      { id: 'l5', text: 'Wandelt die Netzspannung in die benötigten Gleichspannungen (z. B. 12 V, 5 V, 3,3 V) um' },
      { id: 'l6', text: 'Nichtflüchtiger Massenspeicher auf Flash-Basis ohne bewegliche Teile' },
    ],
    right: [
      { id: 'r1', text: 'Netzteil' },
      { id: 'r2', text: 'Mainboard' },
      { id: 'r3', text: 'CPU' },
      { id: 'r4', text: 'RAM' },
      { id: 'r5', text: 'GPU / Grafikkarte' },
      { id: 'r6', text: 'SSD' },
      { id: 'r7', text: 'HDD' },
      { id: 'r8', text: 'BIOS/UEFI' },
    ],
    pairs: { l1: 'r3', l2: 'r4', l3: 'r5', l4: 'r2', l5: 'r1', l6: 'r6' },
    explanation:
      'HDDs sind ebenfalls nichtflüchtig, haben aber rotierende Magnetscheiben. BIOS/UEFI ist die Firmware auf dem Mainboard, die den Startvorgang steuert.',
  },
  {
    id: 'ap-ma-002',
    section: 'arbeitsplatz',
    topic: 'lizenzmodelle',
    type: 'matching',
    title: 'Lizenzmodelle',
    scenario: 'Die Reiseplattform TripNest stellt ihre Softwarebeschaffung um und lässt sich die verschiedenen Lizenzmodelle erklären.',
    text: 'Ordnen Sie jeder Beschreibung das passende Lizenzmodell zu.',
    points: 4,
    difficulty: 2,
    left: [
      { id: 'l1', text: 'Die Lizenz ist an eine bestimmte, namentlich festgelegte Person gebunden' },
      { id: 'l2', text: 'Es wird nur die Anzahl der gleichzeitig aktiven Nutzer begrenzt; wer nicht angemeldet ist, belegt keine Lizenz' },
      { id: 'l3', text: 'Nutzungsrecht wird für einen Zeitraum (z. B. monatlich) gegen wiederkehrende Zahlung eingeräumt' },
      { id: 'l4', text: 'Ein Rahmenvertrag über eine größere Anzahl Lizenzen zu Sonderkonditionen mit einem Lizenzschlüssel' },
      { id: 'l5', text: 'Software wird gemeinsam mit neuer Hardware ausgeliefert und ist an dieses Gerät gebunden' },
    ],
    right: [
      { id: 'r1', text: 'Named-User-Lizenz' },
      { id: 'r2', text: 'Concurrent-User-Lizenz (Floating)' },
      { id: 'r3', text: 'Subscription / Abonnement' },
      { id: 'r4', text: 'Volumenlizenz' },
      { id: 'r5', text: 'OEM-Lizenz' },
      { id: 'r6', text: 'Einzelplatzlizenz (Retail)' },
      { id: 'r7', text: 'Freeware' },
    ],
    pairs: { l1: 'r1', l2: 'r2', l3: 'r3', l4: 'r4', l5: 'r5' },
    explanation:
      'Named User = personengebunden, Concurrent User = gleichzeitige Nutzer, Subscription = zeitlich befristet, Volumenlizenz = Mengenvertrag, OEM = hardwaregebunden. Freeware ist kostenlos, aber meist nicht quelloffen.',
  },
  {
    id: 'ap-ma-003',
    section: 'arbeitsplatz',
    topic: 'schnittstellen',
    type: 'matching',
    title: 'Schnittstellen am Arbeitsplatz',
    scenario: 'Die Filmproduktion Lichtspiel GmbH stattet einen Schnittplatz mit externem Speicher, zwei Monitoren und Peripherie aus. Sie erklären die vorhandenen Anschlüsse.',
    text: 'Ordnen Sie jeder Beschreibung die passende Schnittstelle zu.',
    points: 4,
    difficulty: 2,
    left: [
      { id: 'l1', text: 'Universelle Schnittstelle mit bis zu 40 Gbit/s, die Daten, Bild und Strom über einen USB-C-Stecker überträgt und Daisy-Chaining erlaubt' },
      { id: 'l2', text: 'Digitale Bildschnittstelle aus der PC-Welt; unterstützt Multi-Stream für mehrere Monitore an einem Anschluss' },
      { id: 'l3', text: 'Digitale Bild- und Tonschnittstelle, verbreitet an Fernsehern, Beamern und Spielkonsolen' },
      { id: 'l4', text: 'Interne Schnittstelle für Festplatten und SSDs mit maximal 6 Gbit/s' },
      { id: 'l5', text: 'Interner Steckplatz-Standard mit Lanes, an den Grafikkarten und NVMe-SSDs angebunden werden' },
      { id: 'l6', text: 'Verbreitete externe Schnittstelle für Tastatur, Maus, Drucker und Speichersticks; Version 3.2 Gen 1 mit 5 Gbit/s' },
    ],
    right: [
      { id: 'r1', text: 'USB-A (USB 3.2 Gen 1)' },
      { id: 'r2', text: 'Thunderbolt 4' },
      { id: 'r3', text: 'DisplayPort' },
      { id: 'r4', text: 'HDMI' },
      { id: 'r5', text: 'SATA III' },
      { id: 'r6', text: 'PCI Express' },
      { id: 'r7', text: 'VGA' },
      { id: 'r8', text: 'PS/2' },
    ],
    pairs: { l1: 'r2', l2: 'r3', l3: 'r4', l4: 'r5', l5: 'r6', l6: 'r1' },
    explanation:
      'Thunderbolt 4 nutzt den USB-C-Stecker mit 40 Gbit/s; DisplayPort (MST) und HDMI sind digitale Bildschnittstellen; SATA und PCIe sind interne Bus-Schnittstellen. VGA ist analog, PS/2 veraltet.',
  },

  /* ===================== Lückentext (3 Punkte) ===================== */
  {
    id: 'ap-cl-001',
    section: 'arbeitsplatz',
    topic: 'speichereinheiten',
    type: 'cloze',
    title: 'Speichereinheiten und Präfixe',
    scenario: 'Sie erklären einem Kunden der Systemhaus Weber GmbH, warum sein Betriebssystem eine geringere Festplattenkapazität anzeigt als auf der Verpackung angegeben.',
    text: 'Ergänzen Sie den Text.',
    points: 3,
    difficulty: 2,
    template:
      'Ein Byte besteht aus {{b1}} Bit. Bei Binärpräfixen entspricht 1 KiB genau {{b2}} Byte, während 1 kB nach dem Dezimalsystem 1.000 Byte entspricht. Festplattenhersteller rechnen dezimal: 1 TB = 10^{{b3}} Byte. Eine mit 2 TB beworbene Festplatte zeigt das Betriebssystem daher mit etwa {{b4}} TiB an. Die Binärpräfixe (Ki, Mi, Gi, Ti) wurden von der {{b5}} standardisiert.',
    blanks: [
      { id: 'b1', accepted: ['8', 'acht'] },
      { id: 'b2', accepted: ['1024', '1.024'] },
      { id: 'b3', accepted: ['12'] },
      { id: 'b4', accepted: ['1,82', '1.82'], options: ['1,60', '1,82', '1,95', '2,00', '2,20'] },
      { id: 'b5', accepted: ['IEC', 'International Electrotechnical Commission'], options: ['IEC', 'ISO 9001', 'IEEE 802.3', 'DIN 69901', 'W3C'] },
    ],
    explanation:
      '2 × 10^12 Byte ÷ 1024^4 = 2 × 10^12 ÷ 1.099.511.627.776 ≈ 1,82 TiB. Die Binärpräfixe Ki/Mi/Gi/Ti sind in IEC 80000-13 genormt.',
  },
  {
    id: 'ap-cl-002',
    section: 'arbeitsplatz',
    topic: 'ergonomie',
    type: 'cloze',
    title: 'Bildschirmarbeitsplatz einrichten',
    scenario: 'Die Steuerkanzlei Bergmann & Partner bittet Sie um eine Checkliste für die ergonomische Einrichtung der neuen Arbeitsplätze.',
    text: 'Ergänzen Sie den Text.',
    points: 3,
    difficulty: 2,
    template:
      'Die Anforderungen an Bildschirmarbeitsplätze sind in Deutschland in der {{b1}} geregelt. Der Sehabstand zum Bildschirm sollte mindestens {{b2}} cm betragen. Der Bildschirm wird so aufgestellt, dass die Blickrichtung {{b3}} zur Fensterfront verläuft, um Blendung und Reflexionen zu vermeiden. Für Büroarbeit wird eine Beleuchtungsstärke von mindestens {{b4}} Lux empfohlen. Ober- und Unterarme sollen beim Tippen einen Winkel von etwa {{b5}} Grad bilden.',
    blanks: [
      { id: 'b1', accepted: ['Arbeitsstättenverordnung', 'ArbStättV', 'Arbeitsstättenverordnung (ArbStättV)'], options: ['Arbeitsstättenverordnung', 'Datenschutz-Grundverordnung', 'Betriebssicherheitsverordnung', 'Gewerbeordnung', 'Produkthaftungsgesetz'] },
      { id: 'b2', accepted: ['50', '50 cm'] },
      { id: 'b3', accepted: ['parallel'], options: ['parallel', 'senkrecht', 'frontal', 'diagonal'] },
      { id: 'b4', accepted: ['500'], options: ['100', '200', '500', '1000', '2000'] },
      { id: 'b5', accepted: ['90'] },
    ],
    explanation:
      'Die frühere Bildschirmarbeitsverordnung ist seit 2016 im Anhang 6 der Arbeitsstättenverordnung enthalten. Sehabstand 50–70 cm, Blickrichtung parallel zum Fenster, 500 Lux (ASR A3.4), 90°-Regel für Arme und Beine.',
  },
  {
    id: 'ap-cl-003',
    section: 'arbeitsplatz',
    topic: 'lizenzmodelle',
    type: 'cloze',
    title: 'Softwarelizenzen',
    scenario: 'Die Werbeagentur PixelPark inventarisiert ihre Software und dokumentiert die jeweiligen Lizenzbedingungen.',
    text: 'Ergänzen Sie den Text.',
    points: 3,
    difficulty: 2,
    template:
      'Bei {{b1}} Software ist der Quellcode nicht zugänglich; der Hersteller behält alle Rechte und räumt dem Nutzer nur ein Nutzungsrecht ein, das im {{b2}} (Endbenutzer-Lizenzvertrag) geregelt ist. Bei Open-Source-Software ist der Quellcode frei verfügbar. Lizenzen wie die GPL enthalten eine {{b3}}-Klausel, nach der abgeleitete Werke unter derselben Lizenz veröffentlicht werden müssen. Lizenzen wie MIT oder BSD gelten dagegen als {{b4}}. Beim {{b5}}-Modell zahlt der Kunde regelmäßig (z. B. jährlich) und verliert das Nutzungsrecht nach Vertragsende.',
    blanks: [
      { id: 'b1', accepted: ['proprietärer', 'proprietäre', 'proprietär', 'Closed-Source', 'closed source'], options: ['proprietärer', 'quelloffener', 'freier', 'öffentlicher'] },
      { id: 'b2', accepted: ['EULA', 'End User License Agreement', 'Endnutzer-Lizenzvertrag'] },
      { id: 'b3', accepted: ['Copyleft', 'Copy-Left'] },
      { id: 'b4', accepted: ['permissiv', 'permissive', 'freizügig', 'freizügige'], options: ['permissiv', 'restriktiv', 'kommerziell', 'gemeinfrei', 'proprietär'] },
      { id: 'b5', accepted: ['Subscription', 'Abonnement', 'Abo', 'Subskription', 'Subscription-Modell', 'Abo-Modell'] },
    ],
    explanation:
      'Proprietär = geschlossener Quellcode mit EULA. Copyleft (GPL) verpflichtet zur Weitergabe unter gleicher Lizenz, permissive Lizenzen (MIT, BSD, Apache) erlauben proprietäre Nutzung. Subscription = zeitlich befristetes Nutzungsrecht.',
  },
  {
    id: 'ap-cl-004',
    section: 'arbeitsplatz',
    topic: 'virtualisierung',
    type: 'cloze',
    title: 'Virtualisierung und Cloud',
    scenario: 'Das Start-up FoodLoop verlagert seine Entwicklungsumgebungen in die Cloud und diskutiert Begriffe im Team.',
    text: 'Ergänzen Sie den Text.',
    points: 3,
    difficulty: 2,
    template:
      'Die Software, die mehrere virtuelle Maschinen auf einer physischen Hardware ausführt und ihnen Ressourcen zuteilt, heißt {{b1}}. Mietet FoodLoop bei einem Cloud-Anbieter nur virtuelle Server, Speicher und Netzwerk und installiert Betriebssystem und Anwendungen selbst, handelt es sich um {{b2}}. Nutzt das Team dagegen eine fertige Anwendung wie ein Online-Office über den Browser, spricht man von {{b3}}. Wird die Cloud-Infrastruktur ausschließlich für ein einzelnes Unternehmen betrieben, nennt man sie {{b4}} Cloud. Der Zustand einer VM kann zu einem Zeitpunkt als {{b5}} gesichert werden, um z. B. vor einem Update eine Rückkehrmöglichkeit zu haben.',
    blanks: [
      { id: 'b1', accepted: ['Hypervisor', 'Virtual Machine Monitor', 'VMM'] },
      { id: 'b2', accepted: ['IaaS', 'Infrastructure as a Service', 'Infrastructure-as-a-Service'], options: ['IaaS', 'PaaS', 'SaaS', 'FaaS', 'On-Premises'] },
      { id: 'b3', accepted: ['SaaS', 'Software as a Service', 'Software-as-a-Service'], options: ['IaaS', 'PaaS', 'SaaS', 'FaaS', 'On-Premises'] },
      { id: 'b4', accepted: ['Private', 'Private Cloud', 'private'], options: ['Private', 'Public', 'Hybrid', 'Community'] },
      { id: 'b5', accepted: ['Snapshot', 'Schnappschuss', 'Sicherungspunkt'] },
    ],
    explanation:
      'Hypervisor (Typ 1 oder 2) verwaltet VMs. IaaS = Infrastruktur, PaaS = Plattform, SaaS = fertige Anwendung. Private Cloud = exklusiv für ein Unternehmen, Public Cloud = geteilt, Hybrid = Mischform. Snapshots frieren den VM-Zustand ein.',
  },

  /* ===================== Rechenaufgaben (5 Punkte) ===================== */
  {
    id: 'ap-ca-001',
    section: 'arbeitsplatz',
    topic: 'speicherbedarf',
    type: 'calculation',
    title: 'Speicherbedarf einer unkomprimierten Videoaufnahme',
    scenario: 'Die Filmproduktion Lichtspiel GmbH nimmt Rohmaterial unkomprimiert auf und benötigt eine Abschätzung des Speicherbedarfs für die Auswahl einer externen SSD.',
    text: 'Ein Video wird in Full HD (**1920 × 1080 Pixel**) mit einer Farbtiefe von **24 Bit** je Pixel und **25 Bildern pro Sekunde** unkomprimiert aufgezeichnet.\n\na) Berechnen Sie die Datenmenge eines Einzelbilds in Byte.\nb) Berechnen Sie die Datenrate in MB/s (1 MB = 10^6 Byte).\nc) Berechnen Sie den Speicherbedarf einer 10-minütigen Aufnahme in GB (1 GB = 10^9 Byte) und in GiB (1 GiB = 1024^3 Byte).\n\nGeben Sie den vollständigen Lösungsweg an.',
    points: 5,
    difficulty: 2,
    solution:
      'a) Pixel je Bild: 1920 × 1080 = 2.073.600 Pixel\nByte je Pixel: 24 Bit ÷ 8 = 3 Byte\nDatenmenge je Bild: 2.073.600 × 3 Byte = 6.220.800 Byte\n\nb) Datenrate: 6.220.800 Byte × 25 Bilder/s = 155.520.000 Byte/s = 155,52 MB/s\n\nc) Dauer: 10 min = 600 s\nSpeicherbedarf: 155.520.000 Byte/s × 600 s = 93.312.000.000 Byte\n= 93,312 GB (dezimal)\n= 93.312.000.000 ÷ 1.073.741.824 ≈ 86,90 GiB',
    expected: [
      { label: 'Datenmenge je Bild', value: 6220800, unit: 'Byte' },
      { label: 'Datenrate', value: 155.52, unit: 'MB/s', tolerance: 0.01 },
      { label: 'Speicherbedarf 10 min (dezimal)', value: 93.312, unit: 'GB', tolerance: 0.01 },
      { label: 'Speicherbedarf 10 min (binär)', value: 86.9, unit: 'GiB', tolerance: 0.05 },
    ],
    rubric: [
      { criterion: 'Datenmenge je Einzelbild korrekt (6.220.800 Byte) inkl. Bit-Byte-Umrechnung', points: 1.5 },
      { criterion: 'Datenrate korrekt (155,52 MB/s)', points: 1.5 },
      { criterion: 'Speicherbedarf in GB korrekt (93,312 GB)', points: 1 },
      { criterion: 'Umrechnung in GiB mit Basis 1024 korrekt (≈ 86,90 GiB)', points: 1 },
    ],
    explanation:
      'Unkomprimiertes Video erzeugt enorme Datenmengen; in der Praxis reduzieren Codecs wie H.264/H.265 das Volumen um den Faktor 50 bis 200.',
  },
  {
    id: 'ap-ca-002',
    section: 'arbeitsplatz',
    topic: 'energiekosten',
    type: 'calculation',
    title: 'Energiekosten der Büro-PCs',
    scenario: 'Die Versicherung NordSecur AG prüft im Rahmen einer Green-IT-Initiative, ob der Austausch der Büro-PCs durch sparsame Mini-PCs wirtschaftlich ist.',
    text: 'In einer Abteilung stehen **25 PCs**, die im Betrieb durchschnittlich **180 W** aufnehmen. Sie laufen an **220 Arbeitstagen** pro Jahr jeweils **8 Stunden**; außerhalb dieser Zeit sind sie ausgeschaltet. Der Strompreis beträgt **0,32 €/kWh**.\n\na) Berechnen Sie den jährlichen Energieverbrauch aller 25 PCs in kWh.\nb) Berechnen Sie die jährlichen Stromkosten.\nc) Die PCs sollen durch Mini-PCs mit **45 W** Leistungsaufnahme ersetzt werden. Berechnen Sie die jährliche Kostenersparnis.\n\nGeben Sie den vollständigen Lösungsweg an.',
    points: 5,
    difficulty: 1,
    solution:
      'a) Betriebsstunden je Jahr: 220 Tage × 8 h = 1.760 h\nVerbrauch je PC: 180 W × 1.760 h = 316.800 Wh = 316,8 kWh\nVerbrauch aller PCs: 25 × 316,8 kWh = 7.920 kWh\n\nb) Stromkosten: 7.920 kWh × 0,32 €/kWh = 2.534,40 €\n\nc) Mini-PC: 45 W × 1.760 h = 79.200 Wh = 79,2 kWh je Gerät\n25 Geräte: 1.980 kWh → 1.980 kWh × 0,32 €/kWh = 633,60 €\nErsparnis: 2.534,40 € − 633,60 € = 1.900,80 € pro Jahr',
    expected: [
      { label: 'Jahresverbrauch alle PCs', value: 7920, unit: 'kWh', tolerance: 0.1 },
      { label: 'Jährliche Stromkosten', value: 2534.4, unit: '€', tolerance: 0.01 },
      { label: 'Jährliche Ersparnis', value: 1900.8, unit: '€', tolerance: 0.01 },
    ],
    rubric: [
      { criterion: 'Betriebsstunden und Jahresverbrauch korrekt (7.920 kWh) inkl. Umrechnung Wh → kWh', points: 2 },
      { criterion: 'Stromkosten korrekt (2.534,40 €)', points: 1 },
      { criterion: 'Verbrauch und Kosten der Mini-PCs sowie Ersparnis korrekt (1.900,80 €)', points: 2 },
    ],
    explanation:
      'Energie (kWh) = Leistung (kW) × Zeit (h). Für eine Wirtschaftlichkeitsbetrachtung würde man die Ersparnis anschließend den Anschaffungskosten gegenüberstellen (Amortisation).',
  },
  {
    id: 'ap-ca-003',
    section: 'arbeitsplatz',
    topic: 'drucker',
    type: 'calculation',
    title: 'Seitenpreis und Gesamtkosten von Druckern',
    scenario: 'Die Anwaltskanzlei Roth & Kollegen vergleicht für einen Arbeitsplatz einen Laserdrucker und einen Tintenstrahldrucker über eine Nutzungsdauer von drei Jahren.',
    text: '**Laserdrucker:** Anschaffung 480 €, Tonerkartusche 95 € mit einer Reichweite von 3.000 Seiten.\n**Tintenstrahldrucker:** Anschaffung 150 €, Patronensatz 42 € mit einer Reichweite von 700 Seiten.\n\nDas Druckvolumen beträgt **12.000 Seiten pro Jahr**. Rechnen Sie mit dem rechnerischen (anteiligen) Verbrauchsmaterialpreis je Seite; alle Preise sind Nettopreise.\n\na) Berechnen Sie für beide Drucker die Verbrauchsmaterialkosten je Seite.\nb) Berechnen Sie die Gesamtkosten (Anschaffung + Verbrauchsmaterial) beider Drucker über drei Jahre.\nc) Berechnen Sie den Gesamtseitenpreis (inkl. Anschaffung) beider Drucker über drei Jahre und geben Sie an, welcher Drucker günstiger ist.\n\nGeben Sie den vollständigen Lösungsweg an.',
    points: 5,
    difficulty: 2,
    solution:
      'a) Laser: 95 € ÷ 3.000 Seiten = 0,03167 €/Seite ≈ 3,17 ct\nTinte: 42 € ÷ 700 Seiten = 0,06 €/Seite = 6,00 ct\n\nb) Seiten in 3 Jahren: 3 × 12.000 = 36.000 Seiten\nLaser: 36.000 × 0,03167 € = 1.140 € (= 12 Toner × 95 €) → Gesamt: 480 € + 1.140 € = 1.620 €\nTinte: 36.000 × 0,06 € = 2.160 € → Gesamt: 150 € + 2.160 € = 2.310 €\n\nc) Gesamtseitenpreis Laser: 1.620 € ÷ 36.000 = 0,045 €/Seite = 4,5 ct\nGesamtseitenpreis Tinte: 2.310 € ÷ 36.000 ≈ 0,0642 €/Seite ≈ 6,4 ct\nDer Laserdrucker ist über drei Jahre um 690 € günstiger.',
    expected: [
      { label: 'Verbrauchskosten je Seite Laser', value: 0.0317, unit: '€', tolerance: 0.0005 },
      { label: 'Verbrauchskosten je Seite Tinte', value: 0.06, unit: '€', tolerance: 0.0005 },
      { label: 'Gesamtkosten Laser 3 Jahre', value: 1620, unit: '€', tolerance: 1 },
      { label: 'Gesamtkosten Tinte 3 Jahre', value: 2310, unit: '€', tolerance: 1 },
      { label: 'Gesamtseitenpreis Laser', value: 0.045, unit: '€', tolerance: 0.0005 },
      { label: 'Gesamtseitenpreis Tinte', value: 0.0642, unit: '€', tolerance: 0.0005 },
    ],
    rubric: [
      { criterion: 'Verbrauchsmaterialkosten je Seite korrekt (ca. 3,17 ct / 6,00 ct)', points: 1.5 },
      { criterion: 'Gesamtkosten über 3 Jahre korrekt (1.620 € / 2.310 €)', points: 2 },
      { criterion: 'Gesamtseitenpreis korrekt (4,5 ct / ca. 6,4 ct) und richtige Empfehlung (Laser)', points: 1.5 },
    ],
    explanation:
      'Bei hohem Druckvolumen gleicht der niedrigere Seitenpreis des Laserdruckers die höheren Anschaffungskosten schnell aus – eine typische TCO-Betrachtung.',
  },
  {
    id: 'ap-ca-004',
    section: 'arbeitsplatz',
    topic: 'monitore',
    type: 'calculation',
    title: 'Pixeldichte von Monitoren',
    scenario: 'Die Werbeagentur PixelPark möchte für die Grafikabteilung neue 27-Zoll-Monitore beschaffen und vergleicht zwei Modelle mit unterschiedlicher Auflösung.',
    text: 'Zur Auswahl stehen zwei Monitore mit einer Bildschirmdiagonale von jeweils **27 Zoll**:\n- Modell 1: **2560 × 1440 Pixel** (WQHD)\n- Modell 2: **3840 × 2160 Pixel** (4K UHD)\n\na) Berechnen Sie die Gesamtzahl der Pixel beider Modelle.\nb) Berechnen Sie die Pixeldichte in ppi (Pixel pro Zoll) beider Modelle. Hinweis: Die Diagonale in Pixeln ergibt sich nach dem Satz des Pythagoras aus Breite und Höhe.\nc) Geben Sie das Seitenverhältnis der Monitore an.\n\nGeben Sie den vollständigen Lösungsweg an; runden Sie die Pixeldichte auf eine Nachkommastelle.',
    points: 5,
    difficulty: 3,
    solution:
      'a) Modell 1: 2560 × 1440 = 3.686.400 Pixel\nModell 2: 3840 × 2160 = 8.294.400 Pixel\n\nb) Diagonale in Pixel = √(Breite² + Höhe²)\nModell 1: √(2560² + 1440²) = √(6.553.600 + 2.073.600) = √8.627.200 ≈ 2.937,2 Pixel\nppi = 2.937,2 ÷ 27 Zoll ≈ 108,8 ppi\nModell 2: √(3840² + 2160²) = √(14.745.600 + 4.665.600) = √19.411.200 ≈ 4.405,8 Pixel\nppi = 4.405,8 ÷ 27 Zoll ≈ 163,2 ppi\n\nc) 2560 : 1440 = 16 : 9 und 3840 : 2160 = 16 : 9 → Seitenverhältnis 16:9',
    expected: [
      { label: 'Pixel Modell 1', value: 3686400, unit: 'Pixel' },
      { label: 'Pixel Modell 2', value: 8294400, unit: 'Pixel' },
      { label: 'Pixeldichte Modell 1', value: 108.8, unit: 'ppi', tolerance: 0.3 },
      { label: 'Pixeldichte Modell 2', value: 163.2, unit: 'ppi', tolerance: 0.3 },
    ],
    rubric: [
      { criterion: 'Pixelanzahl beider Modelle korrekt (3.686.400 / 8.294.400)', points: 1 },
      { criterion: 'Ansatz Pythagoras für die Diagonale in Pixeln korrekt', points: 1 },
      { criterion: 'Pixeldichten korrekt (≈ 108,8 ppi / ≈ 163,2 ppi)', points: 2 },
      { criterion: 'Seitenverhältnis 16:9 korrekt', points: 1 },
    ],
    explanation:
      'Die Pixeldichte bestimmt die Bildschärfe. Bei hoher Pixeldichte (4K auf 27 Zoll) muss das Betriebssystem meist eine Skalierung (z. B. 150 %) verwenden, damit Schrift lesbar bleibt.',
  },
  {
    id: 'ap-ca-005',
    section: 'arbeitsplatz',
    topic: 'angebotsvergleich',
    type: 'calculation',
    title: 'Rechnungsbetrag mit Rabatt, Skonto und Umsatzsteuer',
    scenario: 'Die Möbelmanufaktur Holzwerk Riedel bestellt vier CAD-Workstations beim Systemhaus Weber GmbH.',
    text: 'Der Listenpreis je Workstation beträgt **2.400 € netto**. Das Systemhaus gewährt **15 % Rabatt**. Bei Zahlung innerhalb von 14 Tagen werden zusätzlich **2 % Skonto** gewährt. Die Umsatzsteuer beträgt **19 %**. Die Möbelmanufaktur zahlt innerhalb der Skontofrist.\n\na) Berechnen Sie den Nettopreis nach Rabatt für alle vier Workstations.\nb) Berechnen Sie den Nettobetrag nach Abzug des Skontos und den Skontobetrag.\nc) Berechnen Sie den zu zahlenden Bruttobetrag.\n\nGeben Sie den vollständigen Lösungsweg an.',
    points: 5,
    difficulty: 1,
    solution:
      'a) Listenpreis gesamt: 4 × 2.400 € = 9.600 €\nRabatt: 9.600 € × 15 % = 1.440 €\nNetto nach Rabatt: 9.600 € − 1.440 € = 8.160 €\n\nb) Skonto: 8.160 € × 2 % = 163,20 €\nNetto nach Skonto: 8.160 € − 163,20 € = 7.996,80 €\n\nc) Umsatzsteuer: 7.996,80 € × 19 % = 1.519,39 €\nBruttobetrag: 7.996,80 € × 1,19 = 9.516,19 €',
    expected: [
      { label: 'Netto nach Rabatt', value: 8160, unit: '€', tolerance: 0.01 },
      { label: 'Skontobetrag', value: 163.2, unit: '€', tolerance: 0.01 },
      { label: 'Netto nach Skonto', value: 7996.8, unit: '€', tolerance: 0.01 },
      { label: 'Bruttobetrag', value: 9516.19, unit: '€', tolerance: 0.02 },
    ],
    rubric: [
      { criterion: 'Nettopreis nach Rabatt korrekt (8.160 €)', points: 1.5 },
      { criterion: 'Skontobetrag und Netto nach Skonto korrekt (163,20 € / 7.996,80 €)', points: 1.5 },
      { criterion: 'Bruttobetrag mit 19 % Umsatzsteuer korrekt (9.516,19 €)', points: 2 },
    ],
    explanation:
      'Reihenfolge: Listenpreis − Rabatt = Zieleinkaufspreis; − Skonto = Bareinkaufspreis; darauf wird die Umsatzsteuer berechnet. Skonto wirkt wie ein hoher Jahreszins und sollte genutzt werden.',
  },
  {
    id: 'ap-ca-006',
    section: 'arbeitsplatz',
    topic: 'virtualisierung',
    type: 'calculation',
    title: 'Ressourcenbedarf eines Virtualisierungshosts',
    scenario: 'Die CodeCraft GmbH möchte auf einem neuen Server drei virtuelle Maschinen für Entwicklung, Test und Build betreiben und muss die Hardware dimensionieren.',
    text: 'Geplante virtuelle Maschinen:\n\n| VM | vCPUs | RAM | Festplatte\n| Entwicklung | 2 | 8 GiB | 120 GB\n| Test | 2 | 8 GiB | 120 GB\n| Build-Server | 4 | 16 GiB | 250 GB\n\nFür Hypervisor und Host-Betriebssystem sind zusätzlich **4 GiB RAM** und **60 GB** Festplatte zu reservieren. Auf den Gesamtbedarf an RAM soll eine Reserve von **20 %** aufgeschlagen werden.\n\na) Berechnen Sie den RAM-Bedarf aller VMs sowie den Gesamt-RAM-Bedarf inklusive Host und Reserve.\nb) Der Server wird mit 16-GiB-Modulen bestückt. Wie viele Module werden mindestens benötigt und welche RAM-Größe ergibt sich?\nc) Berechnen Sie den gesamten Festplattenbedarf in GB und die Summe der zugewiesenen vCPUs.\n\nGeben Sie den vollständigen Lösungsweg an.',
    points: 5,
    difficulty: 2,
    solution:
      'a) RAM der VMs: 8 + 8 + 16 = 32 GiB\nInklusive Host: 32 GiB + 4 GiB = 36 GiB\nMit 20 % Reserve: 36 GiB × 1,2 = 43,2 GiB\n\nb) 43,2 GiB ÷ 16 GiB = 2,7 → aufrunden auf 3 Module\nErgebnis: 3 × 16 GiB = 48 GiB\n\nc) Festplatte: 120 + 120 + 250 + 60 = 550 GB\nvCPUs: 2 + 2 + 4 = 8 vCPUs',
    expected: [
      { label: 'RAM der VMs', value: 32, unit: 'GiB' },
      { label: 'Gesamt-RAM inkl. Host und Reserve', value: 43.2, unit: 'GiB', tolerance: 0.05 },
      { label: 'Anzahl 16-GiB-Module', value: 3 },
      { label: 'RAM-Ausbau', value: 48, unit: 'GiB' },
      { label: 'Festplattenbedarf', value: 550, unit: 'GB' },
      { label: 'Summe vCPUs', value: 8 },
    ],
    rubric: [
      { criterion: 'RAM-Bedarf der VMs und Gesamtbedarf inkl. Host und 20 % Reserve korrekt (32 GiB / 43,2 GiB)', points: 2 },
      { criterion: 'Anzahl Module korrekt aufgerundet (3 Module = 48 GiB)', points: 1.5 },
      { criterion: 'Festplattenbedarf (550 GB) und vCPU-Summe (8) korrekt', points: 1.5 },
    ],
    explanation:
      'Bei der Dimensionierung eines Hosts wird der Bedarf aller Gäste plus Hypervisor plus Reserve addiert; Speichermodule können nur in ganzen Einheiten beschafft werden, daher wird aufgerundet.',
  },

  /* ===================== Freitext (3 Punkte) ===================== */
  {
    id: 'ap-ft-001',
    section: 'arbeitsplatz',
    topic: 'thin-client',
    type: 'free_text',
    title: 'Thin Clients im Callcenter',
    scenario: 'Das Callcenter der Versicherung NordSecur AG möchte 80 Arbeitsplätze mit Thin Clients und einem Terminalserver statt mit klassischen PCs ausstatten.',
    text: 'Nennen Sie zwei Vorteile und einen Nachteil dieser Lösung gegenüber klassischen PCs (Fat Clients) und erläutern Sie diese jeweils kurz.',
    points: 3,
    difficulty: 2,
    solution:
      'Vorteile (Beispiele):\n- Zentrale Administration: Software, Updates und Sicherheitsrichtlinien werden nur auf dem Terminalserver gepflegt, was den Aufwand für 80 Arbeitsplätze stark reduziert.\n- Geringere Kosten: Thin Clients sind günstiger in Anschaffung und Energieverbrauch (wenige Watt) und haben eine längere Nutzungsdauer.\n- Höhere Sicherheit: Keine lokalen Daten auf dem Gerät, geringeres Risiko bei Diebstahl oder Malware.\nNachteile (Beispiele):\n- Abhängigkeit von Netzwerk und Server: Fällt der Terminalserver oder das Netz aus, können alle 80 Arbeitsplätze nicht arbeiten (Single Point of Failure) – Redundanz erforderlich.\n- Hoher Server- und Lizenzaufwand (Terminalserver-CALs), eingeschränkte Leistung bei grafikintensiven Anwendungen.',
    rubric: [
      { criterion: 'Zwei zutreffende Vorteile (z. B. zentrale Administration, Kosten/Energie, Sicherheit) genannt und erläutert', points: 2 },
      { criterion: 'Ein zutreffender Nachteil (z. B. Abhängigkeit vom Server/Netz, Lizenzkosten) genannt und erläutert', points: 1 },
    ],
    explanation:
      'Thin Clients verlagern Rechenleistung und Datenhaltung auf den Server; das senkt Betriebskosten und Administrationsaufwand, erhöht aber die Abhängigkeit von Serververfügbarkeit und Netzwerk.',
  },
  {
    id: 'ap-ft-002',
    section: 'arbeitsplatz',
    topic: 'ergonomie',
    type: 'free_text',
    title: 'Ergonomische Arbeitsplatzgestaltung',
    scenario: 'Eine Mitarbeiterin der Steuerkanzlei Bergmann & Partner klagt über Nacken- und Augenbeschwerden nach langen Bildschirmarbeitstagen. Sie sollen ihren Arbeitsplatz überprüfen.',
    text: 'Nennen Sie drei Maßnahmen zur ergonomischen Verbesserung des Bildschirmarbeitsplatzes und begründen Sie jede Maßnahme kurz.',
    points: 3,
    difficulty: 1,
    solution:
      'Mögliche Maßnahmen:\n- Bildschirm richtig positionieren: Oberkante auf Augenhöhe, Sehabstand 50–70 cm, leicht nach hinten geneigt → entlastet Nacken und Augen.\n- Blendfreie Aufstellung: Blickrichtung parallel zum Fenster, Jalousien, kein direktes Licht auf dem Bildschirm → vermeidet Reflexionen und Augenbelastung.\n- Höhenverstellbarer Bürostuhl und Tisch: Ober-/Unterarme und Ober-/Unterschenkel im 90°-Winkel, Füße flach auf dem Boden, ggf. Sitz-Steh-Tisch → ergonomische Haltung, Bewegungswechsel.\n- Ausreichende Beleuchtung (ca. 500 Lux), regelmäßige Pausen und Blickwechsel in die Ferne → beugt Ermüdung der Augen vor.\n- Externe Tastatur und Maus bei Notebook-Nutzung, ausreichend Tiefe der Arbeitsfläche zum Auflegen der Handballen.',
    rubric: [
      { criterion: 'Drei geeignete ergonomische Maßnahmen genannt', points: 1.5 },
      { criterion: 'Jede Maßnahme nachvollziehbar mit Bezug zu Nacken-/Augenbeschwerden begründet', points: 1.5 },
    ],
    explanation:
      'Die Arbeitsstättenverordnung (Anhang 6) verpflichtet den Arbeitgeber zur ergonomischen Gestaltung von Bildschirmarbeitsplätzen; Beschwerden entstehen häufig durch falsche Monitorhöhe, Blendung und starre Sitzhaltung.',
  },
  {
    id: 'ap-ft-003',
    section: 'arbeitsplatz',
    topic: 'gewaehrleistung',
    type: 'free_text',
    title: 'Gewährleistung, Garantie und Mängelrüge',
    scenario: 'Die Gärtnerei Grünwald hat vor acht Monaten bei einem Fachhändler einen Multifunktionsdrucker gekauft. Nun fällt die Scaneinheit aus. Der Händler verweist auf die Herstellergarantie von nur sechs Monaten.',
    text: 'Erläutern Sie den Unterschied zwischen Gewährleistung und Garantie und beurteilen Sie, ob die Gärtnerei trotz der abgelaufenen Garantie Ansprüche geltend machen kann. Nennen Sie außerdem, welche Rechte ihr im Gewährleistungsfall zustehen.',
    points: 3,
    difficulty: 2,
    solution:
      'Gewährleistung (Sachmängelhaftung, §§ 434 ff. BGB) ist gesetzlich vorgeschrieben, richtet sich gegen den Verkäufer und beträgt bei neuen Sachen zwei Jahre ab Übergabe. Sie umfasst Mängel, die bereits bei Übergabe vorlagen (bei Verbrauchern Beweislastumkehr im ersten Jahr).\nGarantie ist eine freiwillige, zusätzliche Zusage (meist des Herstellers), deren Umfang und Dauer frei festgelegt werden; sie schränkt die Gewährleistung nicht ein.\nBeurteilung: Die Garantie ist zwar abgelaufen, die zweijährige Gewährleistung gegenüber dem Händler besteht aber weiterhin. Die Gärtnerei kann den Mangel beim Händler rügen, sofern es sich um einen bei Übergabe vorhandenen Mangel handelt (nicht um Verschleiß oder Fehlbedienung).\nRechte: zunächst Nacherfüllung (Reparatur oder Ersatzlieferung, Wahl liegt beim Käufer); scheitert diese, Minderung des Kaufpreises oder Rücktritt vom Vertrag, ggf. Schadensersatz.',
    rubric: [
      { criterion: 'Unterschied Gewährleistung (gesetzlich, Verkäufer, 2 Jahre) und Garantie (freiwillig, meist Hersteller) korrekt erläutert', points: 1.5 },
      { criterion: 'Korrekte Beurteilung: Gewährleistungsanspruch gegen den Händler besteht trotz abgelaufener Garantie', points: 0.5 },
      { criterion: 'Gewährleistungsrechte genannt (Nacherfüllung, dann Minderung/Rücktritt, ggf. Schadensersatz)', points: 1 },
    ],
    explanation:
      'Die Garantie ergänzt die Gewährleistung, ersetzt sie aber nicht. Ansprechpartner für die Gewährleistung ist immer der Vertragspartner (Händler), nicht der Hersteller.',
  },
  {
    id: 'ap-ft-004',
    section: 'arbeitsplatz',
    topic: 'green-it',
    type: 'free_text',
    title: 'Green IT bei der Arbeitsplatzausstattung',
    scenario: 'Die Stadtwerke Nordhafen AG wollen bei der anstehenden Neuausstattung von 200 Büroarbeitsplätzen Nachhaltigkeitsziele (Green IT) berücksichtigen.',
    text: 'Nennen Sie drei Maßnahmen im Sinne von Green IT, die bei Beschaffung und Betrieb der Arbeitsplätze umgesetzt werden können, und erläutern Sie jeweils den Nutzen.',
    points: 3,
    difficulty: 2,
    solution:
      'Mögliche Maßnahmen:\n- Energieeffiziente Geräte beschaffen (z. B. Mini-PCs, Notebooks, Thin Clients, Monitore mit Energielabel/TCO-Zertifikat) → geringerer Stromverbrauch und niedrigere Betriebskosten.\n- Energiesparfunktionen zentral konfigurieren (Standby, automatisches Abschalten von Monitoren, Wake-on-LAN statt Dauerbetrieb) → Verbrauch außerhalb der Arbeitszeit senken.\n- Langlebige, reparierbare und aufrüstbare Geräte wählen sowie Nutzungsdauer verlängern (z. B. SSD-/RAM-Upgrade statt Neukauf), Refurbished-Geräte einsetzen → weniger Elektroschrott und Ressourcenverbrauch.\n- Umweltgerechte Entsorgung und Rücknahme über den Hersteller (ElektroG) → Wiederverwertung von Rohstoffen.\n- Zentrale Multifunktionsdrucker mit Duplex-Standard statt Arbeitsplatzdrucker → weniger Geräte, Toner und Papier.\n- Virtualisierung/Konsolidierung von Servern, Nutzung von Ökostrom.',
    rubric: [
      { criterion: 'Drei geeignete Green-IT-Maßnahmen genannt', points: 1.5 },
      { criterion: 'Nutzen jeder Maßnahme (Energie, Ressourcen, Kosten, Abfall) nachvollziehbar erläutert', points: 1.5 },
    ],
    explanation:
      'Green IT betrachtet den gesamten Lebenszyklus: umweltgerechte Herstellung und Beschaffung, energieeffizienter Betrieb, lange Nutzung und fachgerechte Entsorgung.',
  },
  {
    id: 'ap-ft-005',
    section: 'arbeitsplatz',
    topic: 'inbetriebnahme',
    type: 'free_text',
    title: 'Inbetriebnahme und Übergabe eines Arbeitsplatzes',
    scenario: 'Sie haben für die Bäckereikette Kornblume einen neuen Büroarbeitsplatz aufgebaut und sollen ihn an die Mitarbeiterin übergeben.',
    text: 'Nennen Sie drei Tätigkeiten, die Sie bei der Inbetriebnahme vor der Übergabe durchführen, und beschreiben Sie, welche Angaben das Übergabeprotokoll bzw. die Dokumentation enthalten sollte.',
    points: 3,
    difficulty: 1,
    solution:
      'Tätigkeiten bei der Inbetriebnahme (Beispiele):\n- Funktionstest aller Komponenten (Boot, Monitor, Peripherie, Netzwerkverbindung, Drucker).\n- Betriebssystem und Software installieren/aktualisieren, Updates und Treiber einspielen, Virenschutz aktivieren.\n- Benutzerkonto anlegen, Rechte zuweisen, Anmeldung testen, Netzlaufwerke und E-Mail einrichten.\n- Sicherheitsrichtlinien umsetzen (Passwort, Verschlüsselung, Bildschirmsperre) und Backup einrichten.\n- Kurze Einweisung der Mitarbeiterin.\nÜbergabeprotokoll / Dokumentation:\n- Datum, Übergebender und Empfänger, Unterschriften.\n- Inventar: Gerätetyp, Seriennummern, Inventarnummern, Zubehör.\n- Konfiguration: Hostname, IP/MAC-Adresse, installierte Software mit Lizenzen/Versionen, Benutzerkonto.\n- Durchgeführte Tests und deren Ergebnis, offene Punkte, Hinweise zur Nutzung und Ansprechpartner für Support.',
    rubric: [
      { criterion: 'Drei sinnvolle Tätigkeiten der Inbetriebnahme genannt (Funktionstest, Installation/Updates, Konten/Rechte, Sicherheit, Einweisung)', points: 1.5 },
      { criterion: 'Wesentliche Inhalte des Übergabeprotokolls genannt (Inventar/Seriennummern, Konfiguration, Software/Lizenzen, Datum/Unterschriften, Testergebnis)', points: 1.5 },
    ],
    explanation:
      'Eine vollständige Dokumentation ist Grundlage für Inventarisierung, Lizenzmanagement, Support und spätere Fehlersuche; das Übergabeprotokoll belegt den ordnungsgemäßen Zustand bei der Übergabe.',
  },
  {
    id: 'ap-mc-012',
    section: 'arbeitsplatz',
    topic: 'ki',
    type: 'multiple_choice',
    title: 'KI-Systeme im Unternehmen einsetzen',
    scenario: 'Die Versicherungsagentur Rheinschutz möchte einen KI-Chatbot zur Beantwortung von Kundenanfragen einführen.',
    text: 'Welche Aussagen zum Einsatz von KI-Systemen treffen zu? (Mehrere Antworten möglich)',
    points: 3,
    difficulty: 2,
    options: [
      { id: 'a', text: 'Die Qualität eines KI-Modells hängt von seinen Trainingsdaten ab; Verzerrungen (Bias) in den Daten können zu diskriminierenden Ergebnissen führen.' },
      { id: 'b', text: 'Werden personenbezogene Kundendaten an einen Cloud-KI-Dienst übermittelt, sind DSGVO-Anforderungen (Rechtsgrundlage, Auftragsverarbeitung) zu beachten.' },
      { id: 'c', text: 'Generative KI-Systeme liefern auf dieselbe Eingabe stets exakt dieselbe Ausgabe.' },
      { id: 'd', text: 'Ausgaben generativer KI müssen fachlich geprüft werden, da sie falsche Inhalte überzeugend darstellen können.' },
      { id: 'e', text: 'Ein einmal trainiertes Sprachmodell aktualisiert sein Wissen automatisch mit jeder Nutzeranfrage.' },
    ],
    correct: ['a', 'b', 'd'],
    multi: true,
    explanation: 'KI-Modelle sind statistische Systeme: Ergebnisse sind nicht deterministisch, hängen von Trainingsdaten ab und können falsch sein. Der Wissensstand endet mit dem Training; Datenschutz gilt uneingeschränkt.',
  },
  {
    id: 'ap-mc-013',
    section: 'arbeitsplatz',
    topic: 'anwendungssoftware',
    type: 'multiple_choice',
    title: 'Betriebliche Anwendungssysteme',
    scenario: 'Die Möbelmanufaktur Holzwerk Riedel möchte Buchhaltung, Lagerverwaltung, Einkauf und Produktionsplanung künftig in einem integrierten System mit einer gemeinsamen Datenbasis abbilden.',
    text: 'Welche Systemkategorie erfüllt diese Anforderung?',
    points: 2,
    difficulty: 1,
    options: [
      { id: 'a', text: 'ERP-System (Enterprise Resource Planning)' },
      { id: 'b', text: 'CRM-System (Customer Relationship Management)' },
      { id: 'c', text: 'CMS (Content Management System)' },
      { id: 'd', text: 'DMS (Dokumentenmanagementsystem)' },
    ],
    correct: ['a'],
    multi: false,
    explanation: 'ERP-Systeme integrieren die betrieblichen Kernprozesse (Finanzen, Lager, Einkauf, Produktion, Personal) auf einer gemeinsamen Datenbasis. CRM fokussiert Kundenbeziehungen, CMS Webinhalte, DMS Dokumente.',
  },
];
