/**
 * Ausfüllbilder: Diagramme (SVG-Primitive) mit Leerfeldern, die der Prüfling
 * per Dropdown oder Texteingabe vervollständigt.
 */
import type { DiagramElement, Question } from '../../../shared/types.js';

/* ---------- Zeichenhelfer ---------- */
const box = (x: number, y: number, w: number, h: number, label?: string, o: { fill?: string; bold?: boolean; size?: number; dashed?: boolean; mono?: boolean } = {}): DiagramElement[] => {
  const els: DiagramElement[] = [{ kind: 'rect', x, y, w, h, fill: o.fill ?? '#ffffff', dashed: o.dashed }];
  if (label) els.push({ kind: 'text', x: x + w / 2, y: y + h / 2, text: label, anchor: 'middle', bold: o.bold, size: o.size ?? 13, mono: o.mono });
  return els;
};
const txt = (x: number, y: number, text: string, o: { bold?: boolean; size?: number; anchor?: 'start' | 'middle' | 'end'; color?: string; mono?: boolean } = {}): DiagramElement => ({
  kind: 'text',
  x,
  y,
  text,
  ...o,
});
const line = (x1: number, y1: number, x2: number, y2: number, o: { arrow?: boolean; dashed?: boolean; arrowStart?: boolean; stroke?: string } = {}): DiagramElement => ({ kind: 'line', x1, y1, x2, y2, ...o });

/* ---------- Tabellen-Helfer ---------- */
function table(x: number, y: number, colWidths: number[], rowH: number, rows: (string | null)[][], o: { headerFill?: string; mono?: boolean } = {}): DiagramElement[] {
  const els: DiagramElement[] = [];
  let cy = y;
  for (const [ri, row] of rows.entries()) {
    let cx = x;
    for (const [ci, cell] of row.entries()) {
      const w = colWidths[ci];
      els.push({ kind: 'rect', x: cx, y: cy, w, h: rowH, fill: ri === 0 ? o.headerFill ?? '#eef2f7' : '#ffffff', rx: 0 });
      if (cell) els.push(txt(cx + 8, cy + rowH / 2, cell, { bold: ri === 0, size: 12.5, mono: o.mono && ri > 0 }));
      cx += w;
    }
    cy += rowH;
  }
  return els;
}

export const questions: Question[] = [
  /* =============== HS2: Arbeitsplatz =============== */
  {
    id: 'ap-if-001',
    section: 'arbeitsplatz',
    topic: 'hardware',
    type: 'image_fill',
    title: 'Blockschaltbild eines PC-Arbeitsplatzes',
    scenario: 'Für die Schulung neuer Auszubildender der Möbelwerkstatt Holzart GmbH dokumentieren Sie den Aufbau eines Büro-PCs.',
    text: 'Ordnen Sie den vier leeren Feldern die richtige Komponente zu. Die Beschriftungen der Verbindungen geben Hinweise auf die Schnittstelle.',
    points: 4,
    difficulty: 1,
    diagram: {
      width: 640,
      height: 360,
      elements: [
        ...box(220, 140, 200, 80, 'Mainboard / Chipsatz', { fill: '#eef2f7', bold: true }),
        ...box(260, 20, 120, 50),
        line(320, 70, 320, 140),
        txt(328, 105, 'CPU-Sockel', { size: 11, color: '#5f6b7c' }),
        ...box(30, 155, 150, 50),
        line(180, 180, 220, 180),
        txt(200, 168, 'DDR5', { size: 11, color: '#5f6b7c', anchor: 'middle' }),
        ...box(460, 155, 150, 50),
        line(420, 180, 460, 180),
        txt(440, 168, 'PCIe x16', { size: 11, color: '#5f6b7c', anchor: 'middle' }),
        ...box(260, 280, 120, 50),
        line(320, 220, 320, 280),
        txt(328, 250, 'M.2 / NVMe (PCIe x4)', { size: 11, color: '#5f6b7c' }),
        ...box(30, 280, 150, 50, 'Netzteil (PSU)'),
        line(105, 280, 105, 205, { dashed: true }),
        line(105, 205, 220, 205, { dashed: true }),
        txt(120, 240, '12 V / 5 V / 3,3 V', { size: 11, color: '#5f6b7c' }),
        ...box(460, 280, 150, 50, 'Tastatur, Maus, Webcam'),
        line(535, 280, 535, 205),
        line(535, 205, 420, 205),
        txt(543, 245, 'USB 3.2', { size: 11, color: '#5f6b7c' }),
      ],
    },
    blanks: [
      { id: 'b1', x: 264, y: 32, w: 112, h: 26, accepted: ['Prozessor (CPU)'], options: ['Prozessor (CPU)', 'Arbeitsspeicher (RAM)', 'Grafikkarte (GPU)', 'Massenspeicher (SSD)', 'Netzwerkkarte (NIC)', 'Soundkarte'] },
      { id: 'b2', x: 34, y: 167, w: 142, h: 26, accepted: ['Arbeitsspeicher (RAM)'], options: ['Prozessor (CPU)', 'Arbeitsspeicher (RAM)', 'Grafikkarte (GPU)', 'Massenspeicher (SSD)', 'Netzwerkkarte (NIC)', 'Soundkarte'] },
      { id: 'b3', x: 464, y: 167, w: 142, h: 26, accepted: ['Grafikkarte (GPU)'], options: ['Prozessor (CPU)', 'Arbeitsspeicher (RAM)', 'Grafikkarte (GPU)', 'Massenspeicher (SSD)', 'Netzwerkkarte (NIC)', 'Soundkarte'] },
      { id: 'b4', x: 264, y: 292, w: 112, h: 26, accepted: ['Massenspeicher (SSD)'], options: ['Prozessor (CPU)', 'Arbeitsspeicher (RAM)', 'Grafikkarte (GPU)', 'Massenspeicher (SSD)', 'Netzwerkkarte (NIC)', 'Soundkarte'] },
    ],
    explanation: 'Die CPU sitzt im Sockel, RAM-Module im DDR5-Speicherbus, die Grafikkarte im PCIe-x16-Steckplatz und eine NVMe-SSD im M.2-Slot (PCIe x4). Das Netzteil versorgt alle Komponenten mit Gleichspannung.',
  },
  {
    id: 'ap-if-002',
    section: 'arbeitsplatz',
    topic: 'virtualisierung',
    type: 'image_fill',
    title: 'Hypervisor-Typen',
    scenario: 'Die Ingenieurgesellschaft Brückner & Söhne möchte ihre alten Server konsolidieren. Sie erklären der Geschäftsleitung die beiden Virtualisierungsarchitekturen.',
    text: 'Vervollständigen Sie die Schichtendarstellung der beiden Hypervisor-Typen und geben Sie ein Beispielprodukt für den Typ-1-Hypervisor an.',
    points: 4,
    difficulty: 2,
    diagram: {
      width: 640,
      height: 320,
      elements: [
        txt(160, 22, 'Typ 1 („bare metal“)', { bold: true, anchor: 'middle', size: 14 }),
        txt(480, 22, 'Typ 2 („hosted“)', { bold: true, anchor: 'middle', size: 14 }),
        // Typ 1 Stack
        ...box(40, 40, 115, 44, 'Gast-OS (VM 1)'),
        ...box(165, 40, 115, 44, 'Gast-OS (VM 2)'),
        ...box(40, 90, 240, 44, undefined, { fill: '#fffdf3' }),
        ...box(40, 140, 240, 44, 'Hardware', { fill: '#eef2f7', bold: true }),
        txt(40, 215, 'Beispielprodukt:', { size: 12 }),
        // Typ 2 Stack
        ...box(360, 40, 115, 44, 'Gast-OS (VM 1)'),
        ...box(485, 40, 115, 44, 'Gast-OS (VM 2)'),
        ...box(360, 90, 240, 44, undefined, { fill: '#fffdf3' }),
        ...box(360, 140, 240, 44, undefined, { fill: '#fffdf3' }),
        ...box(360, 190, 240, 44, 'Hardware', { fill: '#eef2f7', bold: true }),
        txt(360, 260, 'Beispiel: Oracle VirtualBox, VMware Workstation', { size: 12, color: '#5f6b7c' }),
      ],
    },
    blanks: [
      { id: 'b1', x: 60, y: 99, w: 200, h: 26, accepted: ['Hypervisor'], options: ['Hypervisor', 'Host-Betriebssystem', 'Container-Engine', 'BIOS/UEFI'] },
      { id: 'b2', x: 380, y: 99, w: 200, h: 26, accepted: ['Hypervisor'], options: ['Hypervisor', 'Host-Betriebssystem', 'Container-Engine', 'BIOS/UEFI'] },
      { id: 'b3', x: 380, y: 149, w: 200, h: 26, accepted: ['Host-Betriebssystem'], options: ['Hypervisor', 'Host-Betriebssystem', 'Container-Engine', 'BIOS/UEFI'] },
      { id: 'b4', x: 40, y: 226, w: 240, h: 26, accepted: ['VMware ESXi / Microsoft Hyper-V'], options: ['VMware ESXi / Microsoft Hyper-V', 'Oracle VirtualBox', 'Microsoft Office 365', 'Docker Desktop'] },
    ],
    explanation: 'Ein Typ-1-Hypervisor (z. B. VMware ESXi, Hyper-V, Proxmox) läuft direkt auf der Hardware; ein Typ-2-Hypervisor (VirtualBox, VMware Workstation) ist eine Anwendung auf einem Host-Betriebssystem.',
  },
  {
    id: 'ap-if-003',
    section: 'arbeitsplatz',
    topic: 'cloud',
    type: 'image_fill',
    title: 'Verantwortlichkeiten bei Cloud-Servicemodellen',
    scenario: 'Der Online-Versandhändler Nordlicht Trading prüft, welche Aufgaben bei IaaS, PaaS und SaaS beim Anbieter und welche beim Kunden liegen.',
    text: 'Vervollständigen Sie die Verantwortungsmatrix: Wer verwaltet die jeweilige Ebene – Kunde oder Anbieter?',
    points: 4,
    difficulty: 2,
    diagram: {
      width: 640,
      height: 300,
      elements: [
        ...table(
          20,
          20,
          [190, 105, 105, 105, 105],
          32,
          [
            ['Ebene', 'On-Premises', 'IaaS', 'PaaS', 'SaaS'],
            ['Anwendung', 'Kunde', 'Kunde', null, 'Anbieter'],
            ['Daten', 'Kunde', 'Kunde', 'Kunde', 'Kunde'],
            ['Laufzeitumgebung', 'Kunde', 'Kunde', null, 'Anbieter'],
            ['Betriebssystem', 'Kunde', null, 'Anbieter', 'Anbieter'],
            ['Virtualisierung', 'Kunde', null, 'Anbieter', 'Anbieter'],
            ['Server / Speicher', 'Kunde', 'Anbieter', 'Anbieter', 'Anbieter'],
            ['Netzwerk', 'Kunde', 'Anbieter', 'Anbieter', 'Anbieter'],
          ],
        ),
      ],
    },
    blanks: [
      { id: 'b1', x: 424, y: 56, w: 97, h: 24, accepted: ['Kunde'], options: ['Kunde', 'Anbieter'] },
      { id: 'b2', x: 424, y: 120, w: 97, h: 24, accepted: ['Anbieter'], options: ['Kunde', 'Anbieter'] },
      { id: 'b3', x: 319, y: 152, w: 97, h: 24, accepted: ['Kunde'], options: ['Kunde', 'Anbieter'] },
      { id: 'b4', x: 319, y: 184, w: 97, h: 24, accepted: ['Anbieter'], options: ['Kunde', 'Anbieter'] },
    ],
    explanation: 'Bei IaaS mietet der Kunde virtuelle Infrastruktur und verwaltet ab dem Betriebssystem selbst. Bei PaaS stellt der Anbieter zusätzlich Betriebssystem und Laufzeitumgebung; der Kunde bringt nur Anwendung und Daten ein. Bei SaaS liegt fast alles beim Anbieter – die Verantwortung für die Daten (Inhalte, Datenschutz) bleibt aber beim Kunden.',
  },

  /* =============== HS3: Sicherheit =============== */
  {
    id: 'si-if-001',
    section: 'sicherheit',
    topic: 'verschluesselung',
    type: 'image_fill',
    title: 'Asymmetrische Verschlüsselung und digitale Signatur',
    scenario: 'Die Rechtsanwältin Alice sendet dem Mandanten Bob ein vertrauliches, signiertes Dokument per E-Mail. Beide besitzen ein Schlüsselpaar.',
    text: 'Vervollständigen Sie das Ablaufdiagramm: Welcher Schlüssel wird an welcher Stelle verwendet?',
    points: 4,
    difficulty: 2,
    diagram: {
      width: 700,
      height: 300,
      elements: [
        txt(20, 22, 'Vertraulichkeit (Verschlüsselung)', { bold: true, size: 14 }),
        ...box(20, 40, 100, 70, 'Alice\n(Sender)'),
        txt(70, 66, 'Alice', { anchor: 'middle', bold: true }),
        txt(70, 86, '(Sender)', { anchor: 'middle', size: 11 }),
        line(120, 75, 160, 75, { arrow: true }),
        ...box(160, 40, 170, 70, undefined, { fill: '#fffdf3' }),
        txt(245, 56, 'verschlüsseln mit', { anchor: 'middle', size: 12 }),
        line(330, 75, 370, 75, { arrow: true }),
        ...box(370, 45, 90, 60, 'Chiffrat', { fill: '#eef2f7' }),
        line(460, 75, 500, 75, { arrow: true }),
        ...box(500, 40, 170, 70, undefined, { fill: '#fffdf3' }),
        txt(585, 56, 'entschlüsseln mit', { anchor: 'middle', size: 12 }),
        txt(585, 128, '→ Bob (Empfänger)', { anchor: 'middle', size: 12, color: '#5f6b7c' }),

        txt(20, 172, 'Authentizität / Integrität (Signatur)', { bold: true, size: 14 }),
        ...box(20, 190, 100, 70),
        txt(70, 216, 'Alice', { anchor: 'middle', bold: true }),
        txt(70, 236, '(Sender)', { anchor: 'middle', size: 11 }),
        line(120, 225, 160, 225, { arrow: true }),
        ...box(160, 190, 170, 70, undefined, { fill: '#fffdf3' }),
        txt(245, 206, 'Hashwert signieren mit', { anchor: 'middle', size: 12 }),
        line(330, 225, 370, 225, { arrow: true }),
        ...box(370, 195, 90, 60, 'Signatur', { fill: '#eef2f7' }),
        line(460, 225, 500, 225, { arrow: true }),
        ...box(500, 190, 170, 70, undefined, { fill: '#fffdf3' }),
        txt(585, 206, 'Signatur prüfen mit', { anchor: 'middle', size: 12 }),
        txt(585, 278, '→ Bob (Empfänger)', { anchor: 'middle', size: 12, color: '#5f6b7c' }),
      ],
    },
    blanks: [
      { id: 'b1', x: 168, y: 70, w: 154, h: 26, accepted: ['öffentlicher Schlüssel von Bob'], options: ['öffentlicher Schlüssel von Bob', 'privater Schlüssel von Bob', 'öffentlicher Schlüssel von Alice', 'privater Schlüssel von Alice', 'gemeinsames Passwort'] },
      { id: 'b2', x: 508, y: 70, w: 154, h: 26, accepted: ['privater Schlüssel von Bob'], options: ['öffentlicher Schlüssel von Bob', 'privater Schlüssel von Bob', 'öffentlicher Schlüssel von Alice', 'privater Schlüssel von Alice', 'gemeinsames Passwort'] },
      { id: 'b3', x: 168, y: 220, w: 154, h: 26, accepted: ['privater Schlüssel von Alice'], options: ['öffentlicher Schlüssel von Bob', 'privater Schlüssel von Bob', 'öffentlicher Schlüssel von Alice', 'privater Schlüssel von Alice', 'gemeinsames Passwort'] },
      { id: 'b4', x: 508, y: 220, w: 154, h: 26, accepted: ['öffentlicher Schlüssel von Alice'], options: ['öffentlicher Schlüssel von Bob', 'privater Schlüssel von Bob', 'öffentlicher Schlüssel von Alice', 'privater Schlüssel von Alice', 'gemeinsames Passwort'] },
    ],
    explanation: 'Verschlüsselt wird stets mit dem öffentlichen Schlüssel des Empfängers, entschlüsselt mit dessen privatem Schlüssel. Signiert wird mit dem privaten Schlüssel des Senders; jeder kann die Signatur mit dem öffentlichen Schlüssel des Senders prüfen.',
  },
  {
    id: 'si-if-002',
    section: 'sicherheit',
    topic: 'backup',
    type: 'image_fill',
    title: 'Sicherungsstrategien erkennen',
    scenario: 'Die Werbeagentur Farbklang sichert ihren Dateiserver täglich um 22:00 Uhr. Sonntags wird eine Vollsicherung erstellt. Das Diagramm zeigt das Datenvolumen der täglichen Sicherungen für zwei mögliche Strategien.',
    text: 'a) Benennen Sie die beiden Strategien (Felder 1 und 2).\nb) Am Donnerstag um 14:00 Uhr fällt die Festplatte aus. Wie viele Sicherungssätze müssen für die Wiederherstellung bei Strategie 1 (Feld 3) bzw. Strategie 2 (Feld 4) eingespielt werden? Geben Sie jeweils eine Zahl ein.',
    points: 4,
    difficulty: 2,
    diagram: {
      width: 660,
      height: 340,
      elements: [
        txt(20, 22, 'Strategie 1:', { bold: true, size: 13 }),
        txt(20, 182, 'Strategie 2:', { bold: true, size: 13 }),
        // Achsen
        line(60, 150, 640, 150),
        line(60, 310, 640, 310),
        // Balken Strategie 1 (Vollsicherung + wachsend)
        ...['So', 'Mo', 'Di', 'Mi', 'Do', 'Fr', 'Sa'].flatMap((d, i) => {
          const h1 = i === 0 ? 100 : 12 + i * 12;
          const h2 = i === 0 ? 100 : 12;
          const x = 80 + i * 80;
          return [
            { kind: 'rect', x, y: 150 - h1, w: 44, h: h1, fill: i === 0 ? '#1f4fbf' : '#8fa8e8' } as DiagramElement,
            txt(x + 22, 163, d, { anchor: 'middle', size: 12 }),
            { kind: 'rect', x, y: 310 - h2, w: 44, h: h2, fill: i === 0 ? '#1f4fbf' : '#8fa8e8' } as DiagramElement,
            txt(x + 22, 323, d, { anchor: 'middle', size: 12 }),
          ];
        }),
        txt(102, 40, 'Voll', { anchor: 'middle', size: 11, color: '#fff' }),
        txt(102, 200, 'Voll', { anchor: 'middle', size: 11, color: '#fff' }),
        txt(400, 40, 'Datenvolumen je Sicherung', { anchor: 'middle', size: 11, color: '#5f6b7c' }),
      ],
    },
    blanks: [
      { id: 'b1', x: 110, y: 8, w: 200, h: 26, accepted: ['differenzielle Sicherung'], options: ['Vollsicherung', 'differenzielle Sicherung', 'inkrementelle Sicherung', 'Spiegelung (Mirroring)'] },
      { id: 'b2', x: 110, y: 168, w: 200, h: 26, accepted: ['inkrementelle Sicherung'], options: ['Vollsicherung', 'differenzielle Sicherung', 'inkrementelle Sicherung', 'Spiegelung (Mirroring)'] },
      { id: 'b3', x: 480, y: 60, w: 160, h: 26, accepted: ['2', '2 Sicherungen', 'zwei'], hint: 'Anzahl Sätze (Strategie 1)' },
      { id: 'b4', x: 480, y: 220, w: 160, h: 26, accepted: ['4', '4 Sicherungen', 'vier'], hint: 'Anzahl Sätze (Strategie 2)' },
    ],
    explanation: 'Differenzielle Sicherungen wachsen von Tag zu Tag, weil immer alle Änderungen seit der letzten Vollsicherung gesichert werden; zur Wiederherstellung genügen Vollsicherung + letzte differenzielle Sicherung (Mittwoch) = 2 Sätze. Inkrementelle Sicherungen sind klein, benötigen aber die komplette Kette: Voll + Mo + Di + Mi = 4 Sätze.',
  },
  {
    id: 'si-if-003',
    section: 'sicherheit',
    topic: 'authentifizierung',
    type: 'image_fill',
    title: 'Authentifizierungsfaktoren und Autorisierung',
    scenario: 'Die Spedition Wagner & Co. führt für den Zugriff auf das Speditionsportal eine Mehr-Faktor-Authentifizierung ein. Sie erstellen eine Übersicht für die Mitarbeitenden.',
    text: 'Ordnen Sie den drei Faktor-Kategorien ihre Bezeichnung zu (Felder 1–3) und vervollständigen Sie den Anmeldeablauf (Feld 4).',
    points: 4,
    difficulty: 2,
    diagram: {
      width: 660,
      height: 320,
      elements: [
        txt(20, 20, 'Faktor-Kategorien der Authentifizierung', { bold: true, size: 14 }),
        ...box(20, 40, 200, 120, undefined, { fill: '#ffffff' }),
        ...box(230, 40, 200, 120, undefined, { fill: '#ffffff' }),
        ...box(440, 40, 200, 120, undefined, { fill: '#ffffff' }),
        txt(30, 100, 'Beispiele:', { size: 11, color: '#5f6b7c' }),
        txt(30, 120, '• Passwort, PIN', { size: 12 }),
        txt(30, 140, '• Antwort auf Sicherheitsfrage', { size: 12 }),
        txt(240, 100, 'Beispiele:', { size: 11, color: '#5f6b7c' }),
        txt(240, 120, '• Smartphone-App (TOTP-Code)', { size: 12 }),
        txt(240, 140, '• Chipkarte, Hardware-Token', { size: 12 }),
        txt(450, 100, 'Beispiele:', { size: 11, color: '#5f6b7c' }),
        txt(450, 120, '• Fingerabdruck', { size: 12 }),
        txt(450, 140, '• Gesichtserkennung', { size: 12 }),
        txt(20, 200, 'Anmeldeablauf', { bold: true, size: 14 }),
        ...box(20, 220, 130, 60, undefined),
        txt(85, 242, 'Anmeldung', { anchor: 'middle', bold: true, size: 12 }),
        txt(85, 262, 'Benutzer + Faktoren', { anchor: 'middle', size: 10.5 }),
        line(150, 250, 190, 250, { arrow: true }),
        ...box(190, 220, 170, 60, undefined),
        txt(275, 242, 'Authentifizierung', { anchor: 'middle', bold: true, size: 12 }),
        txt(275, 262, 'Identität wird geprüft', { anchor: 'middle', size: 10.5 }),
        line(360, 250, 400, 250, { arrow: true }),
        ...box(400, 220, 170, 60, undefined, { fill: '#fffdf3' }),
        txt(485, 265, 'Rechte werden zugewiesen', { anchor: 'middle', size: 10.5 }),
        line(570, 250, 610, 250, { arrow: true }),
        txt(625, 250, 'Zugriff', { size: 12, bold: true }),
      ],
    },
    blanks: [
      { id: 'b1', x: 30, y: 52, w: 180, h: 26, accepted: ['Wissen'], options: ['Wissen', 'Besitz', 'Inhärenz (Biometrie)', 'Standort', 'Verhalten'] },
      { id: 'b2', x: 240, y: 52, w: 180, h: 26, accepted: ['Besitz'], options: ['Wissen', 'Besitz', 'Inhärenz (Biometrie)', 'Standort', 'Verhalten'] },
      { id: 'b3', x: 450, y: 52, w: 180, h: 26, accepted: ['Inhärenz (Biometrie)'], options: ['Wissen', 'Besitz', 'Inhärenz (Biometrie)', 'Standort', 'Verhalten'] },
      { id: 'b4', x: 410, y: 228, w: 150, h: 26, accepted: ['Autorisierung'], options: ['Autorisierung', 'Authentifizierung', 'Auditierung', 'Anonymisierung', 'Identifikation'] },
    ],
    explanation: 'Echte Mehr-Faktor-Authentifizierung kombiniert Faktoren aus verschiedenen Kategorien: Wissen (Passwort), Besitz (Token, App) und Inhärenz (biometrische Merkmale). Nach der Authentifizierung (Wer bist du?) folgt die Autorisierung (Was darfst du?).',
  },

  /* =============== HS4: Netzwerk =============== */
  {
    id: 'nw-if-001',
    section: 'netzwerk',
    topic: 'osi',
    type: 'image_fill',
    title: 'OSI-Referenzmodell vervollständigen',
    scenario: 'Für die Fehleranalyse im Netz der Grundschule Am Lindenhof dokumentieren Sie, auf welcher Schicht des OSI-Modells die einzelnen Komponenten und Protokolle arbeiten.',
    text: 'Ergänzen Sie die fehlenden Schichtnamen (Felder 1–4).',
    points: 4,
    difficulty: 1,
    diagram: {
      width: 640,
      height: 300,
      elements: [
        ...table(
          20,
          16,
          [50, 190, 250, 110],
          32,
          [
            ['Nr.', 'Schicht', 'Beispiele', 'Dateneinheit'],
            ['7', null, 'HTTP, SMTP, DNS, FTP', 'Daten'],
            ['6', 'Darstellungsschicht', 'TLS/SSL, Zeichensätze, Kompression', 'Daten'],
            ['5', 'Sitzungsschicht', 'NetBIOS, RPC, Sitzungsaufbau', 'Daten'],
            ['4', null, 'TCP, UDP, Ports', 'Segment'],
            ['3', null, 'IP, ICMP, Router', 'Paket'],
            ['2', 'Sicherungsschicht', 'Ethernet, MAC-Adressen, Switch', 'Frame'],
            ['1', null, 'Kabel, Stecker, Hub, Signale', 'Bit'],
          ],
        ),
      ],
    },
    blanks: [
      { id: 'b1', x: 74, y: 52, w: 182, h: 24, accepted: ['Anwendungsschicht'], options: ['Anwendungsschicht', 'Darstellungsschicht', 'Sitzungsschicht', 'Transportschicht', 'Vermittlungsschicht', 'Sicherungsschicht', 'Bitübertragungsschicht'] },
      { id: 'b2', x: 74, y: 148, w: 182, h: 24, accepted: ['Transportschicht'], options: ['Anwendungsschicht', 'Darstellungsschicht', 'Sitzungsschicht', 'Transportschicht', 'Vermittlungsschicht', 'Sicherungsschicht', 'Bitübertragungsschicht'] },
      { id: 'b3', x: 74, y: 180, w: 182, h: 24, accepted: ['Vermittlungsschicht'], options: ['Anwendungsschicht', 'Darstellungsschicht', 'Sitzungsschicht', 'Transportschicht', 'Vermittlungsschicht', 'Sicherungsschicht', 'Bitübertragungsschicht'] },
      { id: 'b4', x: 74, y: 244, w: 182, h: 24, accepted: ['Bitübertragungsschicht'], options: ['Anwendungsschicht', 'Darstellungsschicht', 'Sitzungsschicht', 'Transportschicht', 'Vermittlungsschicht', 'Sicherungsschicht', 'Bitübertragungsschicht'] },
    ],
    explanation: 'Merkhilfe von unten: „Bitte Sichere Vermittlung Transportiert Sitzung Dar Anwendung“ – Bitübertragung, Sicherung, Vermittlung, Transport, Sitzung, Darstellung, Anwendung.',
  },
  {
    id: 'nw-if-002',
    section: 'netzwerk',
    topic: 'dhcp',
    type: 'image_fill',
    title: 'DHCP-Ablauf (DORA)',
    scenario: 'Ein neues Notebook der Physiotherapie-Praxis Bewegt wird ins Netz eingebunden und bezieht automatisch seine IP-Konfiguration.',
    text: 'Vervollständigen Sie das Sequenzdiagramm der DHCP-Adressvergabe mit den vier Nachrichtentypen in der richtigen Reihenfolge.',
    points: 4,
    difficulty: 1,
    diagram: {
      width: 620,
      height: 320,
      elements: [
        ...box(60, 15, 120, 36, 'DHCP-Client', { fill: '#eef2f7', bold: true }),
        ...box(440, 15, 120, 36, 'DHCP-Server', { fill: '#eef2f7', bold: true }),
        line(120, 51, 120, 300, { dashed: true }),
        line(500, 51, 500, 300, { dashed: true }),
        line(120, 90, 500, 90, { arrow: true }),
        txt(140, 78, '1.', { bold: true, size: 12 }),
        txt(480, 104, 'Broadcast (Ziel 255.255.255.255)', { size: 10.5, anchor: 'end', color: '#5f6b7c' }),
        line(500, 150, 120, 150, { arrow: true }),
        txt(140, 138, '2.', { bold: true, size: 12 }),
        txt(480, 164, 'Angebot einer Adresse aus dem Pool', { size: 10.5, anchor: 'end', color: '#5f6b7c' }),
        line(120, 210, 500, 210, { arrow: true }),
        txt(140, 198, '3.', { bold: true, size: 12 }),
        txt(480, 224, 'Client nimmt das Angebot an', { size: 10.5, anchor: 'end', color: '#5f6b7c' }),
        line(500, 270, 120, 270, { arrow: true }),
        txt(140, 258, '4.', { bold: true, size: 12 }),
        txt(480, 284, 'Bestätigung, Lease-Zeit beginnt', { size: 10.5, anchor: 'end', color: '#5f6b7c' }),
      ],
    },
    blanks: [
      { id: 'b1', x: 220, y: 62, w: 180, h: 26, accepted: ['DHCP Discover'], options: ['DHCP Discover', 'DHCP Offer', 'DHCP Request', 'DHCP Acknowledge', 'DHCP Release', 'DHCP Decline'] },
      { id: 'b2', x: 220, y: 122, w: 180, h: 26, accepted: ['DHCP Offer'], options: ['DHCP Discover', 'DHCP Offer', 'DHCP Request', 'DHCP Acknowledge', 'DHCP Release', 'DHCP Decline'] },
      { id: 'b3', x: 220, y: 182, w: 180, h: 26, accepted: ['DHCP Request'], options: ['DHCP Discover', 'DHCP Offer', 'DHCP Request', 'DHCP Acknowledge', 'DHCP Release', 'DHCP Decline'] },
      { id: 'b4', x: 220, y: 242, w: 180, h: 26, accepted: ['DHCP Acknowledge'], options: ['DHCP Discover', 'DHCP Offer', 'DHCP Request', 'DHCP Acknowledge', 'DHCP Release', 'DHCP Decline'] },
    ],
    explanation: 'DORA: Discover (Client sucht per Broadcast einen Server), Offer (Server bietet Adresse an), Request (Client fordert die angebotene Adresse an), Acknowledge (Server bestätigt und übermittelt Lease-Zeit, Gateway, DNS).',
  },
  {
    id: 'nw-if-003',
    section: 'netzwerk',
    topic: 'subnetting',
    type: 'image_fill',
    title: 'Subnetztabelle vervollständigen',
    scenario: 'Die Berufsschule Ostpark teilt ihr Netz 192.168.10.0/24 in vier gleich große Subnetze für Verwaltung, Lehrkräfte, Schüler und Technik auf.',
    text: 'Vervollständigen Sie die Subnetztabelle (Subnetzmaske 255.255.255.192, /26). Geben Sie vollständige IPv4-Adressen ein.',
    points: 4,
    difficulty: 2,
    diagram: {
      width: 660,
      height: 220,
      elements: [
        ...table(
          20,
          16,
          [110, 130, 130, 130, 130],
          34,
          [
            ['Subnetz', 'Netzadresse', 'Erster Host', 'Letzter Host', 'Broadcast'],
            ['1 Verwaltung', '192.168.10.0', '192.168.10.1', '192.168.10.62', '192.168.10.63'],
            ['2 Lehrkräfte', null, '192.168.10.65', '192.168.10.126', null],
            ['3 Schüler', '192.168.10.128', null, null, '192.168.10.191'],
            ['4 Technik', null, '192.168.10.193', '192.168.10.254', '192.168.10.255'],
          ],
          { mono: true },
        ),
      ],
    },
    blanks: [
      { id: 'b1', x: 133, y: 89, w: 124, h: 24, accepted: ['192.168.10.64', '.64', '64'], hint: 'Netzadresse' },
      { id: 'b2', x: 523, y: 89, w: 124, h: 24, accepted: ['192.168.10.127', '.127', '127'], hint: 'Broadcast' },
      { id: 'b3', x: 263, y: 123, w: 124, h: 24, accepted: ['192.168.10.129', '.129', '129'], hint: 'Erster Host' },
      { id: 'b4', x: 393, y: 123, w: 124, h: 24, accepted: ['192.168.10.190', '.190', '190'], hint: 'Letzter Host' },
      { id: 'b5', x: 133, y: 157, w: 124, h: 24, accepted: ['192.168.10.192', '.192', '192'], hint: 'Netzadresse' },
    ],
    explanation: 'Bei /26 bleiben 6 Hostbits: Blockgröße 64. Die Subnetze beginnen bei .0, .64, .128 und .192; der Broadcast ist jeweils die letzte Adresse des Blocks (.63, .127, .191, .255), die Hosts liegen dazwischen.',
  },

  /* =============== HS5: Entwicklung =============== */
  {
    id: 'ew-if-001',
    section: 'entwicklung',
    topic: 'aktivitaetsdiagramm',
    type: 'image_fill',
    title: 'UML-Aktivitätsdiagramm vervollständigen',
    scenario: 'Für die Lagerverwaltung der Gartencenter Grünwald GmbH soll ein Algorithmus die Summe aller **geraden** Zahlen von 1 bis n berechnen (z. B. n = 6 → 2 + 4 + 6 = 12). Der Ablauf ist als UML-Aktivitätsdiagramm modelliert.',
    text: 'Vervollständigen Sie das Aktivitätsdiagramm: Füllen Sie die Aktionen (Felder 1, 4 und 5) und die Bedingungen (Guards) an den Entscheidungsknoten (Felder 2 und 3).',
    points: 5,
    difficulty: 2,
    diagram: {
      width: 540,
      height: 450,
      elements: [
        { kind: 'ellipse', cx: 260, cy: 24, rx: 9, ry: 9, fill: '#2d3a55' },
        line(260, 33, 260, 50, { arrow: true }),
        { kind: 'rect', x: 180, y: 50, w: 160, h: 34, rx: 14 },
        txt(260, 67, 'Eingabe: n', { anchor: 'middle', mono: true }),
        line(260, 84, 260, 104, { arrow: true }),
        { kind: 'rect', x: 180, y: 104, w: 160, h: 34, rx: 14, fill: '#fffdf3' },
        line(260, 138, 260, 156, { arrow: true }),
        { kind: 'path', d: 'M 260 156 L 300 176 L 260 196 L 220 176 Z', fill: '#ffffff' },
        line(300, 176, 380, 176, { arrow: true }),
        txt(340, 166, '[sonst]', { anchor: 'middle', size: 11, mono: true }),
        { kind: 'rect', x: 380, y: 159, w: 130, h: 34, rx: 14 },
        txt(445, 176, 'Ausgabe: summe', { anchor: 'middle', mono: true, size: 12 }),
        line(445, 193, 445, 222, { arrow: true }),
        { kind: 'ellipse', cx: 445, cy: 236, rx: 11, ry: 11, fill: '#ffffff' },
        { kind: 'ellipse', cx: 445, cy: 236, rx: 7, ry: 7, fill: '#2d3a55' },
        line(260, 196, 260, 230, { arrow: true }),
        { kind: 'path', d: 'M 260 230 L 300 250 L 260 270 L 220 250 Z', fill: '#ffffff' },
        line(220, 250, 140, 250),
        line(140, 250, 140, 366),
        line(140, 366, 246, 366, { arrow: true }),
        txt(150, 240, '[sonst]', { size: 11, mono: true }),
        line(260, 270, 260, 300, { arrow: true }),
        { kind: 'rect', x: 180, y: 300, w: 160, h: 34, rx: 14, fill: '#fffdf3' },
        line(260, 334, 260, 352, { arrow: true }),
        { kind: 'path', d: 'M 260 352 L 274 366 L 260 380 L 246 366 Z', fill: '#ffffff' },
        line(260, 380, 260, 396, { arrow: true }),
        { kind: 'rect', x: 180, y: 396, w: 160, h: 34, rx: 14, fill: '#fffdf3' },
        line(180, 413, 100, 413),
        line(100, 413, 100, 176),
        line(100, 176, 220, 176, { arrow: true }),
      ],
    },
    blanks: [
      { id: 'b1', x: 186, y: 108, w: 148, h: 26, accepted: ['summe = 0; i = 1'], options: ['summe = 0; i = 1', 'summe = 1; i = 0', 'i = n', 'summe = n'] },
      { id: 'b2', x: 268, y: 200, w: 100, h: 24, accepted: ['[i <= n]'], options: ['[i <= n]', '[i < n]', '[i > n]', '[n = 0]'] },
      { id: 'b3', x: 268, y: 274, w: 120, h: 24, accepted: ['[i MOD 2 = 0]'], options: ['[i MOD 2 = 0]', '[i MOD 2 = 1]', '[i = 2]', '[summe > 0]'] },
      { id: 'b4', x: 186, y: 304, w: 148, h: 26, accepted: ['summe = summe + i'], options: ['summe = summe + i', 'summe = summe + 1', 'i = i + summe', 'summe = i'] },
      { id: 'b5', x: 186, y: 400, w: 148, h: 26, accepted: ['i = i + 1'], options: ['i = i + 1', 'i = i + 2', 'n = n − 1', 'i = 1'] },
    ],
    explanation: 'Nach der Initialisierung (summe = 0, i = 1) prüft der erste Entscheidungsknoten die Schleifenbedingung [i <= n]. Ist i gerade ([i MOD 2 = 0]), wird i aufaddiert; danach wird i in jedem Durchlauf um 1 erhöht. Im [sonst]-Fall des ersten Knotens wird die Summe ausgegeben und der Ablauf endet.',
  },
  {
    id: 'ew-if-002',
    section: 'entwicklung',
    topic: 'uml-klassendiagramm',
    type: 'image_fill',
    title: 'UML-Klassendiagramm vervollständigen',
    scenario: 'Für den Webshop der Buchhandlung Leseinsel modellieren Sie Kunden, Bestellungen und Bestellpositionen. Eine Bestellung existiert nicht ohne ihre Positionen; ein Kunde kann beliebig viele Bestellungen haben.',
    text: 'Ergänzen Sie die Sichtbarkeiten (Feld 1 und 2), die Multiplizitäten der Assoziation Kunde–Bestellung (Feld 3 und 4) und die Art der Beziehung zwischen Bestellung und Position (Feld 5).',
    points: 5,
    difficulty: 2,
    diagram: {
      width: 660,
      height: 320,
      elements: [
        // Kunde
        ...box(20, 30, 200, 30, 'Kunde', { fill: '#eef2f7', bold: true }),
        { kind: 'rect', x: 20, y: 60, w: 200, h: 70, fill: '#ffffff' },
        txt(60, 78, 'kundenNr: int', { mono: true, size: 12 }),
        txt(32, 100, '- name: String', { mono: true, size: 12 }),
        txt(32, 120, '- email: String', { mono: true, size: 12 }),
        { kind: 'rect', x: 20, y: 130, w: 200, h: 50, fill: '#ffffff' },
        txt(32, 150, '+ getName(): String', { mono: true, size: 12 }),
        txt(32, 170, '+ setEmail(e: String)', { mono: true, size: 12 }),
        // Bestellung
        ...box(300, 30, 220, 30, 'Bestellung', { fill: '#eef2f7', bold: true }),
        { kind: 'rect', x: 300, y: 60, w: 220, h: 50, fill: '#ffffff' },
        txt(312, 78, '- bestellNr: int', { mono: true, size: 12 }),
        txt(312, 98, '- datum: Date', { mono: true, size: 12 }),
        { kind: 'rect', x: 300, y: 110, w: 220, h: 50, fill: '#ffffff' },
        txt(340, 128, 'berechneSumme(): double', { mono: true, size: 12 }),
        txt(312, 148, '+ addPosition(p: Position)', { mono: true, size: 12 }),
        // Assoziation Kunde - Bestellung
        line(220, 95, 300, 95),
        txt(260, 82, 'erteilt', { size: 11, anchor: 'middle', color: '#5f6b7c' }),
        // Position
        ...box(300, 230, 220, 30, 'Position', { fill: '#eef2f7', bold: true }),
        { kind: 'rect', x: 300, y: 260, w: 220, h: 50, fill: '#ffffff' },
        txt(312, 278, '- menge: int', { mono: true, size: 12 }),
        txt(312, 298, '- einzelpreis: double', { mono: true, size: 12 }),
        // Komposition Bestellung -> Position
        line(410, 175, 410, 230),
        { kind: 'path', d: 'M 410 160 L 418 168 L 410 176 L 402 168 Z', fill: '#2d3a55' },
        txt(420, 190, '1', { size: 12, bold: true }),
        txt(420, 222, '1..*', { size: 12, bold: true }),
        txt(540, 200, 'Beziehungsart:', { size: 12 }),
      ],
    },
    blanks: [
      { id: 'b1', x: 30, y: 66, w: 28, h: 22, accepted: ['-'], options: ['+', '-', '#', '~'] },
      { id: 'b2', x: 310, y: 116, w: 28, h: 22, accepted: ['+'], options: ['+', '-', '#', '~'] },
      { id: 'b3', x: 222, y: 100, w: 36, h: 22, accepted: ['1'], options: ['1', '0..1', '*', '0..*', '1..*'] },
      { id: 'b4', x: 262, y: 100, w: 36, h: 22, accepted: ['0..*'], options: ['1', '0..1', '*', '0..*', '1..*'] },
      { id: 'b5', x: 540, y: 208, w: 110, h: 24, accepted: ['Komposition'], options: ['Komposition', 'Aggregation', 'Assoziation', 'Abhängigkeit'] },
    ],
    explanation: 'Attribute werden nach dem Prinzip der Kapselung privat (-) deklariert, öffentliche Methoden mit +. Ein Kunde erteilt 0..* Bestellungen, jede Bestellung gehört zu genau 1 Kunden. Die ausgefüllte Raute steht für Komposition: Positionen existieren nicht ohne ihre Bestellung.',
  },
  {
    id: 'ew-if-003',
    section: 'entwicklung',
    topic: 'er-modell',
    type: 'image_fill',
    title: 'ER-Diagramm vervollständigen',
    scenario: 'Für die Datenbank des Fahrradverleihs Radlerglück modellieren Sie: Ein Kunde erteilt beliebig viele Bestellungen, jede Bestellung gehört zu genau einem Kunden. Eine Bestellung enthält mehrere Artikel, ein Artikel kann in vielen Bestellungen vorkommen.',
    text: 'Ergänzen Sie die Kardinalitäten (Chen-Notation, Felder 1–4) und bestimmen Sie den Primärschlüssel der Entität Bestellung (Feld 5).',
    points: 5,
    difficulty: 2,
    diagram: {
      width: 680,
      height: 260,
      elements: [
        ...box(20, 80, 120, 50, 'Kunde', { bold: true }),
        { kind: 'path', d: 'M 260 80 L 320 105 L 260 130 L 200 105 Z', fill: '#eef2f7' },
        txt(260, 105, 'erteilt', { anchor: 'middle', size: 12 }),
        ...box(380, 80, 120, 50, 'Bestellung', { bold: true }),
        { kind: 'path', d: 'M 600 80 L 660 105 L 600 130 L 540 105 Z', fill: '#eef2f7' },
        txt(600, 105, 'enthält', { anchor: 'middle', size: 12 }),
        ...box(560, 170, 120, 50, 'Artikel', { bold: true }),
        line(140, 105, 200, 105),
        line(320, 105, 380, 105),
        line(500, 105, 540, 105),
        line(620, 130, 620, 170),
        // Attribute Bestellung
        { kind: 'ellipse', cx: 400, cy: 30, rx: 45, ry: 16, fill: '#ffffff' },
        txt(400, 30, 'BestellNr', { anchor: 'middle', size: 11 }),
        { kind: 'ellipse', cx: 500, cy: 30, rx: 40, ry: 16, fill: '#ffffff' },
        txt(500, 30, 'Datum', { anchor: 'middle', size: 11 }),
        line(400, 46, 420, 80),
        line(500, 46, 480, 80),
        { kind: 'ellipse', cx: 80, cy: 30, rx: 45, ry: 16, fill: '#ffffff' },
        txt(80, 30, 'KundenNr', { anchor: 'middle', size: 11 }),
        line(80, 46, 80, 80),
        txt(20, 200, 'Primärschlüssel von Bestellung:', { size: 12, bold: true }),
      ],
    },
    blanks: [
      { id: 'b1', x: 148, y: 78, w: 46, h: 22, accepted: ['1'], options: ['1', 'n', 'm', '0'] },
      { id: 'b2', x: 328, y: 78, w: 46, h: 22, accepted: ['n'], options: ['1', 'n', 'm', '0'] },
      { id: 'b3', x: 500, y: 78, w: 40, h: 22, accepted: ['n', 'm'], options: ['1', 'n', 'm', '0'] },
      { id: 'b4', x: 626, y: 138, w: 46, h: 22, accepted: ['m', 'n'], options: ['1', 'n', 'm', '0'] },
      { id: 'b5', x: 250, y: 188, w: 140, h: 24, accepted: ['BestellNr'], options: ['BestellNr', 'Datum', 'KundenNr', 'Artikelname'] },
    ],
    explanation: 'Kunde–Bestellung ist eine 1:n-Beziehung (ein Kunde, viele Bestellungen). Bestellung–Artikel ist n:m und wird in der relationalen Umsetzung über eine Zwischentabelle (Bestellposition) aufgelöst. Der Primärschlüssel muss eindeutig sein: BestellNr.',
  },
  {
    id: 'ew-if-004',
    section: 'entwicklung',
    topic: 'bpmn',
    type: 'image_fill',
    title: 'BPMN-Prozessdiagramm: Elemente benennen',
    scenario: 'Der Bestellprozess des Online-Shops Nordlicht Trading wurde in BPMN (Business Process Model and Notation) modelliert. Sie sollen die Notationselemente für eine Schulung beschriften.',
    text: 'Benennen Sie die mit A bis E gekennzeichneten BPMN-Elemente (Felder 1–5).',
    points: 5,
    difficulty: 2,
    diagram: {
      width: 700,
      height: 330,
      elements: [
        { kind: 'ellipse', cx: 40, cy: 90, rx: 16, ry: 16, fill: '#ffffff' },
        txt(40, 122, 'A', { anchor: 'middle', bold: true, size: 13 }),
        line(56, 90, 90, 90, { arrow: true }),
        { kind: 'rect', x: 90, y: 65, w: 140, h: 50, rx: 10 },
        txt(160, 90, 'Bestellung prüfen', { anchor: 'middle', size: 12 }),
        txt(160, 128, 'B', { anchor: 'middle', bold: true, size: 13 }),
        line(230, 90, 262, 90, { arrow: true }),
        txt(246, 78, 'D', { anchor: 'middle', bold: true, size: 13 }),
        { kind: 'path', d: 'M 290 62 L 318 90 L 290 118 L 262 90 Z', fill: '#ffffff' },
        txt(290, 90, 'X', { anchor: 'middle', bold: true, size: 15 },),
        txt(290, 134, 'C', { anchor: 'middle', bold: true, size: 13 }),
        txt(290, 48, 'Artikel verfügbar?', { anchor: 'middle', size: 11, color: '#5f6b7c' }),
        line(290, 62, 290, 40),
        line(290, 40, 360, 40, { arrow: true }),
        txt(325, 30, 'ja', { anchor: 'middle', size: 11 }),
        { kind: 'rect', x: 360, y: 15, w: 140, h: 50, rx: 10 },
        txt(430, 40, 'Ware versenden', { anchor: 'middle', size: 12 }),
        line(500, 40, 544, 40, { arrow: true }),
        { kind: 'ellipse', cx: 560, cy: 40, rx: 16, ry: 16, fill: '#ffffff' },
        { kind: 'ellipse', cx: 560, cy: 40, rx: 13, ry: 13, fill: '#ffffff' },
        line(290, 118, 290, 140),
        line(290, 140, 360, 140, { arrow: true }),
        txt(325, 130, 'nein', { anchor: 'middle', size: 11 }),
        { kind: 'rect', x: 360, y: 115, w: 140, h: 50, rx: 10 },
        txt(430, 140, 'Kunden informieren', { anchor: 'middle', size: 12 }),
        line(500, 140, 544, 140, { arrow: true }),
        { kind: 'ellipse', cx: 560, cy: 140, rx: 16, ry: 16, fill: '#ffffff' },
        { kind: 'ellipse', cx: 560, cy: 140, rx: 13, ry: 13, fill: '#ffffff' },
        txt(560, 172, 'E', { anchor: 'middle', bold: true, size: 13 }),
        txt(20, 205, 'A (dünner Kreis):', { size: 12, bold: true }),
        txt(20, 235, 'B (abgerundetes Rechteck):', { size: 12, bold: true }),
        txt(20, 265, 'C (Raute mit X):', { size: 12, bold: true }),
        txt(20, 295, 'D (durchgezogener Pfeil):', { size: 12, bold: true }),
        txt(370, 205, 'E (dicker Doppelkreis):', { size: 12, bold: true }),
      ],
    },
    blanks: [
      { id: 'b1', x: 150, y: 193, w: 200, h: 24, accepted: ['Startereignis'], options: ['Startereignis', 'Endereignis', 'Zwischenereignis', 'Aufgabe (Task)', 'Exklusives Gateway (XOR)', 'Paralleles Gateway (AND)', 'Sequenzfluss', 'Nachrichtenfluss', 'Pool / Lane'] },
      { id: 'b2', x: 210, y: 223, w: 200, h: 24, accepted: ['Aufgabe (Task)'], options: ['Startereignis', 'Endereignis', 'Zwischenereignis', 'Aufgabe (Task)', 'Exklusives Gateway (XOR)', 'Paralleles Gateway (AND)', 'Sequenzfluss', 'Nachrichtenfluss', 'Pool / Lane'] },
      { id: 'b3', x: 150, y: 253, w: 200, h: 24, accepted: ['Exklusives Gateway (XOR)'], options: ['Startereignis', 'Endereignis', 'Zwischenereignis', 'Aufgabe (Task)', 'Exklusives Gateway (XOR)', 'Paralleles Gateway (AND)', 'Sequenzfluss', 'Nachrichtenfluss', 'Pool / Lane'] },
      { id: 'b4', x: 210, y: 283, w: 200, h: 24, accepted: ['Sequenzfluss'], options: ['Startereignis', 'Endereignis', 'Zwischenereignis', 'Aufgabe (Task)', 'Exklusives Gateway (XOR)', 'Paralleles Gateway (AND)', 'Sequenzfluss', 'Nachrichtenfluss', 'Pool / Lane'] },
      { id: 'b5', x: 530, y: 193, w: 160, h: 24, accepted: ['Endereignis'], options: ['Startereignis', 'Endereignis', 'Zwischenereignis', 'Aufgabe (Task)', 'Exklusives Gateway (XOR)', 'Paralleles Gateway (AND)', 'Sequenzfluss', 'Nachrichtenfluss', 'Pool / Lane'] },
    ],
    explanation: 'BPMN-Grundelemente: Ereignisse (Kreise: dünn = Start, dick = Ende), Aktivitäten/Aufgaben (abgerundete Rechtecke), Gateways (Rauten; X = exklusive Entscheidung, + = parallel) und Sequenzflüsse (durchgezogene Pfeile). Nachrichtenflüsse zwischen Pools werden gestrichelt gezeichnet.',
  },
  {
    id: 'ew-if-005',
    section: 'entwicklung',
    topic: 'zustandsdiagramm',
    type: 'image_fill',
    title: 'UML-Zustandsdiagramm vervollständigen',
    scenario: 'Für das Ticketsystem des IT-Supports der Klinikum Südstadt gGmbH modellieren Sie den Lebenszyklus eines Support-Tickets.',
    text: 'Ergänzen Sie die fehlenden Zustände (Felder 1–3) und Ereignisse/Transitionen (Felder 4 und 5) im Zustandsdiagramm.',
    points: 5,
    difficulty: 2,
    diagram: {
      width: 700,
      height: 260,
      elements: [
        { kind: 'ellipse', cx: 40, cy: 60, rx: 9, ry: 9, fill: '#2d3a55' },
        line(49, 60, 90, 60, { arrow: true }),
        ...box(90, 35, 130, 50, undefined, { fill: '#fffdf3' }),
        line(220, 60, 280, 60, { arrow: true }),
        txt(250, 46, 'zuweisen()', { anchor: 'middle', size: 11, mono: true }),
        ...box(280, 35, 130, 50, 'In Bearbeitung'),
        line(410, 60, 470, 60, { arrow: true }),
        txt(440, 46, 'lösen()', { anchor: 'middle', size: 11, mono: true }),
        ...box(470, 35, 130, 50, undefined, { fill: '#fffdf3' }),
        line(600, 60, 650, 60, { arrow: true }),
        txt(625, 46, 'schließen()', { anchor: 'middle', size: 11, mono: true }),
        { kind: 'ellipse', cx: 662, cy: 60, rx: 11, ry: 11, fill: '#ffffff' },
        { kind: 'ellipse', cx: 662, cy: 60, rx: 7, ry: 7, fill: '#2d3a55' },
        // Warten auf Kunde
        line(345, 85, 345, 150, { arrow: true }),
        txt(352, 118, 'Rückfrage stellen', { size: 11, mono: true }),
        ...box(280, 150, 130, 50, undefined, { fill: '#fffdf3' }),
        line(280, 175, 160, 175),
        line(160, 175, 160, 85, { arrow: true }),
        // Reopen
        line(535, 85, 535, 230),
        line(535, 230, 200, 230),
        line(200, 230, 200, 85, { arrow: true }),
        txt(360, 244, 'Kunde meldet: Problem besteht weiterhin', { size: 11, anchor: 'middle', color: '#5f6b7c' }),
      ],
    },
    blanks: [
      { id: 'b1', x: 96, y: 47, w: 118, h: 26, accepted: ['Neu / Offen'], options: ['Neu / Offen', 'Gelöst', 'Geschlossen', 'Wartet auf Kunde', 'Archiviert'] },
      { id: 'b2', x: 476, y: 47, w: 118, h: 26, accepted: ['Gelöst'], options: ['Neu / Offen', 'Gelöst', 'Geschlossen', 'Wartet auf Kunde', 'Archiviert'] },
      { id: 'b3', x: 286, y: 162, w: 118, h: 26, accepted: ['Wartet auf Kunde'], options: ['Neu / Offen', 'Gelöst', 'Geschlossen', 'Wartet auf Kunde', 'Archiviert'] },
      { id: 'b4', x: 165, y: 150, w: 110, h: 24, accepted: ['Kunde antwortet'], options: ['Kunde antwortet', 'Ticket löschen', 'schließen()', 'zuweisen()'] },
      { id: 'b5', x: 300, y: 204, w: 130, h: 24, accepted: ['wiedereröffnen()'], options: ['wiedereröffnen()', 'lösen()', 'archivieren()', 'zuweisen()'] },
    ],
    explanation: 'Ein Ticket startet im Zustand Neu/Offen, wird zugewiesen (In Bearbeitung), kann auf eine Kundenantwort warten und geht nach dem Lösen in „Gelöst“ über. Meldet der Kunde, dass das Problem weiterhin besteht, wird es wiedereröffnet; sonst wird es geschlossen (Endzustand).',
  },
];
