/**
 * Handlungsschritt 1: Kundenbedarf analysieren und Projekt planen.
 * Themen: Bedarfsanalyse, Lasten-/Pflichtenheft, Projektphasen, PSP, Meilensteine,
 * Gantt, Netzplantechnik, Vorgehensmodelle, Stakeholder, SMART, Wirtschaftlichkeit,
 * Nutzwertanalyse, Angebotsvergleich, Kommunikation, Barrierefreiheit, Risiken.
 */
import type { Question } from '../../../shared/types.js';

export const questions: Question[] = [
  /* ===================== Multiple Choice (2 Punkte) ===================== */
  {
    id: 'kb-mc-001',
    section: 'kundenbedarf',
    topic: 'lastenheft',
    type: 'multiple_choice',
    title: 'Lastenheft und Pflichtenheft',
    scenario: 'Die Fahrradmanufaktur Velomotion GmbH möchte ein neues Warenwirtschaftssystem einführen und hat Ihr Softwarehaus um ein Angebot gebeten.',
    text: 'Welche Aussage zum Lastenheft ist korrekt?',
    points: 2,
    difficulty: 1,
    options: [
      { id: 'a', text: 'Das Lastenheft wird vom Auftragnehmer erstellt und beschreibt, wie die Anforderungen technisch umgesetzt werden.' },
      { id: 'b', text: 'Das Lastenheft wird vom Auftraggeber erstellt und beschreibt, was gefordert wird und wofür die Lösung benötigt wird.' },
      { id: 'c', text: 'Das Lastenheft ist die verbindliche Abnahmeerklärung nach Projektabschluss.' },
      { id: 'd', text: 'Das Lastenheft enthält den detaillierten Testplan des Entwicklungsteams.' },
    ],
    correct: ['b'],
    multi: false,
    explanation:
      'Das Lastenheft (DIN 69901) beschreibt die Gesamtheit der Forderungen des Auftraggebers an die Lieferungen und Leistungen; das Pflichtenheft ist die Antwort des Auftragnehmers mit dem Realisierungskonzept (das „Wie“).',
  },
  {
    id: 'kb-mc-002',
    section: 'kundenbedarf',
    topic: 'projektstrukturplan',
    type: 'multiple_choice',
    title: 'Projektstrukturplan',
    scenario: 'Für die Einführung eines Ticketsystems bei der Stadtwerke Nordhafen AG soll ein Projektstrukturplan (PSP) erstellt werden.',
    text: 'Welche Aussage zum Projektstrukturplan ist korrekt?',
    points: 2,
    difficulty: 1,
    options: [
      { id: 'a', text: 'Der PSP stellt die zeitliche Abfolge der Vorgänge mit Anfangs- und Endterminen auf einer Zeitachse dar.' },
      { id: 'b', text: 'Der PSP gliedert das Projekt hierarchisch in Teilprojekte und Arbeitspakete, ohne zeitliche Reihenfolge.' },
      { id: 'c', text: 'Der PSP zeigt die Abhängigkeiten der Vorgänge und den kritischen Pfad.' },
      { id: 'd', text: 'Der PSP listet alle Stakeholder mit Einfluss und Interesse auf.' },
    ],
    correct: ['b'],
    multi: false,
    explanation:
      'Der Projektstrukturplan zerlegt das Projekt vollständig in Teilaufgaben und Arbeitspakete (objekt-, funktions- oder phasenorientiert). Die zeitliche Abfolge zeigen Gantt-Diagramm und Netzplan.',
  },
  {
    id: 'kb-mc-003',
    section: 'kundenbedarf',
    topic: 'scrum',
    type: 'multiple_choice',
    title: 'Scrum-Rollen und -Ereignisse',
    scenario: 'Das Entwicklungsteam der Reiseplattform TripNest arbeitet nach Scrum. Ein neuer Auszubildender fragt Sie nach den Grundlagen.',
    text: 'Welche Aussagen zu Scrum sind korrekt? (Mehrere Antworten möglich)',
    points: 2,
    difficulty: 2,
    options: [
      { id: 'a', text: 'Der Product Owner priorisiert das Product Backlog und vertritt die fachlichen Interessen der Stakeholder.' },
      { id: 'b', text: 'Der Scrum Master weist den Entwicklern die Aufgaben zu und kontrolliert deren Arbeitsfortschritt.' },
      { id: 'c', text: 'Im Sprint Review wird das Inkrement den Stakeholdern vorgestellt und Feedback eingeholt.' },
      { id: 'd', text: 'Ein Sprint dauert üblicherweise höchstens vier Wochen und hat eine feste Länge.' },
      { id: 'e', text: 'In der Sprint-Retrospektive werden die Anforderungen für den nächsten Sprint ausgewählt.' },
    ],
    correct: ['a', 'c', 'd'],
    multi: true,
    explanation:
      'Der Scrum Master ist Coach und Moderator, keine Führungskraft; das Team organisiert sich selbst. Die Retrospektive reflektiert die Zusammenarbeit, die Auswahl der Backlog-Einträge erfolgt im Sprint Planning.',
  },
  {
    id: 'kb-mc-004',
    section: 'kundenbedarf',
    topic: 'smart-ziele',
    type: 'multiple_choice',
    title: 'SMART formulierte Projektziele',
    scenario: 'Die Online-Apotheke MediKurier möchte die Ladezeit ihres Webshops verbessern. Sie sollen die Projektziele nach der SMART-Methode prüfen.',
    text: 'Welche der folgenden Zielformulierungen erfüllen die SMART-Kriterien? (Mehrere Antworten möglich)',
    points: 2,
    difficulty: 2,
    options: [
      { id: 'a', text: 'Der Webshop soll deutlich schneller werden.' },
      { id: 'b', text: 'Bis zum 30.09. wird die durchschnittliche Ladezeit der Produktseite von 4,2 s auf unter 2,0 s gesenkt (gemessen mit Lighthouse).' },
      { id: 'c', text: 'Bis zum Ende des Quartals werden alle Produktbilder auf das Format WebP umgestellt, sodass das Datenvolumen der Startseite um mindestens 40 % sinkt.' },
      { id: 'd', text: 'Die Kundenzufriedenheit soll in Zukunft irgendwie steigen.' },
      { id: 'e', text: 'Der Shop soll ab morgen die schnellste Website Deutschlands sein.' },
    ],
    correct: ['b', 'c'],
    multi: true,
    explanation:
      'SMART = spezifisch, messbar, attraktiv/akzeptiert, realistisch, terminiert. Die Formulierungen a und d sind weder messbar noch terminiert, e ist nicht realistisch.',
  },
  {
    id: 'kb-mc-005',
    section: 'kundenbedarf',
    topic: 'magisches-dreieck',
    type: 'multiple_choice',
    title: 'Magisches Dreieck des Projektmanagements',
    scenario: 'Im Projekt „Kassensystem 2.0“ der Bäckereikette Kornblume wünscht der Kunde kurz vor Abgabe zusätzliche Funktionen bei gleichem Termin.',
    text: 'Welche Auswirkung beschreibt das magische Dreieck des Projektmanagements in dieser Situation korrekt?',
    points: 2,
    difficulty: 1,
    options: [
      { id: 'a', text: 'Erweiterter Leistungsumfang bei gleichem Termin erfordert in der Regel höhere Kosten (z. B. mehr Personal) oder geht zulasten der Qualität.' },
      { id: 'b', text: 'Zusätzliche Funktionen haben keinen Einfluss auf Kosten oder Termin, wenn das Team motiviert ist.' },
      { id: 'c', text: 'Mehr Leistung senkt automatisch die Kosten, da mehr Nutzen erzeugt wird.' },
      { id: 'd', text: 'Das magische Dreieck betrifft nur die Beziehung zwischen Auftraggeber, Auftragnehmer und Projektleiter.' },
    ],
    correct: ['a'],
    multi: false,
    explanation:
      'Die drei Größen Leistung (Umfang/Qualität), Zeit und Kosten stehen in Konkurrenz: Wird eine Größe verändert, wirkt sich das auf mindestens eine der anderen aus.',
  },
  {
    id: 'kb-mc-006',
    section: 'kundenbedarf',
    topic: 'meilensteine',
    type: 'multiple_choice',
    title: 'Meilensteine im Projektplan',
    scenario: 'Der Projektleiter der Logistikfirma CargoLine GmbH bittet Sie, im Gantt-Diagramm für die Einführung eines Lagerverwaltungssystems Meilensteine einzutragen.',
    text: 'Welche Aussage zu Meilensteinen ist korrekt?',
    points: 2,
    difficulty: 1,
    options: [
      { id: 'a', text: 'Ein Meilenstein ist ein Vorgang mit besonders langer Dauer, der den kritischen Pfad bestimmt.' },
      { id: 'b', text: 'Ein Meilenstein ist ein Ereignis von besonderer Bedeutung mit der Dauer null, z. B. „Abnahme des Pflichtenhefts“.' },
      { id: 'c', text: 'Ein Meilenstein bezeichnet die Pufferzeit zwischen zwei Projektphasen.' },
      { id: 'd', text: 'Meilensteine werden nur in agilen Projekten am Ende jedes Sprints gesetzt.' },
    ],
    correct: ['b'],
    multi: false,
    explanation:
      'Meilensteine markieren überprüfbare Zwischenergebnisse oder Phasenübergänge; sie verbrauchen keine Zeit und Ressourcen und dienen der Fortschrittskontrolle.',
  },
  {
    id: 'kb-mc-007',
    section: 'kundenbedarf',
    topic: 'netzplantechnik',
    type: 'multiple_choice',
    title: 'Pufferzeiten im Netzplan',
    scenario: 'Bei der Planung der Migration des E-Mail-Systems der Kanzlei Bergmann & Partner haben Sie einen Netzplan erstellt.',
    text: 'Welche Aussage zum Gesamtpuffer (GP) eines Vorgangs ist korrekt?',
    points: 2,
    difficulty: 2,
    options: [
      { id: 'a', text: 'Der Gesamtpuffer ist die Zeitspanne, um die ein Vorgang verschoben werden kann, ohne den Projektendtermin zu gefährden (GP = SAZ − FAZ).' },
      { id: 'b', text: 'Der Gesamtpuffer ist die Summe aller Vorgangsdauern auf dem kritischen Pfad.' },
      { id: 'c', text: 'Der Gesamtpuffer ist die Zeitspanne, um die ein Vorgang verschoben werden kann, ohne den frühesten Anfang des Nachfolgers zu verändern.' },
      { id: 'd', text: 'Der Gesamtpuffer ist bei allen Vorgängen größer als null, sonst wäre das Projekt nicht durchführbar.' },
    ],
    correct: ['a'],
    multi: false,
    explanation:
      'GP = SAZ − FAZ (bzw. SEZ − FEZ). Antwort c beschreibt den freien Puffer (FP). Vorgänge auf dem kritischen Pfad haben den Gesamtpuffer 0.',
  },
  {
    id: 'kb-mc-008',
    section: 'kundenbedarf',
    topic: 'vorgehensmodelle',
    type: 'multiple_choice',
    title: 'Wasserfallmodell und V-Modell',
    scenario: 'Die Medizintechnikfirma Cardiosense GmbH muss für eine Steuerungssoftware nachweisen, dass jede Anforderung getestet wurde. Sie diskutieren das passende Vorgehensmodell.',
    text: 'Welche Aussagen zu klassischen Vorgehensmodellen sind korrekt? (Mehrere Antworten möglich)',
    points: 2,
    difficulty: 2,
    options: [
      { id: 'a', text: 'Im V-Modell ist jeder Entwicklungsphase eine Testphase gegenübergestellt (z. B. Anforderungsdefinition – Abnahmetest).' },
      { id: 'b', text: 'Das Wasserfallmodell eignet sich besonders, wenn sich die Anforderungen während des Projekts häufig ändern.' },
      { id: 'c', text: 'Beim Wasserfallmodell werden die Phasen sequenziell durchlaufen; jede Phase endet mit einem Dokument als Ergebnis.' },
      { id: 'd', text: 'Das V-Modell verzichtet vollständig auf Dokumentation und setzt auf tägliche Absprachen.' },
    ],
    correct: ['a', 'c'],
    multi: true,
    explanation:
      'Klassische Modelle sind plangetrieben und dokumentenorientiert; sie passen zu stabilen, klar definierten Anforderungen. Bei häufigen Änderungen sind agile Modelle im Vorteil.',
  },

  /* ===================== Zuordnung (3 Punkte) ===================== */
  {
    id: 'kb-ma-001',
    section: 'kundenbedarf',
    topic: 'netzplantechnik',
    type: 'matching',
    title: 'Begriffe der Netzplantechnik',
    scenario: 'Sie erläutern einem neuen Kollegen der Solarfirma Heliotec AG die Felder eines Vorgangsknotens im Netzplan.',
    text: 'Ordnen Sie jeder Beschreibung die passende Abkürzung zu.',
    points: 3,
    difficulty: 1,
    left: [
      { id: 'l1', text: 'Frühestmöglicher Zeitpunkt, an dem ein Vorgang beginnen kann' },
      { id: 'l2', text: 'Spätester Zeitpunkt, an dem ein Vorgang enden darf, ohne das Projektende zu verzögern' },
      { id: 'l3', text: 'Zeitspanne, um die ein Vorgang verschoben werden kann, ohne den frühesten Anfang eines Nachfolgers zu verändern' },
      { id: 'l4', text: 'Zeitspanne, um die ein Vorgang verschoben werden kann, ohne das Projektende zu verzögern' },
      { id: 'l5', text: 'Frühestmöglicher Zeitpunkt, an dem ein Vorgang abgeschlossen ist' },
    ],
    right: [
      { id: 'r1', text: 'FAZ' },
      { id: 'r2', text: 'FEZ' },
      { id: 'r3', text: 'SAZ' },
      { id: 'r4', text: 'SEZ' },
      { id: 'r5', text: 'GP' },
      { id: 'r6', text: 'FP' },
      { id: 'r7', text: 'D' },
    ],
    pairs: { l1: 'r1', l2: 'r4', l3: 'r6', l4: 'r5', l5: 'r2' },
    explanation:
      'FAZ/FEZ ergeben sich aus der Vorwärtsrechnung, SAZ/SEZ aus der Rückwärtsrechnung. GP = SAZ − FAZ; FP = min(FAZ der Nachfolger) − FEZ.',
  },
  {
    id: 'kb-ma-002',
    section: 'kundenbedarf',
    topic: 'vorgehensmodelle',
    type: 'matching',
    title: 'Vorgehensmodelle der Softwareentwicklung',
    scenario: 'Die Agentur PixelPark berät Kunden bei der Wahl eines Vorgehensmodells für ihre Softwareprojekte.',
    text: 'Ordnen Sie jeder Beschreibung das passende Vorgehensmodell bzw. Framework zu.',
    points: 3,
    difficulty: 2,
    left: [
      { id: 'l1', text: 'Sequenzieller Ablauf fester Phasen; ein Rücksprung ist nicht vorgesehen' },
      { id: 'l2', text: 'Jeder Entwicklungsstufe ist eine Teststufe zugeordnet; stark in sicherheitskritischen und öffentlichen Projekten verbreitet' },
      { id: 'l3', text: 'Arbeit in festen Iterationen (Sprints) mit definierten Rollen wie Product Owner und Scrum Master' },
      { id: 'l4', text: 'Visualisierung des Arbeitsflusses auf einem Board und Begrenzung der parallel bearbeiteten Aufgaben (WIP-Limit)' },
      { id: 'l5', text: 'Programmierung in Paaren, testgetriebene Entwicklung und ständige Integration als Kernpraktiken' },
    ],
    right: [
      { id: 'r1', text: 'Scrum' },
      { id: 'r2', text: 'Kanban' },
      { id: 'r3', text: 'Wasserfallmodell' },
      { id: 'r4', text: 'V-Modell' },
      { id: 'r5', text: 'Extreme Programming (XP)' },
      { id: 'r6', text: 'Spiralmodell' },
      { id: 'r7', text: 'Prototyping' },
    ],
    pairs: { l1: 'r3', l2: 'r4', l3: 'r1', l4: 'r2', l5: 'r5' },
    explanation:
      'Wasserfall und V-Modell sind plangetrieben; Scrum, Kanban und XP zählen zu den agilen Ansätzen. Das Spiralmodell ist risikogetrieben und iterativ.',
  },
  {
    id: 'kb-ma-003',
    section: 'kundenbedarf',
    topic: 'wirtschaftlichkeit',
    type: 'matching',
    title: 'Verfahren der Wirtschaftlichkeitsbetrachtung',
    scenario: 'Die Geschäftsführung der Möbelmanufaktur Holzwerk Riedel möchte die Anschaffung einer CAD-Software bewerten lassen.',
    text: 'Ordnen Sie jeder Fragestellung das passende Verfahren bzw. die passende Kennzahl zu.',
    points: 3,
    difficulty: 2,
    left: [
      { id: 'l1', text: 'Nach wie vielen Jahren haben die Einsparungen die Investition wieder eingebracht?' },
      { id: 'l2', text: 'Ab welcher Absatzmenge decken die Erlöse die gesamten Kosten?' },
      { id: 'l3', text: 'Welche Alternative erzielt unter Berücksichtigung gewichteter, auch nicht monetärer Kriterien die höchste Punktzahl?' },
      { id: 'l4', text: 'Welche Gesamtkosten (Anschaffung, Betrieb, Wartung, Schulung, Entsorgung) entstehen über die gesamte Nutzungsdauer?' },
      { id: 'l5', text: 'Ist es günstiger, die Leistung selbst zu erbringen oder extern zu beziehen?' },
    ],
    right: [
      { id: 'r1', text: 'Nutzwertanalyse' },
      { id: 'r2', text: 'Break-Even-Analyse' },
      { id: 'r3', text: 'Amortisationsrechnung' },
      { id: 'r4', text: 'Total Cost of Ownership (TCO)' },
      { id: 'r5', text: 'Make-or-Buy-Analyse' },
      { id: 'r6', text: 'Lineare Abschreibung' },
      { id: 'r7', text: 'ABC-Analyse' },
    ],
    pairs: { l1: 'r3', l2: 'r2', l3: 'r1', l4: 'r4', l5: 'r5' },
    explanation:
      'Amortisation = Investition ÷ jährlicher Rückfluss; Break-Even = Fixkosten ÷ Deckungsbeitrag je Stück; die Nutzwertanalyse bewertet qualitative Kriterien mit Gewichtung; TCO betrachtet alle Kosten über den Lebenszyklus.',
  },

  /* ===================== Lückentext (3 Punkte) ===================== */
  {
    id: 'kb-cl-001',
    section: 'kundenbedarf',
    topic: 'netzplantechnik',
    type: 'cloze',
    title: 'Kleiner Netzplan auswerten',
    scenario: 'Für die Einführung einer Zeiterfassung bei der Gärtnerei Grünwald liegt folgende Vorgangsliste vor (Dauer in Tagen).',
    text: '| Vorgang | Dauer | Vorgänger\n| A | 2 | –\n| B | 5 | A\n| C | 3 | A\n| D | 4 | B, C\n\nErgänzen Sie den Text. Rechnen Sie mit FAZ des ersten Vorgangs = 0.',
    points: 3,
    difficulty: 2,
    template:
      'Die Gesamtdauer des Projekts beträgt {{b1}} Tage. Der kritische Pfad verläuft über die Vorgänge {{b2}}. Vorgang D kann frühestens am Tag {{b3}} beginnen (FAZ). Vorgang C hat einen Gesamtpuffer von {{b4}} Tagen. Alle Vorgänge auf dem kritischen Pfad haben einen Gesamtpuffer von {{b5}}.',
    blanks: [
      { id: 'b1', accepted: ['11'] },
      { id: 'b2', accepted: ['A-B-D', 'A, B, D', 'A B D', 'A–B–D'], options: ['A-B-D', 'A-C-D', 'A-B-C-D', 'B-D', 'A-D'] },
      { id: 'b3', accepted: ['7'] },
      { id: 'b4', accepted: ['2'] },
      { id: 'b5', accepted: ['0', 'null', '0 Tagen'] },
    ],
    explanation:
      'Pfad A-B-D: 2 + 5 + 4 = 11 Tage (kritisch). Pfad A-C-D: 2 + 3 + 4 = 9 Tage. D beginnt nach dem späteren Vorgänger B (FEZ 7). C: FEZ = 5, SEZ = 7, GP = 2.',
  },
  {
    id: 'kb-cl-002',
    section: 'kundenbedarf',
    topic: 'projektphasen',
    type: 'cloze',
    title: 'Projektphasen und Dokumente',
    scenario: 'Die Versicherung NordSecur AG lässt ein Kundenportal entwickeln. Sie beschreiben dem Fachbereich den Ablauf eines klassischen Projekts.',
    text: 'Ergänzen Sie den Text.',
    points: 3,
    difficulty: 1,
    template:
      'Zu Beginn formuliert der Auftraggeber seine Anforderungen im {{b1}}. Der Auftragnehmer antwortet mit dem {{b2}}, das beschreibt, wie die Anforderungen umgesetzt werden. Ein Projekt ist nach DIN 69901 ein Vorhaben, das durch die {{b3}} der Bedingungen gekennzeichnet ist, z. B. eine klare Zielvorgabe sowie zeitliche, finanzielle und personelle Begrenzungen. Der {{b4}} ist das offizielle Dokument, mit dem der Auftraggeber die erbrachte Leistung akzeptiert. Der formale Start eines Projekts wird häufig mit dem {{b5}} eingeleitet.',
    blanks: [
      { id: 'b1', accepted: ['Lastenheft', 'Lastenhefts'] },
      { id: 'b2', accepted: ['Pflichtenheft', 'Pflichtenhefts'] },
      { id: 'b3', accepted: ['Einmaligkeit'], options: ['Einmaligkeit', 'Wiederholbarkeit', 'Unbegrenztheit', 'Beliebigkeit', 'Dauerhaftigkeit'] },
      { id: 'b4', accepted: ['Abnahmeprotokoll', 'Abnahmebericht'], options: ['Abnahmeprotokoll', 'Projektauftrag', 'Lastenheft', 'Statusbericht', 'Angebot'] },
      { id: 'b5', accepted: ['Kick-off', 'Kickoff', 'Kick-off-Meeting', 'Kickoff-Meeting', 'Projektauftrag'], options: ['Kick-off-Meeting', 'Sprint Review', 'Lessons Learned', 'Abnahmetest', 'Daily'] },
    ],
    explanation:
      'Lastenheft (Auftraggeber: Was?) und Pflichtenheft (Auftragnehmer: Wie?) sind die zentralen Anforderungsdokumente. Einmaligkeit, Zielvorgabe und Begrenzungen definieren ein Projekt; die Abnahme wird protokolliert.',
  },
  {
    id: 'kb-cl-003',
    section: 'kundenbedarf',
    topic: 'scrum',
    type: 'cloze',
    title: 'Agile Begriffe',
    scenario: 'Das Start-up FoodLoop entwickelt eine App zur Lebensmittelrettung nach Scrum und nutzt zusätzlich ein Kanban-Board für den Support.',
    text: 'Ergänzen Sie den Text.',
    points: 3,
    difficulty: 2,
    template:
      'Alle Anforderungen an das Produkt werden priorisiert im {{b1}} gesammelt; verantwortlich dafür ist der {{b2}}. Die Anforderungen werden häufig als User Stories formuliert, deren Erfüllung anhand von {{b3}} überprüft wird. Am Ende jedes Sprints entsteht ein auslieferbares {{b4}}. Auf dem Kanban-Board begrenzt das {{b5}} die Anzahl gleichzeitig bearbeiteter Aufgaben je Spalte.',
    blanks: [
      { id: 'b1', accepted: ['Product Backlog', 'Product-Backlog', 'Produkt-Backlog', 'Backlog'] },
      { id: 'b2', accepted: ['Product Owner', 'Product-Owner'], options: ['Product Owner', 'Scrum Master', 'Projektleiter', 'Entwicklungsteam', 'Auftraggeber'] },
      { id: 'b3', accepted: ['Akzeptanzkriterien', 'Akzeptanzkriterium'], options: ['Akzeptanzkriterien', 'Meilensteinen', 'Story Points', 'Unit-Tests', 'Lastenheften'] },
      { id: 'b4', accepted: ['Inkrement', 'Produktinkrement', 'Increment'] },
      { id: 'b5', accepted: ['WIP-Limit', 'WIP Limit', 'Work-in-Progress-Limit', 'WIP'] },
    ],
    explanation:
      'Product Backlog und Product Owner, Akzeptanzkriterien je User Story, Inkrement als Sprint-Ergebnis. Das WIP-Limit (Work in Progress) ist das zentrale Steuerungsinstrument in Kanban.',
  },

  /* ===================== Rechenaufgaben (5 Punkte) ===================== */
  {
    id: 'kb-ca-001',
    section: 'kundenbedarf',
    topic: 'break-even',
    type: 'calculation',
    title: 'Break-Even-Analyse für eine Softwarelizenz',
    scenario: 'Das Softwarehaus CodeCraft GmbH möchte eine selbst entwickelte Zeiterfassungs-App als Lizenz verkaufen.',
    text: 'Für die Entwicklung und den Vertrieb fallen jährliche Fixkosten von **48.000 €** an. Der Verkaufspreis je Lizenz beträgt **120 €**, die variablen Kosten je Lizenz (Support, Zahlungsabwicklung) betragen **40 €**.\n\na) Berechnen Sie den Deckungsbeitrag je Lizenz.\nb) Berechnen Sie die Break-Even-Menge (Anzahl Lizenzen) und den Umsatz am Break-Even-Punkt.\nc) Welcher Gewinn ergibt sich beim Verkauf von 900 Lizenzen?\n\nGeben Sie den vollständigen Lösungsweg an.',
    points: 5,
    difficulty: 2,
    solution:
      'a) Deckungsbeitrag je Lizenz = Verkaufspreis − variable Kosten = 120 € − 40 € = 80 €\n\nb) Break-Even-Menge = Fixkosten ÷ Deckungsbeitrag = 48.000 € ÷ 80 € = 600 Lizenzen\nUmsatz am Break-Even = 600 × 120 € = 72.000 €\n\nc) Gewinn = Menge × Deckungsbeitrag − Fixkosten = 900 × 80 € − 48.000 € = 72.000 € − 48.000 € = 24.000 €',
    expected: [
      { label: 'Deckungsbeitrag je Lizenz', value: 80, unit: '€' },
      { label: 'Break-Even-Menge', value: 600, unit: 'Lizenzen' },
      { label: 'Umsatz am Break-Even', value: 72000, unit: '€' },
      { label: 'Gewinn bei 900 Lizenzen', value: 24000, unit: '€' },
    ],
    rubric: [
      { criterion: 'Deckungsbeitrag korrekt (80 €)', points: 1 },
      { criterion: 'Break-Even-Menge korrekt hergeleitet (600 Lizenzen)', points: 2 },
      { criterion: 'Umsatz am Break-Even korrekt (72.000 €)', points: 1 },
      { criterion: 'Gewinn bei 900 Lizenzen korrekt (24.000 €)', points: 1 },
    ],
    explanation:
      'Am Break-Even-Punkt decken die Deckungsbeiträge genau die Fixkosten. Jede weitere verkaufte Lizenz erhöht den Gewinn um den Deckungsbeitrag von 80 €.',
  },
  {
    id: 'kb-ca-002',
    section: 'kundenbedarf',
    topic: 'nutzwertanalyse',
    type: 'calculation',
    title: 'Nutzwertanalyse für ein Ticketsystem',
    scenario: 'Die Stadtwerke Nordhafen AG wählen ein Ticketsystem für den IT-Support aus. Drei Anbieter stehen zur Auswahl.',
    text: 'Die Kriterien wurden wie folgt gewichtet und die Anbieter mit Punkten von 1 (schlecht) bis 10 (sehr gut) bewertet:\n\n| Kriterium | Gewichtung | Anbieter A | Anbieter B | Anbieter C\n| Preis | 40 | 8 | 5 | 7\n| Funktionsumfang | 30 | 6 | 9 | 7\n| Support | 20 | 5 | 8 | 6\n| Benutzerfreundlichkeit | 10 | 9 | 7 | 6\n\na) Berechnen Sie den gewichteten Nutzwert jedes Anbieters.\nb) Welcher Anbieter ist nach der Nutzwertanalyse zu empfehlen? Begründen Sie kurz.\n\nGeben Sie den vollständigen Lösungsweg an.',
    points: 5,
    difficulty: 2,
    solution:
      'a) Nutzwert = Summe (Gewichtung × Punkte)\nAnbieter A: 40×8 + 30×6 + 20×5 + 10×9 = 320 + 180 + 100 + 90 = 690\nAnbieter B: 40×5 + 30×9 + 20×8 + 10×7 = 200 + 270 + 160 + 70 = 700\nAnbieter C: 40×7 + 30×7 + 20×6 + 10×6 = 280 + 210 + 120 + 60 = 670\n\nb) Anbieter B erreicht mit 700 Punkten den höchsten Nutzwert und ist zu empfehlen. Der Vorsprung gegenüber A (690) ist allerdings gering; Preisverhandlungen oder eine Sensitivitätsprüfung der Gewichtung wären sinnvoll.',
    expected: [
      { label: 'Nutzwert Anbieter A', value: 690, tolerance: 0.5 },
      { label: 'Nutzwert Anbieter B', value: 700, tolerance: 0.5 },
      { label: 'Nutzwert Anbieter C', value: 670, tolerance: 0.5 },
    ],
    rubric: [
      { criterion: 'Rechenansatz Gewichtung × Punktzahl je Kriterium erkennbar', points: 1 },
      { criterion: 'Nutzwerte der drei Anbieter korrekt (690 / 700 / 670)', points: 3 },
      { criterion: 'Empfehlung für Anbieter B mit Begründung (höchster Nutzwert)', points: 1 },
    ],
    explanation:
      'Die Nutzwertanalyse macht qualitative Kriterien durch Gewichtung und Punktbewertung vergleichbar. Der Anbieter mit dem höchsten gewichteten Gesamtwert wird empfohlen.',
  },
  {
    id: 'kb-ca-003',
    section: 'kundenbedarf',
    topic: 'amortisation',
    type: 'calculation',
    title: 'Amortisation und Abschreibung einer Serverinvestition',
    scenario: 'Die Spedition CargoLine GmbH erwägt, ihre veralteten Server durch ein neues virtualisiertes System zu ersetzen.',
    text: 'Die Investition beträgt **36.000 €**. Durch geringeren Strom- und Wartungsaufwand werden jährliche Einsparungen von **15.000 €** erwartet; gleichzeitig entstehen neue jährliche Betriebskosten (Lizenzen, Support) von **3.000 €**. Die betriebsgewöhnliche Nutzungsdauer beträgt **5 Jahre**.\n\na) Berechnen Sie die statische Amortisationszeit in Jahren.\nb) Berechnen Sie den jährlichen Abschreibungsbetrag bei linearer Abschreibung.\nc) Welcher Gesamtvorteil (Einsparung abzüglich Investition) ergibt sich über die gesamte Nutzungsdauer?\n\nGeben Sie den vollständigen Lösungsweg an.',
    points: 5,
    difficulty: 2,
    solution:
      'a) Jährlicher Netto-Rückfluss = 15.000 € − 3.000 € = 12.000 €\nAmortisationszeit = Investition ÷ jährlicher Rückfluss = 36.000 € ÷ 12.000 € = 3 Jahre\n\nb) Lineare Abschreibung = Anschaffungskosten ÷ Nutzungsdauer = 36.000 € ÷ 5 Jahre = 7.200 € pro Jahr\n\nc) Gesamtvorteil = 5 × 12.000 € − 36.000 € = 60.000 € − 36.000 € = 24.000 €',
    expected: [
      { label: 'Jährlicher Netto-Rückfluss', value: 12000, unit: '€' },
      { label: 'Amortisationszeit', value: 3, unit: 'Jahre', tolerance: 0.05 },
      { label: 'Jährliche Abschreibung', value: 7200, unit: '€' },
      { label: 'Gesamtvorteil über 5 Jahre', value: 24000, unit: '€' },
    ],
    rubric: [
      { criterion: 'Netto-Rückfluss je Jahr korrekt ermittelt (12.000 €)', points: 1 },
      { criterion: 'Amortisationszeit korrekt (3 Jahre)', points: 2 },
      { criterion: 'Lineare Abschreibung korrekt (7.200 €/Jahr)', points: 1 },
      { criterion: 'Gesamtvorteil korrekt (24.000 €)', points: 1 },
    ],
    explanation:
      'Bei der statischen Amortisationsrechnung wird die Investition durch den jährlichen Netto-Rückfluss geteilt. Die Amortisationszeit liegt mit 3 Jahren deutlich innerhalb der Nutzungsdauer – die Investition ist wirtschaftlich.',
  },
  {
    id: 'kb-ca-004',
    section: 'kundenbedarf',
    topic: 'angebotsvergleich',
    type: 'calculation',
    title: 'Angebotsvergleich mit Rabatt und Skonto',
    scenario: 'Die Werbeagentur PixelPark benötigt 12 neue Notebooks. Zwei Händler haben Angebote abgegeben.',
    text: '**Angebot A:** Listenpreis 1.250 € netto je Notebook, 8 % Mengenrabatt, 2 % Skonto bei Zahlung innerhalb von 10 Tagen, Lieferung frei Haus.\n**Angebot B:** Listenpreis 1.180 € netto je Notebook, kein Rabatt, 3 % Skonto bei Zahlung innerhalb von 10 Tagen, zuzüglich 150 € netto Lieferkosten (auf die Lieferkosten wird kein Skonto gewährt).\n\nDie Agentur zahlt innerhalb der Skontofrist.\n\na) Berechnen Sie den Nettoeinstandspreis (Bezugspreis) für beide Angebote.\nb) Welches Angebot ist günstiger und um wie viel Euro?\nc) Berechnen Sie für das günstigere Angebot den Bruttobetrag inkl. 19 % Umsatzsteuer.\n\nGeben Sie den vollständigen Lösungsweg an.',
    points: 5,
    difficulty: 2,
    solution:
      'a) Angebot A:\nListenpreis: 12 × 1.250 € = 15.000 €\n− 8 % Rabatt: 15.000 € × 0,92 = 13.800 €\n− 2 % Skonto: 13.800 € × 0,98 = 13.524 €\nLieferung frei Haus → Einstandspreis A = 13.524 €\n\nAngebot B:\nListenpreis: 12 × 1.180 € = 14.160 €\n− 3 % Skonto: 14.160 € × 0,97 = 13.735,20 €\n+ Lieferkosten 150 € → Einstandspreis B = 13.885,20 €\n\nb) Angebot A ist günstiger: 13.885,20 € − 13.524 € = 361,20 €\n\nc) Brutto A = 13.524 € × 1,19 = 16.093,56 €',
    expected: [
      { label: 'Einstandspreis Angebot A (netto)', value: 13524, unit: '€', tolerance: 0.01 },
      { label: 'Einstandspreis Angebot B (netto)', value: 13885.2, unit: '€', tolerance: 0.01 },
      { label: 'Differenz', value: 361.2, unit: '€', tolerance: 0.01 },
      { label: 'Bruttobetrag Angebot A', value: 16093.56, unit: '€', tolerance: 0.01 },
    ],
    rubric: [
      { criterion: 'Einstandspreis A korrekt mit Rabatt und Skonto in richtiger Reihenfolge (13.524 €)', points: 2 },
      { criterion: 'Einstandspreis B korrekt, Lieferkosten ohne Skonto addiert (13.885,20 €)', points: 1.5 },
      { criterion: 'Vergleich mit Differenz korrekt (A günstiger um 361,20 €)', points: 0.5 },
      { criterion: 'Bruttobetrag korrekt (16.093,56 €)', points: 1 },
    ],
    explanation:
      'Beim Bezugspreis werden zuerst Rabatte, dann Skonto vom Zieleinkaufspreis abgezogen; Bezugskosten werden addiert. Die Umsatzsteuer ist für den Vergleich unerheblich, da sie als Vorsteuer abziehbar ist.',
  },
  {
    id: 'kb-ca-005',
    section: 'kundenbedarf',
    topic: 'stundensatz',
    type: 'calculation',
    title: 'Stundensatz und Angebotspreis berechnen',
    scenario: 'Die CodeCraft GmbH soll ein Angebot für die Entwicklung einer Schnittstelle abgeben und benötigt dafür den internen Stundensatz einer Entwicklerin.',
    text: 'Das Bruttojahresgehalt der Entwicklerin beträgt **52.000 €**. Der Arbeitgeberanteil zur Sozialversicherung wird mit **20 %** des Bruttogehalts angesetzt. Für Arbeitsplatz, Software und Verwaltung werden anteilige Gemeinkosten von **8.000 € pro Jahr** angesetzt.\n\nDie Entwicklerin hat **220 Arbeitstage** zu je **8 Stunden**; davon sind **80 %** als fakturierbare (produktive) Stunden ansetzbar.\n\na) Berechnen Sie die jährlichen Gesamtkosten der Entwicklerin.\nb) Berechnen Sie die produktiven Stunden pro Jahr und den Selbstkosten-Stundensatz.\nc) Für das Projekt werden 120 Stunden veranschlagt. Berechnen Sie den Angebotspreis (netto) bei einem Gewinnaufschlag von 25 % auf die Selbstkosten.\n\nGeben Sie den vollständigen Lösungsweg an.',
    points: 5,
    difficulty: 3,
    solution:
      'a) Personalkosten = 52.000 € × 1,20 = 62.400 €\nGesamtkosten = 62.400 € + 8.000 € = 70.400 €\n\nb) Gesamtstunden = 220 × 8 h = 1.760 h\nProduktive Stunden = 1.760 h × 0,80 = 1.408 h\nStundensatz = 70.400 € ÷ 1.408 h = 50,00 €/h\n\nc) Selbstkosten Projekt = 120 h × 50 € = 6.000 €\nAngebotspreis = 6.000 € × 1,25 = 7.500 € netto',
    expected: [
      { label: 'Jährliche Gesamtkosten', value: 70400, unit: '€' },
      { label: 'Produktive Stunden', value: 1408, unit: 'h' },
      { label: 'Stundensatz', value: 50, unit: '€/h', tolerance: 0.05 },
      { label: 'Angebotspreis netto', value: 7500, unit: '€' },
    ],
    rubric: [
      { criterion: 'Jahresgesamtkosten inkl. Arbeitgeberanteil und Gemeinkosten korrekt (70.400 €)', points: 1.5 },
      { criterion: 'Produktive Stunden korrekt (1.408 h)', points: 1 },
      { criterion: 'Stundensatz korrekt (50 €/h)', points: 1.5 },
      { criterion: 'Angebotspreis mit Gewinnaufschlag korrekt (7.500 €)', points: 1 },
    ],
    explanation:
      'Der Stundensatz muss auf die tatsächlich verrechenbaren Stunden bezogen werden, nicht auf die Anwesenheitszeit; Urlaub, Krankheit und interne Tätigkeiten mindern die produktive Zeit.',
  },
  {
    id: 'kb-ca-006',
    section: 'kundenbedarf',
    topic: 'netzplantechnik',
    type: 'calculation',
    title: 'Projektdauer aus einer Vorgangsliste ermitteln',
    scenario: 'Die Arztpraxis Dr. Keller lässt eine neue Praxissoftware einführen. Der Projektleiter hat folgende Vorgangsliste erstellt (Dauer in Arbeitstagen).',
    text: '| Vorgang | Bezeichnung | Dauer | Vorgänger\n| A | Anforderungen aufnehmen | 3 | –\n| B | Server einrichten | 4 | A\n| C | Arbeitsplätze vorbereiten | 2 | A\n| D | Software installieren und konfigurieren | 5 | B\n| E | Mitarbeiter schulen | 3 | C\n| F | Abnahme und Go-live | 2 | D, E\n\na) Ermitteln Sie die Gesamtdauer des Projekts und den kritischen Pfad.\nb) Berechnen Sie für Vorgang E den Gesamtpuffer (GP) und den freien Puffer (FP).\nc) Berechnen Sie für Vorgang C den Gesamtpuffer (GP) und den freien Puffer (FP).\n\nGeben Sie den Rechenweg an (FAZ/FEZ bzw. SAZ/SEZ der betroffenen Vorgänge). Rechnen Sie mit FAZ(A) = 0.',
    points: 5,
    difficulty: 3,
    solution:
      'a) Vorwärtsrechnung (FAZ/FEZ):\nA: 0/3, B: 3/7, C: 3/5, D: 7/12, E: 5/8, F: 12/14\nGesamtdauer = 14 Tage\nPfad A-B-D-F: 3+4+5+2 = 14 (kritisch); Pfad A-C-E-F: 3+2+3+2 = 10\nKritischer Pfad: A → B → D → F\n\nb) Rückwärtsrechnung: F: SAZ 12 / SEZ 14; E: SEZ 12, SAZ 9\nGP(E) = SAZ − FAZ = 9 − 5 = 4 Tage\nFP(E) = FAZ(F) − FEZ(E) = 12 − 8 = 4 Tage\n\nc) C: SEZ = SAZ(E) = 9, SAZ = 7\nGP(C) = 7 − 3 = 4 Tage\nFP(C) = FAZ(E) − FEZ(C) = 5 − 5 = 0 Tage',
    expected: [
      { label: 'Gesamtdauer', value: 14, unit: 'Tage' },
      { label: 'GP Vorgang E', value: 4, unit: 'Tage' },
      { label: 'FP Vorgang E', value: 4, unit: 'Tage' },
      { label: 'GP Vorgang C', value: 4, unit: 'Tage' },
      { label: 'FP Vorgang C', value: 0, unit: 'Tage' },
    ],
    rubric: [
      { criterion: 'Gesamtdauer 14 Tage und kritischer Pfad A-B-D-F korrekt', points: 2 },
      { criterion: 'GP und FP von Vorgang E korrekt (4 / 4 Tage) mit nachvollziehbarer Rückwärtsrechnung', points: 1.5 },
      { criterion: 'GP und FP von Vorgang C korrekt (4 / 0 Tage)', points: 1.5 },
    ],
    explanation:
      'Der freie Puffer von C ist 0, obwohl der Gesamtpuffer 4 beträgt: Verschiebt sich C, verschiebt sich sofort E – das Projektende aber erst, wenn der Gesamtpuffer des Teilpfads C-E aufgebraucht ist.',
  },

  /* ===================== Freitext (2 Punkte) ===================== */
  {
    id: 'kb-ft-001',
    section: 'kundenbedarf',
    topic: 'stakeholder',
    type: 'free_text',
    title: 'Stakeholderanalyse',
    scenario: 'Die Stadtbibliothek Lindenau möchte ein Online-Ausleihsystem einführen. Sie sollen das Projekt vorbereiten.',
    text: 'Erläutern Sie, was unter einer Stakeholderanalyse zu verstehen ist, und nennen Sie zwei konkrete Stakeholder dieses Projekts mit jeweils einem Interesse, das sie am Projekt haben.',
    points: 2,
    difficulty: 1,
    solution:
      'Die Stakeholderanalyse identifiziert alle Personen und Gruppen, die vom Projekt betroffen sind oder Einfluss darauf haben, und bewertet deren Interessen, Erwartungen und Einfluss (z. B. in einer Macht-Interesse-Matrix), um daraus Maßnahmen für Kommunikation und Einbindung abzuleiten.\nBeispiele: Bibliotheksmitarbeiter (einfache Bedienung, keine Mehrarbeit), Nutzer/Leser (bequeme Ausleihe, Datenschutz), Stadtverwaltung/Kämmerei (Kosten im Budget), Datenschutzbeauftragter (DSGVO-Konformität), Systemlieferant (Auftragsvolumen).',
    rubric: [
      { criterion: 'Stakeholderanalyse korrekt erläutert (Betroffene/Einflussnehmer identifizieren und nach Interesse/Einfluss bewerten)', points: 1 },
      { criterion: 'Zwei passende Stakeholder mit je einem plausiblen Interesse genannt', points: 1 },
    ],
    explanation:
      'Stakeholder sind alle, die ein berechtigtes Interesse am Projekt haben. Ihre frühzeitige Einbindung verringert Widerstände und Änderungswünsche im späteren Projektverlauf.',
  },
  {
    id: 'kb-ft-002',
    section: 'kundenbedarf',
    topic: 'projektrisiken',
    type: 'free_text',
    title: 'Projektrisiken und Gegenmaßnahmen',
    scenario: 'Die Möbelmanufaktur Holzwerk Riedel migriert ihre Kundendaten in ein neues CRM-System. Der Projektleiter bittet Sie um eine Risikoeinschätzung.',
    text: 'Nennen Sie zwei typische Risiken dieses Migrationsprojekts und geben Sie zu jedem Risiko eine geeignete Gegenmaßnahme an.',
    points: 2,
    difficulty: 2,
    solution:
      'Mögliche Risiken und Maßnahmen:\n- Datenverlust oder fehlerhafte Übernahme bei der Migration → vollständiges Backup vor der Migration, Testmigration mit Stichprobenprüfung, Abgleich der Datensatzanzahl.\n- Ausfall von Schlüsselpersonen (Know-how-Träger) → Dokumentation, Vertretungsregelung, Wissen im Team verteilen.\n- Terminverzug durch unklare Anforderungen → Anforderungen im Lastenheft präzisieren, Meilensteine und Pufferzeiten einplanen.\n- Akzeptanzprobleme bei Mitarbeitenden → frühzeitige Einbindung, Schulungen.\n- Datenschutzverstöße → Verfahrensverzeichnis, Datenschutzbeauftragten einbeziehen, Zugriffskonzept.',
    rubric: [
      { criterion: 'Zwei realistische Projektrisiken genannt', points: 1 },
      { criterion: 'Zu jedem Risiko eine passende, konkrete Gegenmaßnahme', points: 1 },
    ],
    explanation:
      'Risikomanagement umfasst Identifikation, Bewertung (Eintrittswahrscheinlichkeit × Schadenshöhe), Maßnahmenplanung und Überwachung während des gesamten Projekts.',
  },
  {
    id: 'kb-ft-003',
    section: 'kundenbedarf',
    topic: 'kommunikation',
    type: 'free_text',
    title: 'Zielgruppengerechte Präsentation',
    scenario: 'Sie sollen die Ergebnisse Ihrer Bedarfsanalyse für ein neues Kassensystem der Geschäftsführung der Bäckereikette Kornblume präsentieren. Die Geschäftsführung hat keine IT-Kenntnisse.',
    text: 'Nennen und begründen Sie zwei Maßnahmen, mit denen Sie Ihre Präsentation an diese Zielgruppe anpassen.',
    points: 2,
    difficulty: 1,
    solution:
      'Mögliche Maßnahmen:\n- Fachbegriffe und Abkürzungen vermeiden bzw. erklären, da die Zuhörer sonst den Inhalt nicht nachvollziehen können.\n- Nutzen und Kosten in den Vordergrund stellen (Wirtschaftlichkeit, Zeitersparnis) statt technischer Details, weil die Geschäftsführung Entscheidungen auf dieser Basis trifft.\n- Visualisierungen (Diagramme, Vorher-Nachher-Vergleich) statt Textwüsten, um komplexe Zusammenhänge verständlich zu machen.\n- Kurze, strukturierte Präsentation mit klarer Handlungsempfehlung am Ende, da die Zeit der Geschäftsführung begrenzt ist.',
    rubric: [
      { criterion: 'Zwei passende Maßnahmen zur Anpassung an eine fachfremde Zielgruppe genannt', points: 1 },
      { criterion: 'Jede Maßnahme nachvollziehbar begründet', points: 1 },
    ],
    explanation:
      'Zielgruppengerechte Kommunikation orientiert sich an Vorwissen, Interessen und Entscheidungskompetenz der Adressaten: Entscheider brauchen Nutzen, Kosten und Empfehlung, keine technischen Details.',
  },
  {
    id: 'kb-ft-004',
    section: 'kundenbedarf',
    topic: 'make-or-buy',
    type: 'free_text',
    title: 'Make-or-Buy-Entscheidung',
    scenario: 'Die Reiseplattform TripNest benötigt eine Funktion zur Online-Bezahlung. Das Team überlegt, ob es die Zahlungsabwicklung selbst entwickelt oder einen externen Zahlungsdienstleister einbindet.',
    text: 'Nennen Sie je zwei Kriterien, die für „Make“ (Eigenentwicklung) und für „Buy“ (Fremdbezug) sprechen können.',
    points: 2,
    difficulty: 2,
    solution:
      'Für Make (Eigenentwicklung): volle Kontrolle über Funktionsumfang und Anpassbarkeit; Know-how bleibt im Unternehmen; keine Abhängigkeit von einem Anbieter (Vendor Lock-in); keine laufenden Lizenz-/Transaktionsgebühren.\nFür Buy (Fremdbezug): schnellere Verfügbarkeit; geringere Entwicklungskosten und geringeres Risiko; Anbieter übernimmt Sicherheit, Zertifizierung (z. B. PCI DSS) und Wartung; eigenes Personal kann sich auf das Kerngeschäft konzentrieren.',
    rubric: [
      { criterion: 'Zwei passende Kriterien für Eigenentwicklung', points: 1 },
      { criterion: 'Zwei passende Kriterien für Fremdbezug', points: 1 },
    ],
    explanation:
      'Bei Make-or-Buy werden neben Kosten auch Zeit, Know-how, Risiko, strategische Bedeutung und Abhängigkeiten betrachtet. Gerade bei Zahlungsabwicklung sprechen Sicherheitsanforderungen und Zertifizierungen häufig für Buy.',
  },
  {
    id: 'kb-ft-005',
    section: 'kundenbedarf',
    topic: 'barrierefreiheit',
    type: 'free_text',
    title: 'Barrierefreiheit als Anforderung',
    scenario: 'Die Stadtverwaltung Lindenau beauftragt ein Bürgerportal. Im Lastenheft soll die Barrierefreiheit als nicht-funktionale Anforderung aufgenommen werden.',
    text: 'Begründen Sie, warum Barrierefreiheit für dieses Projekt eine verbindliche Anforderung ist, und nennen Sie zwei konkrete, überprüfbare Anforderungen, die Sie ins Lastenheft aufnehmen.',
    points: 2,
    difficulty: 2,
    solution:
      'Begründung: Öffentliche Stellen sind gesetzlich (BGG, BITV 2.0, EU-Richtlinie 2016/2102) verpflichtet, ihre Webangebote barrierefrei zu gestalten; außerdem erreicht das Portal so alle Bürgerinnen und Bürger, auch Menschen mit Seh-, Hör- oder motorischen Einschränkungen.\nÜberprüfbare Anforderungen (Beispiele):\n- Konformität mit WCAG 2.1 Stufe AA bzw. BITV 2.0.\n- Alle Funktionen sind vollständig per Tastatur bedienbar.\n- Alle Bilder haben Alternativtexte; Formularfelder sind beschriftet (Labels).\n- Kontrastverhältnis von mindestens 4,5:1 für Fließtext.\n- Kompatibilität mit Screenreadern (semantisches HTML, ARIA).',
    rubric: [
      { criterion: 'Begründung mit rechtlicher Pflicht (BITV/BGG) und/oder Nutzengedanke (alle Bürger erreichen)', points: 1 },
      { criterion: 'Zwei konkrete, prüfbare Anforderungen genannt', points: 1 },
    ],
    explanation:
      'Nicht-funktionale Anforderungen wie Barrierefreiheit müssen im Lastenheft messbar formuliert werden (z. B. Bezug auf WCAG/BITV), damit sie bei der Abnahme geprüft werden können.',
  },
];
