/**
 * Handlungsschritt 4: IT-Systeme in ein Netzwerk einbinden.
 * ID-Präfix: nw
 */
import type { Question } from '../../../shared/types.js';

export const questions: Question[] = [
  /* =====================================================================
   * RECHENAUFGABEN (5 Punkte)
   * ===================================================================== */
  {
    id: 'nw-ca-001',
    section: 'netzwerk',
    topic: 'subnetting',
    type: 'calculation',
    title: 'Aufteilung eines /24-Netzes in gleich große Subnetze',
    scenario: 'Die Fahrradmanufaktur Velomotion GmbH nutzt das Netz 192.168.10.0/24. Es soll in vier gleich große Subnetze für Verwaltung, Produktion, Lager und Gäste-WLAN aufgeteilt werden.',
    text: 'a) Geben Sie die Subnetzmaske der neuen Subnetze in Dezimalschreibweise und in CIDR-Schreibweise an.\nb) Wie viele Hosts können in jedem Subnetz adressiert werden?\nc) Geben Sie für alle vier Subnetze die Netzadresse, den nutzbaren Hostbereich (erste und letzte Hostadresse) und die Broadcastadresse an.\n\nGeben Sie den vollständigen Lösungsweg an.',
    points: 5,
    difficulty: 2,
    solution:
      'a) 4 Subnetze → 2 zusätzliche Netzbits (2^2 = 4). Präfix: /24 + 2 = **/26**\nSubnetzmaske: 255.255.255.**192** (11000000 im letzten Oktett)\n\nb) Hostbits: 32 − 26 = 6 → 2^6 − 2 = **62 Hosts** je Subnetz (Netz- und Broadcastadresse abgezogen)\n\nc) Blockgröße 256 / 4 = 64 Adressen je Subnetz:\n| Subnetz | Netzadresse | Erster Host | Letzter Host | Broadcast\n| 1 (Verwaltung) | 192.168.10.0/26 | 192.168.10.1 | 192.168.10.62 | 192.168.10.63\n| 2 (Produktion) | 192.168.10.64/26 | 192.168.10.65 | 192.168.10.126 | 192.168.10.127\n| 3 (Lager) | 192.168.10.128/26 | 192.168.10.129 | 192.168.10.190 | 192.168.10.191\n| 4 (Gäste) | 192.168.10.192/26 | 192.168.10.193 | 192.168.10.254 | 192.168.10.255',
    expected: [
      { label: 'Präfixlänge', value: 26, tolerance: 0 },
      { label: 'Letztes Oktett der Subnetzmaske', value: 192, tolerance: 0 },
      { label: 'Hosts je Subnetz', value: 62, tolerance: 0 },
      { label: 'Letztes Oktett Broadcast Subnetz 3', value: 191, tolerance: 0 },
    ],
    rubric: [
      { criterion: 'Subnetzmaske 255.255.255.192 bzw. /26 korrekt hergeleitet', points: 1 },
      { criterion: 'Hostanzahl 62 je Subnetz korrekt (2^6 − 2)', points: 1 },
      { criterion: 'Vier Netzadressen (.0, .64, .128, .192) korrekt', points: 1.5 },
      { criterion: 'Hostbereiche und Broadcastadressen (.63, .127, .191, .255) korrekt', points: 1.5 },
    ],
    explanation: 'Zwei geliehene Hostbits ergeben vier Subnetze mit je 64 Adressen; die erste Adresse ist das Netz, die letzte der Broadcast.',
  },
  {
    id: 'nw-ca-002',
    section: 'netzwerk',
    topic: 'vlsm',
    type: 'calculation',
    title: 'Subnetting mit variabler Länge (VLSM)',
    scenario: 'Die Werkzeugbau Hartmann GmbH hat den Adressbereich 10.20.0.0/24 erhalten und benötigt Subnetze unterschiedlicher Größe. Die Adressen sollen möglichst sparsam vergeben werden.',
    text: 'Folgende Subnetze werden benötigt:\n- Vertrieb: 100 Hosts\n- Produktion: 50 Hosts\n- Verwaltung: 25 Hosts\n- Verbindungsnetz zum Router-Standort: 2 Hosts\n\na) Bestimmen Sie für jedes Subnetz die kleinstmögliche Präfixlänge (CIDR) und die Anzahl nutzbarer Hosts.\nb) Vergeben Sie die Subnetze lückenlos, beginnend mit dem größten Subnetz bei 10.20.0.0. Geben Sie jeweils Netzadresse und Broadcastadresse an.\nc) Wie viele Adressen des /24-Netzes bleiben nach der Vergabe unbenutzt?\n\nGeben Sie den vollständigen Lösungsweg an.',
    points: 5,
    difficulty: 3,
    solution:
      'a) Präfixe (Hostbits so wählen, dass 2^h − 2 ≥ Bedarf):\nVertrieb 100 → 7 Hostbits (126 Hosts) → **/25**\nProduktion 50 → 6 Hostbits (62 Hosts) → **/26**\nVerwaltung 25 → 5 Hostbits (30 Hosts) → **/27**\nVerbindungsnetz 2 → 2 Hostbits (2 Hosts) → **/30**\n\nb) Vergabe vom größten zum kleinsten Netz:\n| Subnetz | Netzadresse | Broadcast | Adressen\n| Vertrieb | 10.20.0.0/25 | 10.20.0.127 | 128\n| Produktion | 10.20.0.128/26 | 10.20.0.191 | 64\n| Verwaltung | 10.20.0.192/27 | 10.20.0.223 | 32\n| Verbindung | 10.20.0.224/30 | 10.20.0.227 | 4\n\nc) Verbrauchte Adressen: 128 + 64 + 32 + 4 = 228\nUnbenutzt: 256 − 228 = **28 Adressen** (10.20.0.228 bis 10.20.0.255)',
    expected: [
      { label: 'Nutzbare Hosts Vertrieb (/25)', value: 126, tolerance: 0 },
      { label: 'Nutzbare Hosts Verwaltung (/27)', value: 30, tolerance: 0 },
      { label: 'Letztes Oktett Netzadresse Verwaltung', value: 192, tolerance: 0 },
      { label: 'Letztes Oktett Broadcast Verbindungsnetz', value: 227, tolerance: 0 },
      { label: 'Unbenutzte Adressen', value: 28, tolerance: 0 },
    ],
    rubric: [
      { criterion: 'Präfixlängen /25, /26, /27, /30 mit Hostanzahlen 126, 62, 30, 2 korrekt', points: 2 },
      { criterion: 'Netz- und Broadcastadressen in korrekter, lückenloser Reihenfolge (.0/.127, .128/.191, .192/.223, .224/.227)', points: 2 },
      { criterion: 'Verbleibende 28 Adressen korrekt berechnet', points: 1 },
    ],
    explanation: 'VLSM vergibt Subnetze absteigend nach Größe, damit jedes Netz an einer zu seiner Blockgröße passenden Grenze beginnt und keine Adressen verschwendet werden.',
  },
  {
    id: 'nw-ca-003',
    section: 'netzwerk',
    topic: 'uebertragungsdauer',
    type: 'calculation',
    title: 'Übertragungsdauer einer Datei',
    scenario: 'Das Architekturbüro Lichtblick tauscht mit einer Außenstelle regelmäßig Planungsdaten aus. Die Standleitung hat eine Bandbreite von 100 Mbit/s.',
    text: 'Eine Projektdatei ist 4,5 GB groß (1 GB = 10^9 Byte). Durch Protokoll-Overhead stehen effektiv nur 80 % der Bandbreite für Nutzdaten zur Verfügung.\n\na) Berechnen Sie die Dateigröße in Bit.\nb) Berechnen Sie die effektive Nutzdatenrate in Mbit/s.\nc) Berechnen Sie die Übertragungsdauer der Datei in Sekunden und in Minuten.\nd) Wie lange dauert die Übertragung bei einer Leitung mit 1 Gbit/s und gleichem Overhead?\n\nGeben Sie den vollständigen Lösungsweg an.',
    points: 5,
    difficulty: 1,
    solution:
      'a) 4,5 GB = 4,5 × 10^9 Byte × 8 Bit/Byte = **3,6 × 10^10 Bit** (36.000.000.000 Bit)\n\nb) Effektive Datenrate: 100 Mbit/s × 0,8 = **80 Mbit/s** = 8 × 10^7 Bit/s\n\nc) Dauer = 3,6 × 10^10 Bit / 8 × 10^7 Bit/s = **450 s** = **7,5 min**\n\nd) 1 Gbit/s × 0,8 = 800 Mbit/s = 8 × 10^8 Bit/s\nDauer = 3,6 × 10^10 / 8 × 10^8 = **45 s** (Faktor 10 schneller)',
    expected: [
      { label: 'Dateigröße', value: 36000000000, unit: 'Bit', tolerance: 1 },
      { label: 'Nutzdatenrate', value: 80, unit: 'Mbit/s', tolerance: 0 },
      { label: 'Übertragungsdauer 100 Mbit/s', value: 450, unit: 's', tolerance: 0.5 },
      { label: 'Übertragungsdauer 1 Gbit/s', value: 45, unit: 's', tolerance: 0.5 },
    ],
    rubric: [
      { criterion: 'Umrechnung Byte → Bit korrekt (3,6 × 10^10 Bit)', points: 1 },
      { criterion: 'Effektive Datenrate 80 Mbit/s korrekt', points: 1 },
      { criterion: 'Übertragungsdauer 450 s = 7,5 min korrekt', points: 2 },
      { criterion: 'Dauer bei 1 Gbit/s (45 s) korrekt', points: 1 },
    ],
    explanation: 'Dauer = Datenmenge / Datenrate. Wichtig: Byte in Bit umrechnen (× 8) und den Overhead als Faktor auf die Bandbreite anwenden.',
  },
  {
    id: 'nw-ca-004',
    section: 'netzwerk',
    topic: 'bandbreite',
    type: 'calculation',
    title: 'Bandbreitenbedarf für Videostreams',
    scenario: 'Die Berufsschule am Stadtpark richtet einen Schulungsraum ein, in dem Lernvideos gestreamt und Videokonferenzen geführt werden. Der Internetanschluss hat 100 Mbit/s im Download.',
    text: 'Gleichzeitig laufen maximal 12 Lernvideos in Full-HD mit je 5 Mbit/s sowie 4 Videokonferenzen mit je 2,5 Mbit/s.\n\na) Berechnen Sie die insgesamt benötigte Bandbreite in Mbit/s.\nb) Die IT-Abteilung fordert 30 % Reserve auf den berechneten Bedarf. Reicht der Anschluss aus? Begründen Sie mit Zahlen.\nc) Berechnen Sie das Datenvolumen in GB, das anfällt, wenn diese Last an 20 Schultagen jeweils 2 Stunden pro Tag besteht (1 GB = 1000 MB, 1 MB = 8 Mbit).\n\nGeben Sie den vollständigen Lösungsweg an.',
    points: 5,
    difficulty: 2,
    solution:
      'a) Lernvideos: 12 × 5 Mbit/s = 60 Mbit/s\nKonferenzen: 4 × 2,5 Mbit/s = 10 Mbit/s\nGesamt: **70 Mbit/s**\n\nb) Mit 30 % Reserve: 70 Mbit/s × 1,3 = **91 Mbit/s**\n91 Mbit/s ≤ 100 Mbit/s → der Anschluss reicht aus, allerdings nur mit knapp 9 Mbit/s Luft für sonstigen Verkehr.\n\nc) Zeit: 20 Tage × 2 h × 3.600 s = 144.000 s\nDatenmenge: 70 Mbit/s × 144.000 s = 10.080.000 Mbit\nIn MB: 10.080.000 / 8 = 1.260.000 MB\nIn GB: 1.260.000 / 1.000 = **1.260 GB** (= 1,26 TB)',
    expected: [
      { label: 'Gesamtbandbreite', value: 70, unit: 'Mbit/s', tolerance: 0 },
      { label: 'Bandbreite mit Reserve', value: 91, unit: 'Mbit/s', tolerance: 0 },
      { label: 'Datenvolumen', value: 1260, unit: 'GB', tolerance: 1 },
    ],
    rubric: [
      { criterion: 'Gesamtbandbreite 70 Mbit/s korrekt (60 + 10)', points: 1.5 },
      { criterion: 'Bedarf mit Reserve 91 Mbit/s und begründete Bewertung (reicht aus)', points: 1.5 },
      { criterion: 'Datenvolumen 1.260 GB mit korrekter Umrechnung Mbit → MB → GB', points: 2 },
    ],
    explanation: 'Bandbreite ist die Summe der gleichzeitigen Datenströme; das Volumen ergibt sich aus Datenrate × Zeit, wobei Bit und Byte sauber zu trennen sind.',
  },
  {
    id: 'nw-ca-005',
    section: 'netzwerk',
    topic: 'subnetting',
    type: 'calculation',
    title: 'Netzgrenzen eines /22-Netzes',
    scenario: 'Der Logistikdienstleister Cargo Express erhält für sein Zentrallager das Netz 172.20.4.0/22. Ein neuer Drucker soll die Adresse 172.20.8.1 bekommen.',
    text: 'a) Geben Sie die Subnetzmaske in Dezimalschreibweise an.\nb) Berechnen Sie die Anzahl der adressierbaren Hosts in diesem Netz.\nc) Bestimmen Sie die erste und die letzte nutzbare Hostadresse sowie die Broadcastadresse.\nd) Beurteilen Sie, ob der Drucker mit der Adresse 172.20.8.1 im selben Netz erreichbar ist. Begründen Sie.\n\nGeben Sie den vollständigen Lösungsweg an.',
    points: 5,
    difficulty: 2,
    solution:
      'a) /22 → 22 Netzbits: 11111111.11111111.11111100.00000000 → **255.255.252.0**\n\nb) Hostbits: 32 − 22 = 10 → 2^10 − 2 = **1.022 Hosts**\n\nc) Blockgröße im dritten Oktett: 256 − 252 = 4 → Netze 172.20.0.0, 172.20.4.0, 172.20.8.0 …\nDas Netz 172.20.4.0/22 umfasst 172.20.4.0 bis 172.20.7.255.\nErste Hostadresse: **172.20.4.1**\nLetzte Hostadresse: **172.20.7.254**\nBroadcast: **172.20.7.255**\n\nd) Nein. 172.20.8.1 liegt im nächsten Block (172.20.8.0/22) und damit außerhalb des Netzes 172.20.4.0 – 172.20.7.255. Der Drucker wäre ohne Router nicht erreichbar; er benötigt eine Adresse aus 172.20.4.1 – 172.20.7.254.',
    expected: [
      { label: 'Drittes Oktett der Subnetzmaske', value: 252, tolerance: 0 },
      { label: 'Anzahl Hosts', value: 1022, tolerance: 0 },
      { label: 'Drittes Oktett der Broadcastadresse', value: 7, tolerance: 0 },
    ],
    rubric: [
      { criterion: 'Subnetzmaske 255.255.252.0 korrekt', points: 1 },
      { criterion: 'Hostanzahl 1.022 korrekt (2^10 − 2)', points: 1 },
      { criterion: 'Hostbereich 172.20.4.1 – 172.20.7.254 und Broadcast 172.20.7.255 korrekt', points: 2 },
      { criterion: 'Beurteilung des Druckers korrekt begründet (liegt außerhalb, nächster Block ab 172.20.8.0)', points: 1 },
    ],
    explanation: 'Bei /22 liegt die Netzgrenze im dritten Oktett (Schrittweite 4). Das Netz reicht von .4.0 bis .7.255; .8.1 gehört bereits zum nächsten Netz.',
  },
  {
    id: 'nw-ca-006',
    section: 'netzwerk',
    topic: 'ipv6',
    type: 'calculation',
    title: 'IPv6-Adressen kürzen und Subnetze zählen',
    scenario: 'Die Medienagentur Klangfarbe stellt ihr Firmennetz auf IPv6 um und hat vom Provider das Präfix 2001:db8:4711::/48 erhalten.',
    text: 'a) Kürzen Sie die Adresse `2001:0db8:0000:0000:0000:ff00:0042:8329` nach den Regeln der IPv6-Schreibweise maximal.\nb) Schreiben Sie die gekürzte Adresse `fe80::1a2b:0:0:1` vollständig (ungekürzt) aus.\nc) Wie viele /64-Subnetze kann die Agentur aus ihrem /48-Präfix bilden? Geben Sie den Rechenweg an.\nd) Wie viele Bit umfasst die Interface-ID (Hostanteil) in einem /64-Subnetz?\n\nGeben Sie den vollständigen Lösungsweg an.',
    points: 5,
    difficulty: 3,
    solution:
      'a) Führende Nullen in jedem Block entfernen: 2001:db8:0:0:0:ff00:42:8329\nLängste Folge von Nullblöcken (drei Blöcke) einmalig durch "::" ersetzen:\n→ **2001:db8::ff00:42:8329**\n\nb) fe80::1a2b:0:0:1 hat 4 Blöcke ausgeschrieben, "::" steht also für 8 − 4 = 4 Nullblöcke:\n→ **fe80:0000:0000:0000:1a2b:0000:0000:0001**\n\nc) Präfix /48, Subnetz /64 → 64 − 48 = 16 Bit für Subnetz-IDs\n2^16 = **65.536 Subnetze**\n\nd) 128 Bit − 64 Bit Präfix = **64 Bit** Interface-ID',
    expected: [
      { label: 'Subnetz-Bits', value: 16, unit: 'Bit', tolerance: 0 },
      { label: 'Anzahl /64-Subnetze', value: 65536, tolerance: 0 },
      { label: 'Interface-ID', value: 64, unit: 'Bit', tolerance: 0 },
    ],
    rubric: [
      { criterion: 'Kürzung 2001:db8::ff00:42:8329 korrekt (führende Nullen entfernt, längste Nullfolge durch :: ersetzt)', points: 1.5 },
      { criterion: 'Ausgeschriebene Adresse fe80:0000:0000:0000:1a2b:0000:0000:0001 korrekt', points: 1.5 },
      { criterion: '16 Subnetz-Bits und 2^16 = 65.536 Subnetze korrekt', points: 1.5 },
      { criterion: 'Interface-ID 64 Bit korrekt', points: 0.5 },
    ],
    explanation: 'IPv6: 128 Bit in 8 Hexadezimalblöcken. "::" darf nur einmal vorkommen und ersetzt die längste Folge von Nullblöcken; ein /48-Präfix lässt 16 Bit für 65.536 /64-Subnetze.',
  },

  /* =====================================================================
   * MULTIPLE CHOICE (3 Punkte)
   * ===================================================================== */
  {
    id: 'nw-mc-001',
    section: 'netzwerk',
    topic: 'protokolle',
    type: 'multiple_choice',
    title: 'Protokolle auf UDP-Basis',
    scenario: 'Die Systemhaus Kettner GmbH konfiguriert die Firewall eines Kunden und muss festlegen, für welche Dienste UDP-Ports freigegeben werden müssen.',
    text: 'Welche der folgenden Protokolle nutzen auf der Transportschicht primär **UDP**? (Mehrere Antworten möglich)',
    points: 3,
    difficulty: 2,
    options: [
      { id: 'a', text: 'DNS (Namensauflösung)' },
      { id: 'b', text: 'HTTP (Webseitenabruf)' },
      { id: 'c', text: 'DHCP (automatische Adressvergabe)' },
      { id: 'd', text: 'SSH (verschlüsselte Fernwartung)' },
      { id: 'e', text: 'NTP (Zeitsynchronisation)' },
      { id: 'f', text: 'SMTP (E-Mail-Versand)' },
    ],
    correct: ['a', 'c', 'e'],
    multi: true,
    explanation: 'DNS-Anfragen, DHCP (Broadcast-basiert) und NTP nutzen das verbindungslose UDP, weil kurze Nachrichten ohne Verbindungsaufbau genügen. HTTP, SSH und SMTP benötigen die zuverlässige Übertragung von TCP.',
  },
  {
    id: 'nw-mc-002',
    section: 'netzwerk',
    topic: 'osi',
    type: 'multiple_choice',
    title: 'Router im OSI-Modell',
    scenario: 'Im Netzwerk der Bäckereikette Kornblume soll ein Router die Filialnetze mit der Zentrale verbinden. Ein Auszubildender fragt, auf welcher Ebene das Gerät arbeitet.',
    text: 'Auf welcher Schicht des OSI-Modells trifft ein klassischer Router seine Weiterleitungsentscheidung, und anhand welcher Information?',
    points: 3,
    difficulty: 1,
    options: [
      { id: 'a', text: 'Schicht 2 (Sicherungsschicht) anhand der MAC-Adresse' },
      { id: 'b', text: 'Schicht 3 (Vermittlungsschicht) anhand der IP-Adresse' },
      { id: 'c', text: 'Schicht 4 (Transportschicht) anhand der Portnummer' },
      { id: 'd', text: 'Schicht 1 (Bitübertragungsschicht) anhand des elektrischen Signals' },
      { id: 'e', text: 'Schicht 7 (Anwendungsschicht) anhand der URL' },
    ],
    correct: ['b'],
    multi: false,
    explanation: 'Router arbeiten auf Schicht 3 und leiten Pakete anhand der Ziel-IP-Adresse und ihrer Routingtabelle weiter. Switches arbeiten auf Schicht 2 mit MAC-Adressen.',
  },
  {
    id: 'nw-mc-003',
    section: 'netzwerk',
    topic: 'ipv4',
    type: 'multiple_choice',
    title: 'Private IPv4-Adressbereiche',
    scenario: 'Für das interne Netz der Zahnarztpraxis Dr. Sommer sollen private IPv4-Adressen verwendet werden, die im Internet nicht geroutet werden.',
    text: 'Welche der folgenden Adressen stammen aus einem **privaten** Adressbereich nach RFC 1918? (Mehrere Antworten möglich)',
    points: 3,
    difficulty: 2,
    options: [
      { id: 'a', text: '10.45.200.3' },
      { id: 'b', text: '172.32.10.1' },
      { id: 'c', text: '192.168.250.17' },
      { id: 'd', text: '169.254.10.20' },
      { id: 'e', text: '172.20.0.99' },
      { id: 'f', text: '127.0.0.1' },
    ],
    correct: ['a', 'c', 'e'],
    multi: true,
    explanation: 'Private Bereiche: 10.0.0.0/8, 172.16.0.0/12 (172.16.0.0 – 172.31.255.255) und 192.168.0.0/16. 172.32.x.x liegt außerhalb, 169.254.x.x ist APIPA (Link-local), 127.x.x.x ist Loopback.',
  },
  {
    id: 'nw-mc-004',
    section: 'netzwerk',
    topic: 'dhcp',
    type: 'multiple_choice',
    title: 'Ablauf der DHCP-Adressvergabe',
    scenario: 'Ein neues Notebook der Eventagentur Feierlaune wird ins Firmennetz eingebunden und bezieht seine IP-Konfiguration automatisch.',
    text: 'In welcher Reihenfolge laufen die Nachrichten der DHCP-Adressvergabe (DORA) ab?',
    points: 3,
    difficulty: 1,
    options: [
      { id: 'a', text: 'Discover (Client) → Offer (Server) → Request (Client) → Acknowledge (Server)' },
      { id: 'b', text: 'Offer (Server) → Discover (Client) → Acknowledge (Server) → Request (Client)' },
      { id: 'c', text: 'Request (Client) → Offer (Server) → Discover (Client) → Acknowledge (Server)' },
      { id: 'd', text: 'Discover (Server) → Offer (Client) → Request (Server) → Acknowledge (Client)' },
      { id: 'e', text: 'Discover (Client) → Request (Client) → Offer (Server) → Acknowledge (Server)' },
    ],
    correct: ['a'],
    multi: false,
    explanation: 'Der Client sucht per Broadcast (Discover), Server bieten Adressen an (Offer), der Client wählt und fordert eine Adresse an (Request), der Server bestätigt (Acknowledge).',
  },
  {
    id: 'nw-mc-005',
    section: 'netzwerk',
    topic: 'vlan',
    type: 'multiple_choice',
    title: 'Kommunikation zwischen VLANs',
    scenario: 'Im Netz der Steuerberatung Hoffmann sind Buchhaltung (VLAN 10) und Empfang (VLAN 20) auf demselben Switch getrennt. Der Empfang soll auf den Drucker der Buchhaltung zugreifen können.',
    text: 'Welche Maßnahme ist notwendig, damit Geräte aus VLAN 20 den Drucker in VLAN 10 erreichen können?',
    points: 3,
    difficulty: 2,
    options: [
      { id: 'a', text: 'Ein Router oder Layer-3-Switch muss zwischen den VLANs routen (Inter-VLAN-Routing).' },
      { id: 'b', text: 'Es genügt, beide Geräte an denselben Switch anzuschließen, da Switches alle Ports verbinden.' },
      { id: 'c', text: 'Der Drucker muss eine zweite MAC-Adresse erhalten.' },
      { id: 'd', text: 'Ein Hub muss zwischen die beiden VLANs geschaltet werden.' },
      { id: 'e', text: 'Beide Geräte müssen dieselbe IP-Adresse verwenden.' },
    ],
    correct: ['a'],
    multi: false,
    explanation: 'VLANs sind getrennte Broadcast-Domänen auf Schicht 2. Verkehr zwischen ihnen erfordert Routing auf Schicht 3, z. B. durch einen Layer-3-Switch oder Router (Router-on-a-Stick).',
  },
  {
    id: 'nw-mc-006',
    section: 'netzwerk',
    topic: 'wlan',
    type: 'multiple_choice',
    title: 'Sicheres WLAN einrichten',
    scenario: 'Das Café Bohnenglück möchte ein Mitarbeiter-WLAN und ein Gäste-WLAN einrichten und bittet um Empfehlungen zur Absicherung.',
    text: 'Welche Maßnahmen tragen wirksam zur Sicherheit des WLANs bei? (Mehrere Antworten möglich)',
    points: 3,
    difficulty: 2,
    options: [
      { id: 'a', text: 'Verschlüsselung mit WPA3 bzw. mindestens WPA2 mit AES/CCMP' },
      { id: 'b', text: 'Verschlüsselung mit WEP, da es von allen Geräten unterstützt wird' },
      { id: 'c', text: 'Gäste-WLAN als separates VLAN ohne Zugriff auf das Firmennetz' },
      { id: 'd', text: 'WPS per PIN dauerhaft aktivieren, damit Gäste sich einfach verbinden können' },
      { id: 'e', text: 'Langes, zufälliges WLAN-Passwort und regelmäßige Firmware-Updates des Access Points' },
      { id: 'f', text: 'Verstecken der SSID als alleinige Schutzmaßnahme' },
    ],
    correct: ['a', 'c', 'e'],
    multi: true,
    explanation: 'WEP ist gebrochen, WPS-PIN ist angreifbar und eine versteckte SSID bietet keinen echten Schutz. Wirksam sind moderne Verschlüsselung, Netztrennung und gepflegte Geräte.',
  },
  {
    id: 'nw-mc-007',
    section: 'netzwerk',
    topic: 'tcp-udp',
    type: 'multiple_choice',
    title: 'Eigenschaften von TCP',
    scenario: 'Die Entwickler der Telemetrie-Plattform SensorCloud diskutieren, ob Messwerte per TCP oder UDP übertragen werden sollen.',
    text: 'Welche Aussage über TCP ist korrekt?',
    points: 3,
    difficulty: 2,
    options: [
      { id: 'a', text: 'TCP baut vor der Datenübertragung eine Verbindung auf (Drei-Wege-Handshake) und bestätigt empfangene Segmente.' },
      { id: 'b', text: 'TCP ist verbindungslos und verzichtet auf Bestätigungen, um die Latenz zu minimieren.' },
      { id: 'c', text: 'TCP arbeitet auf Schicht 3 des OSI-Modells und vergibt IP-Adressen.' },
      { id: 'd', text: 'TCP verschlüsselt alle übertragenen Daten automatisch.' },
      { id: 'e', text: 'TCP wird ausschließlich für Sprach- und Videoübertragung in Echtzeit eingesetzt.' },
    ],
    correct: ['a'],
    multi: false,
    explanation: 'TCP (Schicht 4) ist verbindungsorientiert, zuverlässig (Bestätigungen, Wiederholungen, Reihenfolge) und hat dadurch mehr Overhead als das verbindungslose UDP, das für Echtzeitanwendungen bevorzugt wird.',
  },

  /* =====================================================================
   * LÜCKENTEXT (2 Punkte)
   * ===================================================================== */
  {
    id: 'nw-cl-001',
    section: 'netzwerk',
    topic: 'ipv4',
    type: 'cloze',
    title: 'IPv4-Adressierung',
    scenario: 'Sie dokumentieren die Adressierung im Büronetz der Kanzlei Bergmann & Partner.',
    text: 'Ergänzen Sie den Text.',
    points: 2,
    difficulty: 1,
    template:
      'Eine IPv4-Adresse ist {{b1}} Bit lang. Bei der Subnetzmaske 255.255.255.0 stehen {{b2}} Bit für den Hostanteil zur Verfügung; damit sind {{b3}} Hosts adressierbar. Die höchste Adresse eines Subnetzes ist die {{b4}}.',
    blanks: [
      { id: 'b1', accepted: ['32'] },
      { id: 'b2', accepted: ['8'] },
      { id: 'b3', accepted: ['254'] },
      { id: 'b4', accepted: ['Broadcastadresse', 'Broadcast-Adresse', 'Broadcast'], options: ['Netzadresse', 'Broadcastadresse', 'Gateway-Adresse', 'Loopback-Adresse'] },
    ],
    explanation: '32 Bit Gesamtlänge, /24 lässt 8 Hostbits: 2^8 − 2 = 254 nutzbare Hosts; die letzte Adresse ist der Broadcast.',
  },
  {
    id: 'nw-cl-002',
    section: 'netzwerk',
    topic: 'dhcp',
    type: 'cloze',
    title: 'DHCP-Ablauf',
    scenario: 'Sie erklären einem neuen Kollegen im Systemhaus Kettner, wie ein Client seine IP-Konfiguration erhält.',
    text: 'Ergänzen Sie den Text.',
    points: 2,
    difficulty: 2,
    template:
      'Ein Client ohne IP-Adresse sendet eine DHCP-{{b1}}-Nachricht als {{b2}} ins Netz. Der DHCP-Server antwortet mit einem {{b3}}, in dem er eine Adresse vorschlägt. Neben der IP-Adresse und der Subnetzmaske übermittelt der Server üblicherweise auch das Standard-{{b4}} und die Adresse des {{b5}}-Servers. Die Adresse wird nur für eine begrenzte Zeit (Lease) vergeben.',
    blanks: [
      { id: 'b1', accepted: ['Discover', 'DHCPDISCOVER'], options: ['Discover', 'Offer', 'Request', 'Acknowledge', 'Release'] },
      { id: 'b2', accepted: ['Broadcast', 'Broadcastnachricht'], options: ['Broadcast', 'Unicast', 'Multicast', 'Anycast'] },
      { id: 'b3', accepted: ['Offer', 'DHCPOFFER', 'DHCP-Offer'], options: ['Discover', 'Offer', 'Request', 'Acknowledge', 'Release'] },
      { id: 'b4', accepted: ['Gateway', 'Standardgateway', 'Default Gateway'] },
      { id: 'b5', accepted: ['DNS'] },
    ],
    explanation: 'DORA: Discover (Broadcast) – Offer – Request – Acknowledge. Der Server verteilt neben IP und Maske auch Gateway, DNS-Server und die Lease-Zeit.',
  },
  {
    id: 'nw-cl-003',
    section: 'netzwerk',
    topic: 'ports',
    type: 'cloze',
    title: 'Protokolle und Standardports',
    scenario: 'Für die Firewall der Ferienhausvermittlung Küstenglück sollen die benötigten Dienste mit ihren Standardports dokumentiert werden.',
    text: 'Ergänzen Sie den Text.',
    points: 2,
    difficulty: 2,
    template:
      'Der Webserver ist über HTTPS auf Port {{b1}} erreichbar, unverschlüsseltes HTTP nutzt Port {{b2}}. Die Administration erfolgt per SSH über Port {{b3}}. Die Namensauflösung übernimmt der DNS-Server auf Port {{b4}}. Der Remote-Desktop-Zugriff auf den Windows-Server nutzt das Protokoll {{b5}} auf Port 3389.',
    blanks: [
      { id: 'b1', accepted: ['443'] },
      { id: 'b2', accepted: ['80'] },
      { id: 'b3', accepted: ['22'] },
      { id: 'b4', accepted: ['53'] },
      { id: 'b5', accepted: ['RDP', 'Remote Desktop Protocol'], options: ['RDP', 'VNC', 'Telnet', 'SMB', 'FTP'] },
    ],
    explanation: 'Well-known Ports: HTTP 80, HTTPS 443, SSH 22, DNS 53, RDP 3389, SMTP 25, IMAP 143, FTP 21, NTP 123.',
  },
  {
    id: 'nw-cl-004',
    section: 'netzwerk',
    topic: 'verkabelung',
    type: 'cloze',
    title: 'Strukturierte Verkabelung',
    scenario: 'Für den Neubau der Kunststofftechnik Rehberg GmbH planen Sie die strukturierte Gebäudeverkabelung.',
    text: 'Ergänzen Sie den Text.',
    points: 2,
    difficulty: 2,
    template:
      'Die strukturierte Verkabelung gliedert sich in drei Bereiche: Der {{b1}}bereich verbindet die Gebäude eines Standorts, der {{b2}}bereich die Etagen innerhalb eines Gebäudes und der {{b3}}bereich die Etagenverteiler mit den Anschlussdosen der Arbeitsplätze. Für die Gebäudeverbindung wird wegen der großen Entfernung und der Unempfindlichkeit gegen elektromagnetische Störungen meist {{b4}} eingesetzt. In der Etagenverkabelung ist Twisted-Pair-Kabel der Kategorie {{b5}} für 10 Gbit/s über 100 m geeignet.',
    blanks: [
      { id: 'b1', accepted: ['Primär', 'Primaer'], options: ['Primär', 'Sekundär', 'Tertiär', 'Quartär'] },
      { id: 'b2', accepted: ['Sekundär', 'Sekundaer'], options: ['Primär', 'Sekundär', 'Tertiär', 'Quartär'] },
      { id: 'b3', accepted: ['Tertiär', 'Tertiaer'], options: ['Primär', 'Sekundär', 'Tertiär', 'Quartär'] },
      { id: 'b4', accepted: ['Glasfaser', 'LWL', 'Lichtwellenleiter', 'Glasfaserkabel'], options: ['Glasfaser', 'Koaxialkabel', 'Cat-5e-Kupferkabel', 'Richtfunk', 'Telefonkabel'] },
      { id: 'b5', accepted: ['6a', 'Cat 6a', 'Cat6a', '6A'] },
    ],
    explanation: 'Primär = Campus (Gebäude–Gebäude, LWL), Sekundär = Steigbereich (Etagen, meist LWL), Tertiär = Etagenbereich (Kupfer, Cat 6a für 10GBASE-T bis 100 m).',
  },
  {
    id: 'nw-cl-005',
    section: 'netzwerk',
    topic: 'ipv6',
    type: 'cloze',
    title: 'Grundlagen IPv6',
    scenario: 'Die Medienagentur Klangfarbe stellt auf IPv6 um; Sie fassen die wichtigsten Eigenschaften für die Dokumentation zusammen.',
    text: 'Ergänzen Sie den Text.',
    points: 2,
    difficulty: 2,
    template:
      'Eine IPv6-Adresse ist {{b1}} Bit lang und wird in acht Blöcken in {{b2}} Schreibweise dargestellt, getrennt durch Doppelpunkte. Eine zusammenhängende Folge von Nullblöcken darf einmal durch {{b3}} ersetzt werden. Adressen, die mit fe80 beginnen, sind {{b4}}-Adressen und nur im lokalen Netzsegment gültig. Für die automatische Adresskonfiguration ohne DHCP-Server nutzt IPv6 das Verfahren {{b5}}.',
    blanks: [
      { id: 'b1', accepted: ['128'] },
      { id: 'b2', accepted: ['hexadezimaler', 'hexadezimal', 'Hexadezimal'], options: ['hexadezimaler', 'dezimaler', 'binärer', 'oktaler'] },
      { id: 'b3', accepted: ['::', 'zwei Doppelpunkte', 'Doppel-Doppelpunkt'] },
      { id: 'b4', accepted: ['Link-local', 'Link-Local', 'Linklocal', 'link-lokale', 'verbindungslokale'], options: ['Link-local', 'Global Unicast', 'Multicast', 'Loopback', 'Unique Local'] },
      { id: 'b5', accepted: ['SLAAC', 'Stateless Address Autoconfiguration'], options: ['SLAAC', 'DHCPv4', 'APIPA', 'NAT64', 'ARP'] },
    ],
    explanation: 'IPv6: 128 Bit, hexadezimal, "::" nur einmal; fe80::/10 ist Link-local; SLAAC bildet Adressen aus Router-Advertisements und der Interface-ID.',
  },

  /* =====================================================================
   * ZUORDNUNG (4 Punkte)
   * ===================================================================== */
  {
    id: 'nw-ma-001',
    section: 'netzwerk',
    topic: 'ports',
    type: 'matching',
    title: 'Protokolle und Standardports',
    scenario: 'Für die Firewall-Konfiguration der Spedition Hellwig Logistik GmbH müssen die Standardports der eingesetzten Dienste bekannt sein.',
    text: 'Ordnen Sie jedem Protokoll den zugehörigen Standardport zu.',
    points: 4,
    difficulty: 1,
    left: [
      { id: 'l1', text: 'HTTPS' },
      { id: 'l2', text: 'SSH' },
      { id: 'l3', text: 'DNS' },
      { id: 'l4', text: 'SMTP' },
      { id: 'l5', text: 'RDP' },
      { id: 'l6', text: 'HTTP' },
    ],
    right: [
      { id: 'r1', text: '443' },
      { id: 'r2', text: '22' },
      { id: 'r3', text: '53' },
      { id: 'r4', text: '25' },
      { id: 'r5', text: '3389' },
      { id: 'r6', text: '80' },
      { id: 'r7', text: '21' },
      { id: 'r8', text: '110' },
      { id: 'r9', text: '123' },
    ],
    pairs: { l1: 'r1', l2: 'r2', l3: 'r3', l4: 'r4', l5: 'r5', l6: 'r6' },
    explanation: 'Well-known Ports: HTTP 80, HTTPS 443, SSH 22, DNS 53, SMTP 25, RDP 3389. Distraktoren: FTP 21, POP3 110, NTP 123.',
  },
  {
    id: 'nw-ma-002',
    section: 'netzwerk',
    topic: 'komponenten',
    type: 'matching',
    title: 'Netzwerkkomponenten und ihre Funktion',
    scenario: 'Die Tischlerei Eichenhof möchte ihr Netzwerk erweitern und bittet Sie, die Funktion der angebotenen Komponenten zu erläutern.',
    text: 'Ordnen Sie jeder Funktionsbeschreibung die passende Netzwerkkomponente zu.',
    points: 4,
    difficulty: 1,
    left: [
      { id: 'l1', text: 'Verbindet Netzwerke auf Schicht 3 und leitet Pakete anhand der IP-Adresse weiter' },
      { id: 'l2', text: 'Leitet Frames anhand der MAC-Adresse gezielt an den richtigen Port weiter' },
      { id: 'l3', text: 'Sendet alle eingehenden Signale an sämtliche Ports weiter (eine Kollisionsdomäne)' },
      { id: 'l4', text: 'Bindet WLAN-Clients an das kabelgebundene Netzwerk an' },
      { id: 'l5', text: 'Wandelt die Signale des Providers (z. B. DSL, Kabel, Glasfaser) in Ethernet-Signale um' },
    ],
    right: [
      { id: 'r1', text: 'Router' },
      { id: 'r2', text: 'Switch' },
      { id: 'r3', text: 'Hub' },
      { id: 'r4', text: 'Access Point' },
      { id: 'r5', text: 'Modem' },
      { id: 'r6', text: 'Repeater' },
      { id: 'r7', text: 'Patchpanel' },
    ],
    pairs: { l1: 'r1', l2: 'r2', l3: 'r3', l4: 'r4', l5: 'r5' },
    explanation: 'Hub (Schicht 1) flutet alle Ports, Switch (Schicht 2) schaltet gezielt per MAC-Tabelle, Router (Schicht 3) verbindet Netze; Access Point und Modem sind Medienübergänge.',
  },
  {
    id: 'nw-ma-003',
    section: 'netzwerk',
    topic: 'osi',
    type: 'matching',
    title: 'OSI-Schichten und ihre Elemente',
    scenario: 'Zur Fehlersuche im Netzwerk der Bäckereikette Kornblume ordnen Sie die beteiligten Komponenten und Protokolle den OSI-Schichten zu.',
    text: 'Ordnen Sie jeder OSI-Schicht das passende Element zu.',
    points: 4,
    difficulty: 2,
    left: [
      { id: 'l1', text: 'Schicht 1 – Bitübertragungsschicht' },
      { id: 'l2', text: 'Schicht 2 – Sicherungsschicht' },
      { id: 'l3', text: 'Schicht 3 – Vermittlungsschicht' },
      { id: 'l4', text: 'Schicht 4 – Transportschicht' },
      { id: 'l5', text: 'Schicht 7 – Anwendungsschicht' },
    ],
    right: [
      { id: 'r1', text: 'Kabel, Stecker, Hub, Repeater' },
      { id: 'r2', text: 'Ethernet-Frame, MAC-Adresse, Switch' },
      { id: 'r3', text: 'IP-Paket, IP-Adresse, Router' },
      { id: 'r4', text: 'TCP/UDP, Portnummern' },
      { id: 'r5', text: 'HTTP, SMTP, DNS' },
      { id: 'r6', text: 'Datenkompression und Zeichenkodierung' },
      { id: 'r7', text: 'Sitzungsverwaltung (Auf- und Abbau von Sessions)' },
    ],
    pairs: { l1: 'r1', l2: 'r2', l3: 'r3', l4: 'r4', l5: 'r5' },
    explanation: 'Merkhilfe: Schicht 1 Bits/Kabel, 2 Frames/MAC/Switch, 3 Pakete/IP/Router, 4 Segmente/Ports/TCP-UDP, 5 Sitzung, 6 Darstellung, 7 Anwendung.',
  },
  {
    id: 'nw-ma-004',
    section: 'netzwerk',
    topic: 'uebertragungsmedien',
    type: 'matching',
    title: 'Übertragungsmedien und Kabeltypen',
    scenario: 'Für die Vernetzung des neuen Produktionsgebäudes der Kunststofftechnik Rehberg GmbH sind verschiedene Übertragungsmedien im Gespräch.',
    text: 'Ordnen Sie jeder Beschreibung das passende Übertragungsmedium zu.',
    points: 4,
    difficulty: 2,
    left: [
      { id: 'l1', text: 'Twisted-Pair-Kupferkabel, spezifiziert für 10 Gbit/s über 100 m' },
      { id: 'l2', text: 'Twisted-Pair-Kupferkabel, spezifiziert für 1 Gbit/s über 100 m, nicht für 10 Gbit/s über die volle Länge' },
      { id: 'l3', text: 'Glasfaser für große Distanzen (mehrere Kilometer), sehr dünner Kern, Laser als Lichtquelle' },
      { id: 'l4', text: 'Glasfaser für kurze Distanzen (bis einige hundert Meter), dickerer Kern, LED/VCSEL als Lichtquelle' },
      { id: 'l5', text: 'Kabelloses Medium im 2,4- und 5-GHz-Band, störanfällig, geteilte Bandbreite' },
    ],
    right: [
      { id: 'r1', text: 'Cat 6a' },
      { id: 'r2', text: 'Cat 5e' },
      { id: 'r3', text: 'LWL Singlemode' },
      { id: 'r4', text: 'LWL Multimode' },
      { id: 'r5', text: 'WLAN (IEEE 802.11)' },
      { id: 'r6', text: 'Koaxialkabel' },
      { id: 'r7', text: 'Cat 3' },
    ],
    pairs: { l1: 'r1', l2: 'r2', l3: 'r3', l4: 'r4', l5: 'r5' },
    explanation: 'Cat 5e = 1 Gbit/s, Cat 6a = 10 Gbit/s über 100 m; Singlemode-LWL für weite, Multimode für kurze Strecken; WLAN teilt sich das Funkmedium.',
  },

  /* =====================================================================
   * FREITEXT (3 Punkte)
   * ===================================================================== */
  {
    id: 'nw-ft-001',
    section: 'netzwerk',
    topic: 'tcp-udp',
    type: 'free_text',
    title: 'TCP oder UDP',
    scenario: 'Die Entwickler der Telemetrie-Plattform SensorCloud müssen entscheiden, ob Sensordaten per TCP oder UDP übertragen werden.',
    text: 'Erläutern Sie **zwei wesentliche Unterschiede** zwischen TCP und UDP und nennen Sie zu jedem Protokoll ein typisches Anwendungsbeispiel.',
    points: 3,
    difficulty: 2,
    solution:
      'Unterschiede (zwei genügen):\n- Verbindung: TCP ist verbindungsorientiert (Drei-Wege-Handshake), UDP verbindungslos.\n- Zuverlässigkeit: TCP bestätigt Segmente, wiederholt verlorene Daten und stellt die Reihenfolge sicher; UDP liefert ohne Bestätigung und ohne Garantie.\n- Overhead/Geschwindigkeit: TCP hat größere Header und mehr Verwaltungsaufwand, UDP ist schlanker und schneller mit geringerer Latenz.\n- Flusskontrolle/Staukontrolle nur bei TCP.\n\nBeispiele: TCP – HTTP/HTTPS, E-Mail (SMTP), Dateiübertragung (FTP, SSH). UDP – DNS, DHCP, VoIP, Videostreaming, Online-Spiele.',
    rubric: [
      { criterion: 'Zwei korrekte Unterschiede fachlich erläutert (z. B. Verbindungsaufbau, Zuverlässigkeit, Overhead)', points: 2 },
      { criterion: 'Je ein passendes Anwendungsbeispiel für TCP und UDP', points: 1 },
    ],
    explanation: 'TCP = zuverlässig und verbindungsorientiert, UDP = schnell und verbindungslos; Echtzeitanwendungen nehmen Paketverlust in Kauf, Dateiübertragungen nicht.',
  },
  {
    id: 'nw-ft-002',
    section: 'netzwerk',
    topic: 'vlan',
    type: 'free_text',
    title: 'Einsatz von VLANs begründen',
    scenario: 'Die Steuerberatung Hoffmann betreibt Buchhaltung, Empfang und Gäste-WLAN bislang in einem gemeinsamen Netz. Sie schlagen die Einführung von VLANs vor.',
    text: 'Nennen und erläutern Sie **zwei Vorteile** des Einsatzes von VLANs für die Kanzlei. Erläutern Sie außerdem, welche Komponente erforderlich ist, damit Geräte aus verschiedenen VLANs bei Bedarf miteinander kommunizieren können.',
    points: 3,
    difficulty: 2,
    solution:
      'Vorteile (zwei genügen):\n- Sicherheit: Logische Trennung, z. B. Gäste erreichen die Buchhaltungsserver nicht; Zugriffe können an der VLAN-Grenze gefiltert werden.\n- Kleinere Broadcast-Domänen: Weniger Broadcast-Verkehr, bessere Performance und Übersicht.\n- Flexibilität: Zuordnung eines Geräts zu einem Netz per Switch-Konfiguration statt Umverkabelung; abteilungsübergreifend über mehrere Switches (Trunk, IEEE 802.1Q).\n- Kostenersparnis: Keine separate physische Infrastruktur je Netz nötig.\n\nKommunikation zwischen VLANs: Ein Router oder Layer-3-Switch (Inter-VLAN-Routing), an dem Firewall-Regeln definiert werden können.',
    rubric: [
      { criterion: 'Zwei Vorteile korrekt genannt und auf die Situation bezogen erläutert', points: 2 },
      { criterion: 'Router / Layer-3-Switch für Inter-VLAN-Routing genannt', points: 1 },
    ],
    explanation: 'VLANs trennen auf Schicht 2 logisch, was physisch dieselbe Infrastruktur nutzt; die Kopplung erfolgt kontrolliert auf Schicht 3.',
  },
  {
    id: 'nw-ft-003',
    section: 'netzwerk',
    topic: 'dmz',
    type: 'free_text',
    title: 'Demilitarisierte Zone',
    scenario: 'Der Online-Shop "Bergsport Nord" möchte seinen Webserver aus dem Internet erreichbar machen, ohne das interne Firmennetz zu gefährden.',
    text: 'Erklären Sie, was eine **DMZ** ist und welchen Zweck sie erfüllt. Nennen Sie zwei Beispiele für Systeme, die typischerweise in einer DMZ platziert werden.',
    points: 3,
    difficulty: 2,
    solution:
      'Eine DMZ (demilitarisierte Zone) ist ein eigenes Netzsegment zwischen dem Internet und dem internen Netz, das durch eine oder zwei Firewalls von beiden Seiten abgeschirmt wird.\nZweck: Öffentlich erreichbare Dienste werden isoliert betrieben. Wird ein Server in der DMZ kompromittiert, hat der Angreifer keinen direkten Zugriff auf das interne LAN, da Verbindungen aus der DMZ ins interne Netz durch die Firewall streng begrenzt sind.\nTypische Systeme: Webserver, Mailserver (Relay), Reverse-Proxy, öffentlicher DNS-Server, VPN-Gateway, FTP-Server.',
    rubric: [
      { criterion: 'DMZ korrekt als abgeschirmtes Netzsegment zwischen Internet und LAN beschrieben', points: 1 },
      { criterion: 'Zweck (Isolation öffentlich erreichbarer Dienste, Schutz des internen Netzes) erläutert', points: 1 },
      { criterion: 'Zwei passende Beispiele genannt (z. B. Webserver, Mailserver)', points: 1 },
    ],
    explanation: 'Die DMZ trennt exponierte Dienste vom internen Netz; Firewalls erlauben von außen nur den Zugriff auf die DMZ, von der DMZ ins LAN nur das Nötigste.',
  },
  {
    id: 'nw-ft-004',
    section: 'netzwerk',
    topic: 'nat',
    type: 'free_text',
    title: 'Network Address Translation',
    scenario: 'Das Café Bohnenglück hat vom Provider nur eine öffentliche IPv4-Adresse erhalten, es sollen aber 30 Geräte gleichzeitig ins Internet.',
    text: 'Erläutern Sie, wie **NAT** (bzw. PAT/Masquerading) es ermöglicht, dass alle 30 Geräte über die eine öffentliche Adresse ins Internet gelangen. Nennen Sie einen Vorteil und einen Nachteil von NAT.',
    points: 3,
    difficulty: 3,
    solution:
      'Funktionsweise: Die Geräte nutzen private IP-Adressen (z. B. 192.168.x.x). Der Router ersetzt beim Verlassen des Netzes die private Quelladresse durch seine öffentliche Adresse und merkt sich in einer NAT-Tabelle die Zuordnung, wobei er jeder Verbindung einen eigenen Quellport zuweist (PAT). Antworten aus dem Internet werden anhand des Ports wieder der richtigen privaten Adresse zugeordnet.\n\nVorteil: Eine öffentliche Adresse genügt für viele Geräte (spart IPv4-Adressen); interne Struktur bleibt verborgen, unaufgeforderte Verbindungen von außen erreichen die Clients nicht.\nNachteil: Von außen initiierte Verbindungen (z. B. Server im LAN, Peer-to-Peer, VoIP) benötigen Portweiterleitungen; Ende-zu-Ende-Prinzip wird verletzt; zusätzlicher Verwaltungsaufwand im Router.',
    rubric: [
      { criterion: 'Adressumsetzung privat → öffentlich mit NAT-Tabelle und Portzuordnung korrekt erläutert', points: 2 },
      { criterion: 'Je ein korrekter Vorteil und Nachteil genannt', points: 1 },
    ],
    explanation: 'PAT unterscheidet die Verbindungen der internen Hosts über Portnummern und ist der Grund, warum IPv4 trotz Adressknappheit weiter funktioniert.',
  },
  {
    id: 'nw-mc-008',
    section: 'netzwerk',
    topic: 'domaene',
    type: 'multiple_choice',
    title: 'Arbeitsplatz-PC in eine Domäne aufnehmen',
    scenario: 'Für die neue Mitarbeiterin der Kanzlei Bergmann & Partner wurde ein Windows-PC installiert. Er soll in die Active-Directory-Domäne der Kanzlei aufgenommen werden.',
    text: 'Welche Aussagen zum Domänenbeitritt treffen zu? (Mehrere Antworten möglich)',
    points: 3,
    difficulty: 2,
    options: [
      { id: 'a', text: 'Der PC muss den Domänencontroller über DNS auflösen können; der DNS-Server des Clients sollte daher auf den Domänencontroller zeigen.' },
      { id: 'b', text: 'Für den Beitritt werden die Anmeldedaten eines Kontos benötigt, das zum Hinzufügen von Computern zur Domäne berechtigt ist.' },
      { id: 'c', text: 'Nach dem Beitritt können sich Benutzer mit zentral verwalteten Domänenkonten anmelden, und Gruppenrichtlinien werden auf den PC angewendet.' },
      { id: 'd', text: 'Der PC benötigt zwingend eine öffentliche IPv4-Adresse.' },
      { id: 'e', text: 'Gruppenrichtlinien wirken ausschließlich auf lokale Benutzerkonten des PCs.' },
    ],
    correct: ['a', 'b', 'c'],
    multi: true,
    explanation: 'Der Domänenbeitritt setzt Namensauflösung des Domänencontrollers und ein berechtigtes Konto voraus. Danach greifen zentrale Benutzerverwaltung und Gruppenrichtlinien; private IP-Adressen genügen.',
  },
];
