/**
 * Handlungsschritt 3: IT-Sicherheit und Datenschutz umsetzen.
 * ID-Präfix: si
 */
import type { Question } from '../../../shared/types.js';

export const questions: Question[] = [
  /* =====================================================================
   * FREITEXT (4 Punkte)
   * ===================================================================== */
  {
    id: 'si-ft-001',
    section: 'sicherheit',
    topic: 'schutzziele',
    type: 'free_text',
    title: 'Schutzziele der Informationssicherheit',
    scenario: 'Die Arztpraxis Dr. Keller speichert Patientendaten auf einem lokalen Server.',
    text: 'Nennen Sie die drei klassischen Schutzziele der Informationssicherheit und erläutern Sie jedes Ziel anhand eines Beispiels aus der Arztpraxis.',
    points: 4,
    difficulty: 1,
    solution:
      'Vertraulichkeit: Nur befugte Personen dürfen Patientendaten lesen (z. B. Zugriffsrechte, Verschlüsselung der Festplatte).\nIntegrität: Daten dürfen nicht unbemerkt verändert werden (z. B. Prüfsummen, Änderungsprotokoll in der Praxissoftware).\nVerfügbarkeit: Daten müssen bei Bedarf zugänglich sein (z. B. Backup, USV, redundante Hardware, damit die Sprechstunde nicht ausfällt).',
    rubric: [
      { criterion: 'Drei Schutzziele korrekt genannt (Vertraulichkeit, Integrität, Verfügbarkeit)', points: 1.5 },
      { criterion: 'Jedes Ziel fachlich korrekt erläutert', points: 1.5 },
      { criterion: 'Passende Beispiele aus dem Praxiskontext', points: 1 },
    ],
    explanation: 'Die CIA-Triade (Confidentiality, Integrity, Availability) ist Grundlage jeder Schutzbedarfsanalyse. Ergänzend werden häufig Authentizität und Nichtabstreitbarkeit genannt.',
  },
  {
    id: 'si-ft-002',
    section: 'sicherheit',
    topic: 'tom',
    type: 'free_text',
    title: 'Technische und organisatorische Maßnahmen',
    scenario: 'Die Steuerkanzlei Winter & Kollegen verarbeitet Mandantendaten und muss gegenüber der Aufsichtsbehörde geeignete Maßnahmen nach Art. 32 DSGVO nachweisen.',
    text: 'Nennen Sie **zwei technische** und **zwei organisatorische** Maßnahmen (TOM), mit denen die Kanzlei die Sicherheit der Mandantendaten erhöhen kann. Erläutern Sie zu jeder Maßnahme kurz, welchen Beitrag sie zum Schutz der Daten leistet.',
    points: 4,
    difficulty: 2,
    solution:
      'Technische Maßnahmen (Beispiele):\n- Verschlüsselung der Notebook-Festplatten: Bei Verlust oder Diebstahl bleiben die Daten vertraulich.\n- Firewall und aktueller Virenschutz: Abwehr von Angriffen und Schadsoftware aus dem Netz.\n- Rollenbasierte Zugriffsrechte / Mehrfaktor-Authentifizierung: Nur berechtigte Personen erhalten Zugriff.\n- Regelmäßige Datensicherung: Wiederherstellbarkeit nach Datenverlust.\n\nOrganisatorische Maßnahmen (Beispiele):\n- Schulung und Sensibilisierung der Mitarbeitenden (z. B. Phishing): Menschliches Fehlverhalten wird reduziert.\n- Passwortrichtlinie und Clean-Desk-Policy: Vorgaben zu sicheren Passwörtern und zum Umgang mit Unterlagen.\n- Vier-Augen-Prinzip und Berechtigungskonzept: Vergabe von Rechten wird kontrolliert und dokumentiert.\n- Besucherregelung / Zutrittskontrolle: Unbefugte gelangen nicht an Arbeitsplätze und Server.',
    rubric: [
      { criterion: 'Zwei korrekte technische Maßnahmen genannt', points: 1 },
      { criterion: 'Zwei korrekte organisatorische Maßnahmen genannt', points: 1 },
      { criterion: 'Beitrag jeder Maßnahme zum Datenschutz/zur Sicherheit nachvollziehbar erläutert', points: 2 },
    ],
    explanation: 'Technische Maßnahmen wirken über Hard- oder Software (Verschlüsselung, Firewall), organisatorische über Regeln, Prozesse und Menschen (Richtlinien, Schulung). Art. 32 DSGVO fordert beides.',
  },
  {
    id: 'si-ft-003',
    section: 'sicherheit',
    topic: 'backup',
    type: 'free_text',
    title: '3-2-1-Regel der Datensicherung',
    scenario: 'Der Online-Shop "Bergsport Nord" sichert seine Datenbank täglich auf eine externe USB-Festplatte, die dauerhaft am Server angeschlossen ist und im Serverraum liegt.',
    text: 'Erläutern Sie die **3-2-1-Regel** der Datensicherung und begründen Sie anhand von zwei konkreten Bedrohungen, warum das aktuelle Sicherungskonzept des Shops nicht ausreichend ist.',
    points: 4,
    difficulty: 2,
    solution:
      '3-2-1-Regel: Es sollen mindestens **3** Kopien der Daten existieren (Original + 2 Sicherungen), auf **2** unterschiedlichen Speichermedien/-technologien (z. B. Festplatte und Band oder Cloud), davon **1** Kopie außer Haus (räumlich getrennt, offline bzw. getrennt vom Netz).\n\nWarum das Konzept nicht ausreicht:\n- Ransomware/Schadsoftware: Da die USB-Platte dauerhaft angeschlossen ist, wird sie bei einem Angriff mitverschlüsselt bzw. mitgelöscht – die Sicherung ist wertlos.\n- Brand, Wasserschaden, Diebstahl, Überspannung: Server und Sicherung befinden sich im selben Raum und gehen gleichzeitig verloren; es gibt keine räumlich getrennte Kopie.\n- Zudem existiert nur ein Sicherungsmedium (keine zwei Technologien).',
    rubric: [
      { criterion: '3-2-1-Regel vollständig und korrekt erläutert (3 Kopien, 2 Medien, 1 extern)', points: 2 },
      { criterion: 'Zwei konkrete Bedrohungen genannt (z. B. Ransomware, Brand/Diebstahl) und auf das Konzept bezogen', points: 2 },
    ],
    explanation: 'Eine ständig verbundene Sicherung schützt nicht vor Ransomware; eine Sicherung am selben Ort nicht vor Elementarschäden. Die 3-2-1-Regel adressiert beide Risiken.',
  },
  {
    id: 'si-ft-004',
    section: 'sicherheit',
    topic: 'social-engineering',
    type: 'free_text',
    title: 'Phishing erkennen und abwehren',
    scenario: 'Ein Mitarbeiter der Spedition Hellwig Logistik GmbH erhält eine E-Mail, angeblich von der Geschäftsführung, mit der Aufforderung, dringend über einen Link seine Zugangsdaten zu bestätigen.',
    text: 'a) Nennen Sie **drei Merkmale**, an denen der Mitarbeiter eine Phishing-Mail erkennen kann.\nb) Nennen und erläutern Sie **zwei Maßnahmen**, mit denen das Unternehmen den Schaden durch Phishing-Angriffe verringern kann.',
    points: 4,
    difficulty: 1,
    solution:
      'a) Merkmale (drei genügen): Absenderadresse weicht von der echten Domain ab (z. B. Tippfehler, Freemail-Adresse); Link-Ziel führt beim Überfahren mit der Maus auf eine fremde Domain; Zeitdruck/Drohungen ("sofort", "sonst Sperrung"); Aufforderung zur Eingabe von Zugangsdaten oder Zahlungen; unpersönliche Anrede, Rechtschreib-/Grammatikfehler; unerwartete Anhänge; ungewöhnlicher Kommunikationsweg für dieses Anliegen.\n\nb) Maßnahmen (zwei genügen):\n- Schulung/Sensibilisierung der Mitarbeitenden, ggf. mit simulierten Phishing-Kampagnen: Angriffe werden erkannt und gemeldet.\n- Mehrfaktor-Authentifizierung: Ein erbeutetes Passwort allein genügt nicht für den Zugriff.\n- Spam-/Phishing-Filter, Kennzeichnung externer E-Mails, SPF/DKIM/DMARC: Verdächtige Mails werden ausgefiltert oder markiert.\n- Klare Meldeprozesse und Verfahren (z. B. Zahlungsfreigabe nur nach Rückruf, Vier-Augen-Prinzip).',
    rubric: [
      { criterion: 'Drei korrekte Erkennungsmerkmale genannt', points: 2 },
      { criterion: 'Zwei sinnvolle Maßnahmen genannt und deren Wirkung erläutert', points: 2 },
    ],
    explanation: 'Phishing ist Social Engineering: Der Angriff zielt auf den Menschen. Technische Filter und MFA begrenzen den Schaden, Schulung senkt die Erfolgsquote.',
  },
  {
    id: 'si-ft-005',
    section: 'sicherheit',
    topic: 'verschluesselung',
    type: 'free_text',
    title: 'Symmetrische und asymmetrische Verschlüsselung',
    scenario: 'Die Ingenieurgesellschaft Falkenberg Planung möchte Konstruktionszeichnungen verschlüsselt an einen neuen Geschäftspartner übermitteln, mit dem bisher kein gemeinsamer Schlüssel vereinbart wurde.',
    text: 'Erläutern Sie den Unterschied zwischen **symmetrischer** und **asymmetrischer** Verschlüsselung. Begründen Sie, welches Verfahren sich für den ersten Kontakt mit dem Geschäftspartner eignet, und erklären Sie, warum in der Praxis (z. B. bei TLS) beide Verfahren kombiniert werden.',
    points: 4,
    difficulty: 3,
    solution:
      'Symmetrisch: Ein gemeinsamer geheimer Schlüssel wird zum Ver- und Entschlüsseln verwendet (z. B. AES). Schnell, aber der Schlüssel muss vorher sicher ausgetauscht werden.\nAsymmetrisch: Schlüsselpaar aus öffentlichem und privatem Schlüssel (z. B. RSA). Mit dem öffentlichen Schlüssel des Empfängers wird verschlüsselt, nur der Empfänger kann mit seinem privaten Schlüssel entschlüsseln. Kein geheimer Schlüsselaustausch nötig, aber deutlich rechenaufwendiger.\n\nErster Kontakt: Asymmetrisches Verfahren, da noch kein gemeinsamer Schlüssel existiert – der Partner stellt seinen öffentlichen Schlüssel bereit (z. B. über ein Zertifikat).\n\nKombination (hybrid, z. B. TLS): Über das asymmetrische Verfahren wird ein zufälliger symmetrischer Sitzungsschlüssel sicher ausgetauscht; die eigentlichen Nutzdaten werden dann symmetrisch verschlüsselt, weil das deutlich schneller ist.',
    rubric: [
      { criterion: 'Symmetrische Verschlüsselung korrekt erklärt (ein gemeinsamer geheimer Schlüssel)', points: 1 },
      { criterion: 'Asymmetrische Verschlüsselung korrekt erklärt (öffentlicher/privater Schlüssel)', points: 1 },
      { criterion: 'Begründete Wahl des asymmetrischen Verfahrens für den ersten Kontakt', points: 1 },
      { criterion: 'Hybridverfahren erklärt (Sitzungsschlüssel asymmetrisch austauschen, Daten symmetrisch verschlüsseln)', points: 1 },
    ],
    explanation: 'Asymmetrische Verfahren lösen das Schlüsselverteilungsproblem, symmetrische sind schnell – deshalb tauscht TLS einen symmetrischen Sitzungsschlüssel asymmetrisch aus.',
  },

  /* =====================================================================
   * ZUORDNUNG (4 Punkte)
   * ===================================================================== */
  {
    id: 'si-ma-001',
    section: 'sicherheit',
    topic: 'malware',
    type: 'matching',
    title: 'Arten von Schadsoftware',
    scenario: 'Nach einem Sicherheitsvorfall bei der Möbelmanufaktur Holzwerk Lindner sollen die Mitarbeitenden in einer Schulung verschiedene Arten von Schadsoftware unterscheiden lernen.',
    text: 'Ordnen Sie jeder Beschreibung die passende Art von Schadsoftware zu.',
    points: 4,
    difficulty: 1,
    left: [
      { id: 'l1', text: 'Verschlüsselt Dateien des Opfers und fordert Lösegeld für die Entschlüsselung' },
      { id: 'l2', text: 'Tarnt sich als nützliches Programm und führt im Hintergrund schädliche Funktionen aus' },
      { id: 'l3', text: 'Verbreitet sich selbstständig über das Netzwerk, ohne dass ein Benutzer eine Datei ausführen muss' },
      { id: 'l4', text: 'Hängt sich an ein Wirtsprogramm an und wird bei dessen Ausführung aktiv und verbreitet' },
      { id: 'l5', text: 'Zeichnet heimlich Tastatureingaben auf und sendet sie an den Angreifer' },
    ],
    right: [
      { id: 'r1', text: 'Virus' },
      { id: 'r2', text: 'Wurm' },
      { id: 'r3', text: 'Trojaner' },
      { id: 'r4', text: 'Ransomware' },
      { id: 'r5', text: 'Keylogger (Spyware)' },
      { id: 'r6', text: 'Adware' },
      { id: 'r7', text: 'Rootkit' },
    ],
    pairs: { l1: 'r4', l2: 'r3', l3: 'r2', l4: 'r1', l5: 'r5' },
    explanation: 'Viren brauchen ein Wirtsprogramm, Würmer verbreiten sich selbstständig, Trojaner täuschen Nützlichkeit vor, Ransomware erpresst, Spyware spioniert aus.',
  },
  {
    id: 'si-ma-002',
    section: 'sicherheit',
    topic: 'dsgvo',
    type: 'matching',
    title: 'Rollen und Begriffe der DSGVO',
    scenario: 'Die Fitnessstudio-Kette VitalPark nutzt für die Mitgliederverwaltung eine Cloud-Software eines externen Anbieters. Sie sollen die datenschutzrechtlichen Rollen dokumentieren.',
    text: 'Ordnen Sie jeder Beschreibung den passenden Begriff aus der DSGVO zu.',
    points: 4,
    difficulty: 2,
    left: [
      { id: 'l1', text: 'Entscheidet über Zwecke und Mittel der Verarbeitung (hier: VitalPark)' },
      { id: 'l2', text: 'Verarbeitet personenbezogene Daten weisungsgebunden im Auftrag (hier: der Cloud-Anbieter)' },
      { id: 'l3', text: 'Natürliche Person, deren Daten verarbeitet werden (hier: das Mitglied)' },
      { id: 'l4', text: 'Unabhängige staatliche Stelle, die die Einhaltung des Datenschutzes überwacht' },
      { id: 'l5', text: 'Berät das Unternehmen intern zum Datenschutz und ist Ansprechpartner für Betroffene' },
    ],
    right: [
      { id: 'r1', text: 'Verantwortlicher' },
      { id: 'r2', text: 'Auftragsverarbeiter' },
      { id: 'r3', text: 'Betroffene Person' },
      { id: 'r4', text: 'Aufsichtsbehörde' },
      { id: 'r5', text: 'Datenschutzbeauftragter' },
      { id: 'r6', text: 'Empfänger' },
      { id: 'r7', text: 'Datenschutz-Folgenabschätzung' },
    ],
    pairs: { l1: 'r1', l2: 'r2', l3: 'r3', l4: 'r4', l5: 'r5' },
    explanation: 'Der Verantwortliche bestimmt Zweck und Mittel; der Auftragsverarbeiter handelt auf Weisung (Art. 28 DSGVO). Die Aufsichtsbehörde ist die externe Kontrollinstanz, der Datenschutzbeauftragte die interne Beratung.',
  },
  {
    id: 'si-ma-003',
    section: 'sicherheit',
    topic: 'netzwerksicherheit',
    type: 'matching',
    title: 'Sicherheitskomponenten und ihre Aufgaben',
    scenario: 'Für das neue Rechenzentrum der Versicherungsagentur Sturm & Berg sollen die geplanten Sicherheitskomponenten in einem Konzept beschrieben werden.',
    text: 'Ordnen Sie jeder Aufgabe die passende Komponente zu.',
    points: 4,
    difficulty: 2,
    left: [
      { id: 'l1', text: 'Filtert den Netzwerkverkehr anhand von Regeln (z. B. Quell-/Zieladresse, Port) und blockiert unerlaubte Verbindungen' },
      { id: 'l2', text: 'Überwacht den Datenverkehr, erkennt Angriffsmuster und löst einen Alarm aus, greift aber nicht selbst ein' },
      { id: 'l3', text: 'Erkennt Angriffsmuster und blockiert den betroffenen Datenverkehr automatisch' },
      { id: 'l4', text: 'Überbrückt Stromausfälle und ermöglicht das geordnete Herunterfahren der Server' },
      { id: 'l5', text: 'Baut einen verschlüsselten Tunnel über ein unsicheres Netz auf, z. B. für Homeoffice-Zugriffe' },
    ],
    right: [
      { id: 'r1', text: 'Firewall' },
      { id: 'r2', text: 'IDS (Intrusion Detection System)' },
      { id: 'r3', text: 'IPS (Intrusion Prevention System)' },
      { id: 'r4', text: 'USV' },
      { id: 'r5', text: 'VPN-Gateway' },
      { id: 'r6', text: 'Load Balancer' },
      { id: 'r7', text: 'Proxy-Server' },
    ],
    pairs: { l1: 'r1', l2: 'r2', l3: 'r3', l4: 'r4', l5: 'r5' },
    explanation: 'Der wesentliche Unterschied zwischen IDS und IPS: Das IDS meldet nur, das IPS greift aktiv ein. Die USV sichert die Verfügbarkeit bei Stromausfall.',
  },
  {
    id: 'si-ma-004',
    section: 'sicherheit',
    topic: 'kryptographie',
    type: 'matching',
    title: 'Kryptographische Verfahren',
    scenario: 'Die Softwarefirma CodeCraft GmbH führt ein Sicherheitskonzept für den Austausch von Vertragsdokumenten ein.',
    text: 'Ordnen Sie jeder Beschreibung das passende kryptographische Verfahren bzw. Hilfsmittel zu.',
    points: 4,
    difficulty: 3,
    left: [
      { id: 'l1', text: 'Erzeugt aus beliebig langen Daten einen Wert fester Länge; aus dem Wert lassen sich die Daten nicht zurückrechnen' },
      { id: 'l2', text: 'Der Absender verschlüsselt den Hashwert eines Dokuments mit seinem privaten Schlüssel; jeder kann die Echtheit mit dem öffentlichen Schlüssel prüfen' },
      { id: 'l3', text: 'Ver- und Entschlüsselung mit demselben geheimen Schlüssel, z. B. AES' },
      { id: 'l4', text: 'Bestätigt durch eine vertrauenswürdige Stelle, dass ein öffentlicher Schlüssel zu einer bestimmten Person oder Domain gehört' },
      { id: 'l5', text: 'Verschlüsselung mit dem öffentlichen, Entschlüsselung mit dem privaten Schlüssel, z. B. RSA' },
    ],
    right: [
      { id: 'r1', text: 'Hashfunktion (z. B. SHA-256)' },
      { id: 'r2', text: 'Digitale Signatur' },
      { id: 'r3', text: 'Symmetrische Verschlüsselung' },
      { id: 'r4', text: 'Digitales Zertifikat (X.509)' },
      { id: 'r5', text: 'Asymmetrische Verschlüsselung' },
      { id: 'r6', text: 'Steganographie' },
      { id: 'r7', text: 'Base64-Kodierung' },
    ],
    pairs: { l1: 'r1', l2: 'r2', l3: 'r3', l4: 'r4', l5: 'r5' },
    explanation: 'Hashes sichern Integrität, Signaturen zusätzlich Authentizität und Nichtabstreitbarkeit; Zertifikate binden öffentliche Schlüssel an Identitäten (PKI). Base64 ist keine Verschlüsselung.',
  },

  /* =====================================================================
   * RECHENAUFGABEN (5 Punkte)
   * ===================================================================== */
  {
    id: 'si-ca-001',
    section: 'sicherheit',
    topic: 'backup',
    type: 'calculation',
    title: 'Inkrementelle und differenzielle Sicherung im Vergleich',
    scenario: 'Die Werbeagentur Pixelwerk GmbH sichert ihren Dateiserver auf ein NAS. Der Datenbestand beträgt 800 GB; pro Arbeitstag ändern sich bzw. entstehen neu ca. 5 % des Bestands.',
    text: 'Jeweils in der Nacht von Sonntag auf Montag wird eine **Vollsicherung** erstellt. In den Nächten von Montag bis Freitag (5 Nächte) folgt jeweils eine Teilsicherung. Das tägliche Änderungsvolumen beträgt 5 % von 800 GB. Es gilt 1 GB = 1000 MB.\n\na) Berechnen Sie das Datenvolumen der fünf Teilsicherungen zusammen (ohne Vollsicherung) bei **inkrementeller** Sicherung und bei **differenzieller** Sicherung.\nb) Am Samstagvormittag fällt der Server aus. Wie viele Sicherungssätze müssen bei inkrementeller bzw. bei differenzieller Sicherung jeweils eingespielt werden, um den Stand von Freitagnacht wiederherzustellen?\nc) Wie lange dauert die differenzielle Sicherung in der Freitagnacht bei einer effektiven Übertragungsrate von 100 MB/s? Geben Sie das Ergebnis in Minuten an.\n\nGeben Sie den vollständigen Lösungsweg an.',
    points: 5,
    difficulty: 2,
    solution:
      'Tägliches Änderungsvolumen: 5 % von 800 GB = 40 GB\n\na) Inkrementell: jede Teilsicherung enthält nur die Änderungen seit der letzten Sicherung → 5 × 40 GB = **200 GB**\nDifferenziell: jede Teilsicherung enthält alle Änderungen seit der Vollsicherung → 40 + 80 + 120 + 160 + 200 GB = **600 GB**\n\nb) Inkrementell: Vollsicherung + 5 inkrementelle Sicherungen (Mo, Di, Mi, Do, Fr) = **6 Sicherungssätze**\nDifferenziell: Vollsicherung + letzte differenzielle Sicherung (Fr) = **2 Sicherungssätze**\n\nc) Differenzielle Sicherung Freitag: 200 GB = 200.000 MB\nDauer = 200.000 MB / 100 MB/s = 2.000 s = **33,3 min** (≈ 33 min 20 s)',
    expected: [
      { label: 'Volumen inkrementell (Mo–Fr)', value: 200, unit: 'GB', tolerance: 0.5 },
      { label: 'Volumen differenziell (Mo–Fr)', value: 600, unit: 'GB', tolerance: 0.5 },
      { label: 'Sicherungssätze inkrementell', value: 6, tolerance: 0 },
      { label: 'Sicherungssätze differenziell', value: 2, tolerance: 0 },
      { label: 'Dauer differenzielle Sicherung Freitag', value: 33.3, unit: 'min', tolerance: 0.2 },
    ],
    rubric: [
      { criterion: 'Änderungsvolumen 40 GB/Tag und inkrementelles Gesamtvolumen 200 GB korrekt', points: 1.5 },
      { criterion: 'Differenzielles Gesamtvolumen 600 GB mit nachvollziehbarer Summenbildung', points: 1.5 },
      { criterion: 'Anzahl der Sicherungssätze für die Wiederherstellung (6 bzw. 2) korrekt', points: 1 },
      { criterion: 'Sicherungsdauer 2.000 s ≈ 33,3 min mit korrekter Einheitenumrechnung', points: 1 },
    ],
    explanation: 'Inkrementell spart Speicherplatz und Sicherungszeit, verlangt aber bei der Wiederherstellung die komplette Kette; differenziell braucht mehr Platz, aber nur zwei Sätze zum Restore.',
  },
  {
    id: 'si-ca-002',
    section: 'sicherheit',
    topic: 'backup',
    type: 'calculation',
    title: 'Kapazitätsplanung für die Datensicherung auf ein NAS',
    scenario:
      'Die Steuerberatung Feldmann & Kollegen sichert ihren Dateiserver auf ein NAS im Serverraum. Der zu sichernde Datenbestand beträgt 1,2 TB. Sonntags wird eine Vollsicherung erstellt, Montag bis Freitag jeweils eine inkrementelle Sicherung mit durchschnittlich 4 % des Datenbestands. Alle Sicherungen werden 4 Wochen aufbewahrt. Das NAS bietet 12 TB nutzbare Kapazität. Rechnen Sie dezimal (1 TB = 1.000 GB).',
    text:
      'a) Berechnen Sie das Sicherungsvolumen einer Woche in GB.\nb) Berechnen Sie den Speicherbedarf für die Aufbewahrungsdauer von 4 Wochen in TB.\nc) Um wie viele zusätzliche Wochen könnte die Aufbewahrungsdauer verlängert werden, ohne dass das NAS voll läuft?\nd) Die Vollsicherung läuft über ein Gigabit-Netz (1 Gbit/s), von dem netto 80 % nutzbar sind. Wie lange dauert die Übertragung der Vollsicherung? Geben Sie das Ergebnis in Stunden und Minuten an.\n\nGeben Sie den vollständigen Lösungsweg an.',
    points: 5,
    difficulty: 2,
    solution:
      'a) Vollsicherung 1.200 GB; inkrementell 4 % × 1.200 GB = 48 GB je Tag; 5 × 48 GB = 240 GB\nWochenvolumen = 1.200 GB + 240 GB = **1.440 GB**\n\nb) 4 Wochen × 1.440 GB = 5.760 GB = **5,76 TB**\n\nc) Freie Kapazität: 12 TB − 5,76 TB = 6,24 TB\n6,24 TB ÷ 1,44 TB je Woche = 4,33 → **4 zusätzliche Wochen** (insgesamt 8 Wochen)\n\nd) Datenmenge: 1.200 GB = 1.200 × 10^9 Byte × 8 = 9,6 × 10^12 Bit\nNettodatenrate: 0,8 × 10^9 Bit/s = 8 × 10^8 Bit/s\nDauer = 9,6 × 10^12 ÷ 8 × 10^8 = 12.000 s = 200 min = **3 h 20 min**',
    expected: [
      { label: 'Wochenvolumen', value: 1440, unit: 'GB', tolerance: 1 },
      { label: 'Bedarf 4 Wochen', value: 5.76, unit: 'TB', tolerance: 0.01 },
      { label: 'Zusätzliche Wochen', value: 4, tolerance: 0 },
      { label: 'Übertragungsdauer', value: 200, unit: 'min', tolerance: 1 },
    ],
    rubric: [
      { criterion: 'Wochenvolumen korrekt (1.440 GB) mit Rechenweg', points: 1 },
      { criterion: 'Bedarf für 4 Wochen korrekt (5,76 TB)', points: 1 },
      { criterion: 'Zusätzliche Wochen korrekt hergeleitet (4 Wochen, sinnvoll abgerundet)', points: 1.5 },
      { criterion: 'Übertragungsdauer korrekt (12.000 s = 3 h 20 min) inkl. Bit/Byte-Umrechnung und Nettodatenrate', points: 1.5 },
    ],
    explanation: 'Bei Kapazitätsplanungen müssen Vollsicherungen und alle inkrementellen Sicherungen der Aufbewahrungsdauer addiert werden. Bei der Übertragungsdauer ist auf Byte→Bit und den nutzbaren Anteil der Bandbreite zu achten.',
  },
  {
    id: 'si-ca-003',
    section: 'sicherheit',
    topic: 'verfuegbarkeit',
    type: 'calculation',
    title: 'Verfügbarkeit und Ausfallzeit',
    scenario: 'Die Reederei Nordwind Shipping hat mit ihrem Hosting-Anbieter für das Buchungssystem eine Verfügbarkeit von 99,9 % pro Jahr vereinbart (SLA).',
    text: 'a) Berechnen Sie die maximal zulässige Ausfallzeit pro Jahr (365 Tage) in Minuten und in Stunden.\nb) Im vergangenen Jahr gab es zwei Ausfälle: einmal 3 Stunden und einmal 90 Minuten. Berechnen Sie die tatsächlich erreichte Verfügbarkeit in Prozent (auf zwei Nachkommastellen).\nc) Wurde das SLA eingehalten? Begründen Sie mit Zahlen.\n\nGeben Sie den vollständigen Lösungsweg an.',
    points: 5,
    difficulty: 2,
    solution:
      'a) Minuten pro Jahr: 365 × 24 × 60 = 525.600 min\nZulässige Ausfallzeit: 100 % − 99,9 % = 0,1 % → 525.600 min × 0,001 = **525,6 min** = **8,76 h**\n\nb) Tatsächliche Ausfallzeit: 3 h + 90 min = 180 min + 90 min = 270 min\nVerfügbarkeit = (525.600 − 270) / 525.600 × 100 % = 525.330 / 525.600 × 100 % ≈ **99,95 %**\n\nc) Ja, das SLA wurde eingehalten: 270 min Ausfall < 525,6 min zulässig bzw. 99,95 % ≥ 99,9 %.',
    expected: [
      { label: 'Zulässige Ausfallzeit pro Jahr', value: 525.6, unit: 'min', tolerance: 0.5 },
      { label: 'Zulässige Ausfallzeit pro Jahr', value: 8.76, unit: 'h', tolerance: 0.01 },
      { label: 'Tatsächliche Verfügbarkeit', value: 99.95, unit: '%', tolerance: 0.01 },
    ],
    rubric: [
      { criterion: 'Minuten pro Jahr (525.600) und zulässige Ausfallzeit 525,6 min / 8,76 h korrekt', points: 2 },
      { criterion: 'Tatsächliche Ausfallzeit 270 min und Verfügbarkeit ≈ 99,95 % korrekt berechnet', points: 2 },
      { criterion: 'SLA-Bewertung korrekt begründet (eingehalten)', points: 1 },
    ],
    explanation: 'Verfügbarkeit = (Gesamtzeit − Ausfallzeit) / Gesamtzeit. "Drei Neunen" (99,9 %) entsprechen knapp 8,8 Stunden Ausfall im Jahr.',
  },
  {
    id: 'si-ca-004',
    section: 'sicherheit',
    topic: 'backup',
    type: 'calculation',
    title: 'Generationenprinzip: Anzahl der Bänder',
    scenario: 'Die Druckerei Farbenreich GmbH sichert ihre Auftragsdaten (Vollsicherung: 1,2 TB) nach dem Generationenprinzip (Großvater-Vater-Sohn) auf LTO-Bänder.',
    text: 'Das Sicherungsschema ist wie folgt festgelegt:\n- **Sohn**: tägliche Sicherung Montag bis Donnerstag; die Bänder werden in der Folgewoche wieder überschrieben.\n- **Vater**: Sicherung an jedem Freitag; Aufbewahrung 5 Wochen, danach Wiederverwendung.\n- **Großvater**: Sicherung am letzten Arbeitstag jedes Monats (zusätzliches Band); Aufbewahrung 12 Monate, danach Wiederverwendung.\n\na) Berechnen Sie, wie viele Bänder für dieses Schema insgesamt benötigt werden.\nb) Ein Band kostet 40 €. Berechnen Sie die Anschaffungskosten für alle Bänder.\nc) Die Vollsicherung von 1,2 TB wird mit 160 MB/s auf das Band geschrieben (1 TB = 10^6 MB). Berechnen Sie die Dauer der Sicherung in Stunden und Minuten.\n\nGeben Sie den vollständigen Lösungsweg an.',
    points: 5,
    difficulty: 2,
    solution:
      'a) Sohn: Mo, Di, Mi, Do → 4 Bänder\nVater: 5 Freitage aufbewahren → 5 Bänder\nGroßvater: 12 Monatsbänder → 12 Bänder\nGesamt: 4 + 5 + 12 = **21 Bänder**\n\nb) 21 × 40 € = **840 €**\n\nc) 1,2 TB = 1.200.000 MB\nDauer = 1.200.000 MB / 160 MB/s = 7.500 s\n7.500 s / 60 = 125 min = **2 h 5 min**',
    expected: [
      { label: 'Anzahl Bänder', value: 21, tolerance: 0 },
      { label: 'Kosten', value: 840, unit: '€', tolerance: 0 },
      { label: 'Dauer Vollsicherung', value: 125, unit: 'min', tolerance: 0.5 },
    ],
    rubric: [
      { criterion: 'Sohn- (4) und Vater-Bänder (5) korrekt bestimmt', points: 1.5 },
      { criterion: 'Großvater-Bänder (12) und Gesamtzahl 21 korrekt', points: 1.5 },
      { criterion: 'Kosten 840 € korrekt', points: 1 },
      { criterion: 'Dauer 7.500 s = 2 h 5 min mit korrekter Umrechnung TB → MB', points: 1 },
    ],
    explanation: 'Das Generationenprinzip kombiniert kurze (täglich), mittlere (wöchentlich) und lange (monatlich) Aufbewahrungsfristen und erlaubt so die Rückkehr zu älteren Datenständen.',
  },
  {
    id: 'si-ca-005',
    section: 'sicherheit',
    topic: 'passwoerter',
    type: 'calculation',
    title: 'Passwortkombinationen und Brute-Force-Dauer',
    scenario: 'Die IT-Abteilung der Brauerei Hopfenquell möchte ihre Passwortrichtlinie überarbeiten und die Sicherheit verschiedener Passwortlängen vergleichen.',
    text: 'Ein Angreifer kann 10^10 (10 Milliarden) Passwörter pro Sekunde durchprobieren.\n\na) Berechnen Sie die Anzahl möglicher Passwörter bei **8 Zeichen** aus einem Zeichenvorrat von 62 Zeichen (a–z, A–Z, 0–9). Geben Sie das Ergebnis als Zehnerpotenz mit zwei Nachkommastellen an (z. B. 3,45 × 10^12).\nb) Wie lange dauert es im ungünstigsten Fall (alle Kombinationen), dieses Passwort per Brute-Force zu finden? Geben Sie das Ergebnis in Stunden an.\nc) Die neue Richtlinie fordert **12 Zeichen** aus einem Vorrat von 95 Zeichen (inkl. Sonderzeichen). Berechnen Sie die Anzahl der Kombinationen als Zehnerpotenz und die Brute-Force-Dauer im ungünstigsten Fall in Jahren (1 Jahr = 365 Tage).\n\nGeben Sie den vollständigen Lösungsweg an.',
    points: 5,
    difficulty: 3,
    solution:
      'a) Kombinationen = Zeichenvorrat ^ Länge = 62^8 = 218.340.105.584.896 ≈ **2,18 × 10^14**\n\nb) Dauer = 2,18 × 10^14 / 10^10 = 21.834 s\n21.834 s / 3.600 s/h ≈ **6,07 h** (rund 6 Stunden)\n\nc) 95^12 ≈ **5,40 × 10^23** Kombinationen\nDauer = 5,40 × 10^23 / 10^10 = 5,40 × 10^13 s\nSekunden pro Jahr: 365 × 24 × 3.600 = 31.536.000 s ≈ 3,15 × 10^7 s\n5,40 × 10^13 / 3,15 × 10^7 ≈ **1,71 × 10^6 Jahre** (rund 1,7 Millionen Jahre)',
    expected: [
      { label: 'Kombinationen 62^8 (× 10^14)', value: 2.18, tolerance: 0.01 },
      { label: 'Brute-Force-Dauer 8 Zeichen', value: 6.07, unit: 'h', tolerance: 0.05 },
      { label: 'Kombinationen 95^12 (× 10^23)', value: 5.4, tolerance: 0.02 },
      { label: 'Brute-Force-Dauer 12 Zeichen (× 10^6 Jahre)', value: 1.71, tolerance: 0.03 },
    ],
    rubric: [
      { criterion: 'Ansatz Zeichenvorrat^Länge und 62^8 ≈ 2,18 × 10^14 korrekt', points: 1.5 },
      { criterion: 'Brute-Force-Dauer ≈ 21.834 s ≈ 6,07 h korrekt', points: 1.5 },
      { criterion: '95^12 ≈ 5,40 × 10^23 und Dauer ≈ 1,7 Millionen Jahre korrekt umgerechnet', points: 2 },
    ],
    explanation: 'Die Passwortlänge wirkt exponentiell, der Zeichenvorrat nur als Basis. Vier zusätzliche Zeichen und Sonderzeichen erhöhen die Brute-Force-Dauer von Stunden auf Millionen Jahre.',
  },

  /* =====================================================================
   * MULTIPLE CHOICE (3 Punkte) – IT-Sicherheit
   * ===================================================================== */
  {
    id: 'si-mc-001',
    section: 'sicherheit',
    topic: 'verfuegbarkeit',
    type: 'multiple_choice',
    title: 'Maßnahmen zur Erhöhung der Verfügbarkeit',
    scenario: 'Die Autovermietung DriveNow Rent betreibt ihr Buchungssystem auf einem einzelnen Server im Büro. Nach einem Stromausfall war das System mehrere Stunden nicht erreichbar.',
    text: 'Welche der folgenden Maßnahmen erhöhen unmittelbar die **Verfügbarkeit** des Buchungssystems? (Mehrere Antworten möglich)',
    points: 3,
    difficulty: 2,
    options: [
      { id: 'a', text: 'Einsatz einer unterbrechungsfreien Stromversorgung (USV)' },
      { id: 'b', text: 'Spiegelung der Daten in Echtzeit auf ein zweites, redundantes Speichersystem' },
      { id: 'c', text: 'Vollständige Verschlüsselung der Server-Festplatten' },
      { id: 'd', text: 'Redundante Netzteile und ein zweiter Internetanschluss' },
      { id: 'e', text: 'Einführung einer Zwei-Faktor-Authentifizierung für alle Benutzer' },
      { id: 'f', text: 'Strengere Passwortrichtlinie mit mindestens 12 Zeichen' },
    ],
    correct: ['a', 'b', 'd'],
    multi: true,
    explanation: 'USV, redundante Datenspeicher und redundante Komponenten beseitigen einzelne Ausfallpunkte (Single Points of Failure). Verschlüsselung, MFA und Passwortrichtlinien dienen der Vertraulichkeit bzw. Authentizität, nicht der Verfügbarkeit.',
  },
  {
    id: 'si-mc-002',
    section: 'sicherheit',
    topic: 'verschluesselung',
    type: 'multiple_choice',
    title: 'Schlüsselverwendung bei asymmetrischer Verschlüsselung',
    scenario: 'Frau Adler von der Personalberatung Adler & Lutz möchte einem Bewerber eine vertrauliche E-Mail mit einem asymmetrischen Verfahren verschlüsselt senden.',
    text: 'Mit welchem Schlüssel muss Frau Adler die Nachricht verschlüsseln, damit **nur der Bewerber** sie lesen kann?',
    points: 3,
    difficulty: 2,
    options: [
      { id: 'a', text: 'Mit ihrem eigenen privaten Schlüssel' },
      { id: 'b', text: 'Mit ihrem eigenen öffentlichen Schlüssel' },
      { id: 'c', text: 'Mit dem öffentlichen Schlüssel des Bewerbers' },
      { id: 'd', text: 'Mit dem privaten Schlüssel des Bewerbers' },
      { id: 'e', text: 'Mit einem gemeinsam vereinbarten Sitzungsschlüssel, der im Klartext mitgesendet wird' },
    ],
    correct: ['c'],
    multi: false,
    explanation: 'Verschlüsselt wird mit dem öffentlichen Schlüssel des Empfängers; nur der zugehörige private Schlüssel des Empfängers kann entschlüsseln. Der eigene private Schlüssel dient dem Signieren.',
  },
  {
    id: 'si-mc-003',
    section: 'sicherheit',
    topic: 'backup',
    type: 'multiple_choice',
    title: 'Backup-Konzept gegen Ransomware',
    scenario: 'Nach einem Ransomware-Angriff auf ein Partnerunternehmen überprüft die Gebäudetechnik Rauscher GmbH ihr Sicherungskonzept.',
    text: 'Welche Eigenschaften muss ein Sicherungskonzept aufweisen, damit Daten nach einem Ransomware-Angriff zuverlässig wiederhergestellt werden können? (Mehrere Antworten möglich)',
    points: 3,
    difficulty: 2,
    options: [
      { id: 'a', text: 'Mindestens eine Sicherungskopie ist offline bzw. vom Produktivnetz getrennt (Air Gap)' },
      { id: 'b', text: 'Die Sicherung liegt auf einer freigegebenen Netzwerkfreigabe, auf die alle Mitarbeitenden Schreibzugriff haben' },
      { id: 'c', text: 'Die Wiederherstellung wird regelmäßig getestet (Restore-Test)' },
      { id: 'd', text: 'Es werden mehrere Versionsstände (Generationen) vorgehalten, nicht nur der letzte' },
      { id: 'e', text: 'Die Sicherung wird auf einer zweiten Partition derselben Festplatte abgelegt' },
      { id: 'f', text: 'Die Sicherung erfolgt ausschließlich als Echtzeit-Spiegelung auf eine zweite Festplatte im selben Server' },
    ],
    correct: ['a', 'c', 'd'],
    multi: true,
    explanation: 'Ransomware verschlüsselt alles Erreichbare – daher Offline-Kopie, mehrere Generationen (falls der Angriff erst spät bemerkt wird) und getestete Restores. Eine Echtzeit-Spiegelung ist kein Backup, da die Verschlüsselung sofort mitgespiegelt wird.',
  },
  {
    id: 'si-mc-004',
    section: 'sicherheit',
    topic: 'haertung',
    type: 'multiple_choice',
    title: 'Härtung eines Betriebssystems',
    scenario: 'Die Spedition Wagner & Co. nimmt einen neuen Windows-Server in Betrieb. Vor dem Produktivbetrieb soll das System nach den Vorgaben des BSI gehärtet werden.',
    text: 'Welche Maßnahmen gehören zur Härtung (Hardening) eines Betriebssystems? (Mehrere Antworten möglich)',
    points: 3,
    difficulty: 2,
    options: [
      { id: 'a', text: 'Nicht benötigte Dienste, Rollen und Programme deaktivieren bzw. deinstallieren' },
      { id: 'b', text: 'Voreingestellte Standardpasswörter und -konten ändern bzw. deaktivieren' },
      { id: 'c', text: 'Alle Netzwerkports öffnen, damit spätere Anwendungen ohne Nacharbeit funktionieren' },
      { id: 'd', text: 'Automatische Installation von Sicherheitsupdates aktivieren' },
      { id: 'e', text: 'Alle Benutzer dauerhaft mit Administratorrechten arbeiten lassen, um Supportanfragen zu vermeiden' },
      { id: 'f', text: 'Die lokale Firewall deaktivieren, da bereits eine Firewall am Internetzugang existiert' },
    ],
    correct: ['a', 'b', 'd'],
    multi: true,
    explanation: 'Härtung bedeutet, die Angriffsfläche zu verkleinern: nur nötige Dienste, keine Standardzugänge, aktuelle Patches, lokale Firewall und Arbeiten nach dem Prinzip der minimalen Rechte (Least Privilege).',
  },
  {
    id: 'si-mc-005',
    section: 'sicherheit',
    topic: 'netzwerksicherheit',
    type: 'multiple_choice',
    title: 'IDS und IPS',
    scenario: 'Die Systemhaus Kettner GmbH schlägt ihrem Kunden zur Absicherung des Firmennetzes ein Intrusion Prevention System (IPS) statt des bisherigen Intrusion Detection Systems (IDS) vor.',
    text: 'Welche Aussage beschreibt den wesentlichen Unterschied zwischen IDS und IPS korrekt?',
    points: 3,
    difficulty: 2,
    options: [
      { id: 'a', text: 'Ein IDS erkennt Angriffe und meldet sie; ein IPS erkennt Angriffe und blockiert den zugehörigen Datenverkehr aktiv.' },
      { id: 'b', text: 'Ein IDS arbeitet nur auf Servern (hostbasiert), ein IPS nur im Netzwerk.' },
      { id: 'c', text: 'Ein IPS ersetzt die Firewall vollständig, ein IDS ergänzt sie lediglich.' },
      { id: 'd', text: 'Ein IDS verschlüsselt den Datenverkehr, ein IPS überwacht ihn nur.' },
      { id: 'e', text: 'Ein IPS ist eine reine Protokollierungslösung, ein IDS greift aktiv in den Verkehr ein.' },
    ],
    correct: ['a'],
    multi: false,
    explanation: 'Detection = erkennen und alarmieren; Prevention = erkennen und verhindern. Beide gibt es host- und netzwerkbasiert, und beide ergänzen eine Firewall, ersetzen sie aber nicht.',
  },
  {
    id: 'si-mc-006',
    section: 'sicherheit',
    topic: 'authentifizierung',
    type: 'multiple_choice',
    title: 'Echte Mehrfaktor-Authentifizierung',
    scenario: 'Die Kreissparkasse-Tochter KSK Immobilien möchte den Zugang zu ihrem Kundenportal mit einer Zwei-Faktor-Authentifizierung absichern.',
    text: 'Welche der folgenden Kombinationen stellen eine echte **Zwei-Faktor-Authentifizierung** dar, bei der zwei unterschiedliche Faktorkategorien (Wissen, Besitz, Inhärenz) kombiniert werden? (Mehrere Antworten möglich)',
    points: 3,
    difficulty: 3,
    options: [
      { id: 'a', text: 'Passwort und Einmalcode aus einer Authenticator-App auf dem Smartphone' },
      { id: 'b', text: 'Passwort und zusätzliche PIN' },
      { id: 'c', text: 'Smartcard und PIN' },
      { id: 'd', text: 'Passwort und Beantwortung einer Sicherheitsfrage' },
      { id: 'e', text: 'Passwort und Fingerabdruck' },
      { id: 'f', text: 'Fingerabdruck und Gesichtserkennung' },
    ],
    correct: ['a', 'c', 'e'],
    multi: true,
    explanation: 'Zwei Faktoren müssen aus verschiedenen Kategorien stammen: Wissen (Passwort, PIN, Sicherheitsfrage), Besitz (Smartphone, Smartcard), Inhärenz (Biometrie). Passwort + PIN oder Fingerabdruck + Gesicht sind jeweils nur eine Kategorie.',
  },
  {
    id: 'si-mc-007',
    section: 'sicherheit',
    topic: 'hash',
    type: 'multiple_choice',
    title: 'Speicherung von Passwörtern',
    scenario: 'Die Entwickler der Lernplattform LearnHub speichern Benutzerpasswörter bislang im Klartext in der Datenbank. Ein Sicherheitsaudit fordert eine Änderung.',
    text: 'Welches Vorgehen ist für die Speicherung von Passwörtern fachlich korrekt?',
    points: 3,
    difficulty: 2,
    options: [
      { id: 'a', text: 'Passwörter mit AES symmetrisch verschlüsseln; der Schlüssel liegt in der Anwendungskonfiguration.' },
      { id: 'b', text: 'Passwörter mit einer langsamen, salted Hashfunktion (z. B. bcrypt, Argon2) hashen und nur den Hash speichern.' },
      { id: 'c', text: 'Passwörter Base64-kodiert speichern, damit sie nicht direkt lesbar sind.' },
      { id: 'd', text: 'Passwörter mit MD5 ohne Salt hashen, weil MD5 besonders schnell ist.' },
      { id: 'e', text: 'Passwörter im Klartext belassen, aber die Datenbank durch eine Firewall schützen.' },
    ],
    correct: ['b'],
    multi: false,
    explanation: 'Ein Hash ist nicht umkehrbar; Salt verhindert Rainbow-Table-Angriffe, langsame Verfahren bremsen Brute-Force. Verschlüsselung ist umkehrbar (Schlüsseldiebstahl), Base64 ist keine Sicherung, MD5 ist veraltet.',
  },

  /* =====================================================================
   * MULTIPLE CHOICE (2 Punkte) – Datenschutz / DSGVO
   * ===================================================================== */
  {
    id: 'si-mc-008',
    section: 'sicherheit',
    topic: 'dsgvo',
    type: 'multiple_choice',
    title: 'Meldepflicht bei Datenpannen',
    scenario: 'Bei der Ferienhausvermittlung Küstenglück wurde ein Notebook mit unverschlüsselten Kundendaten gestohlen.',
    text: 'Welche Aussage zur Meldepflicht nach Art. 33 DSGVO ist korrekt?',
    points: 2,
    difficulty: 1,
    options: [
      { id: 'a', text: 'Die Verletzung muss unverzüglich, möglichst binnen 72 Stunden nach Bekanntwerden, der zuständigen Aufsichtsbehörde gemeldet werden, sofern ein Risiko für die Betroffenen besteht.' },
      { id: 'b', text: 'Die Verletzung muss innerhalb von 14 Tagen der Polizei gemeldet werden; die Aufsichtsbehörde ist nicht zuständig.' },
      { id: 'c', text: 'Eine Meldung ist nur erforderlich, wenn mehr als 1.000 Personen betroffen sind.' },
      { id: 'd', text: 'Es genügt, den Vorfall intern zu dokumentieren; eine Meldung nach außen ist freiwillig.' },
    ],
    correct: ['a'],
    multi: false,
    explanation: 'Art. 33 DSGVO: Meldung an die Aufsichtsbehörde binnen 72 Stunden, wenn ein Risiko für die Rechte und Freiheiten Betroffener besteht; bei hohem Risiko zusätzlich Benachrichtigung der Betroffenen (Art. 34).',
  },
  {
    id: 'si-mc-009',
    section: 'sicherheit',
    topic: 'dsgvo',
    type: 'multiple_choice',
    title: 'Personenbezogene Daten',
    scenario: 'Die Marketingabteilung der Getränkehandel Quellfrisch GmbH möchte verschiedene Daten in einer Analyse-Datenbank zusammenführen und fragt, welche davon dem Datenschutzrecht unterliegen.',
    text: 'Welche der folgenden Angaben ist **kein** personenbezogenes Datum im Sinne der DSGVO?',
    points: 2,
    difficulty: 2,
    options: [
      { id: 'a', text: 'Das amtliche Kfz-Kennzeichen eines Kundenfahrzeugs' },
      { id: 'b', text: 'Die IP-Adresse des privaten Internetanschlusses eines Webshop-Besuchers' },
      { id: 'c', text: 'Der Jahresumsatz der Quellfrisch GmbH im Geschäftsjahr 2025' },
      { id: 'd', text: 'Die Personalnummer eines Mitarbeiters' },
      { id: 'e', text: 'Die private E-Mail-Adresse einer Kundin' },
    ],
    correct: ['c'],
    multi: false,
    explanation: 'Personenbezogen sind alle Informationen, die sich auf eine identifizierte oder identifizierbare natürliche Person beziehen (Art. 4 Nr. 1 DSGVO). Daten juristischer Personen wie ein Firmenumsatz fallen nicht darunter.',
  },
  {
    id: 'si-mc-010',
    section: 'sicherheit',
    topic: 'dsgvo',
    type: 'multiple_choice',
    title: 'Auftragsverarbeitung',
    scenario: 'Die Physiotherapie-Praxis Bewegung Plus möchte ihre Terminverwaltung inklusive Patientendaten an einen Cloud-Dienstleister auslagern.',
    text: 'Welche Voraussetzung muss nach der DSGVO erfüllt sein, bevor der Cloud-Dienstleister die Patientendaten verarbeiten darf?',
    points: 2,
    difficulty: 2,
    options: [
      { id: 'a', text: 'Es muss ein Vertrag zur Auftragsverarbeitung (Art. 28 DSGVO) geschlossen werden, der u. a. Weisungsgebundenheit und technische und organisatorische Maßnahmen regelt.' },
      { id: 'b', text: 'Jeder Patient muss dem Cloud-Dienstleister schriftlich eine eigene Einwilligung erteilen; ein Vertrag ist nicht nötig.' },
      { id: 'c', text: 'Der Dienstleister muss lediglich seinen Sitz in Deutschland haben; weitere Vereinbarungen sind nicht erforderlich.' },
      { id: 'd', text: 'Die Aufsichtsbehörde muss die Auslagerung vorab genehmigen.' },
    ],
    correct: ['a'],
    multi: false,
    explanation: 'Der Auftragsverarbeiter handelt weisungsgebunden für den Verantwortlichen; Grundlage ist ein AV-Vertrag nach Art. 28 DSGVO. Die Praxis bleibt verantwortlich und muss den Dienstleister sorgfältig auswählen.',
  },
  {
    id: 'si-mc-011',
    section: 'sicherheit',
    topic: 'dsgvo',
    type: 'multiple_choice',
    title: 'Betroffenenrechte',
    scenario: 'Ein ehemaliger Kunde des Möbelhauses Wohnideen Falk verlangt per E-Mail, dass ihm mitgeteilt wird, welche Daten über ihn gespeichert sind.',
    text: 'Welches Betroffenenrecht macht der Kunde geltend und innerhalb welcher Frist muss das Möbelhaus grundsätzlich reagieren?',
    points: 2,
    difficulty: 2,
    options: [
      { id: 'a', text: 'Recht auf Löschung – innerhalb von 72 Stunden' },
      { id: 'b', text: 'Recht auf Auskunft – unverzüglich, spätestens innerhalb eines Monats' },
      { id: 'c', text: 'Recht auf Datenübertragbarkeit – innerhalb von sechs Monaten' },
      { id: 'd', text: 'Recht auf Auskunft – innerhalb von zwei Wochen, sonst verfällt der Anspruch' },
      { id: 'e', text: 'Recht auf Berichtigung – innerhalb von drei Werktagen' },
    ],
    correct: ['b'],
    multi: false,
    explanation: 'Art. 15 DSGVO (Auskunftsrecht) in Verbindung mit Art. 12 Abs. 3: Antwort unverzüglich, spätestens innerhalb eines Monats (in Ausnahmefällen verlängerbar). Die 72 Stunden gelten für die Meldung von Datenpannen.',
  },
  {
    id: 'si-mc-012',
    section: 'sicherheit',
    topic: 'dsgvo',
    type: 'multiple_choice',
    title: 'Datenschutzbeauftragter',
    scenario: 'Die Softwareagentur Nordlicht Digital wächst und beschäftigt inzwischen 25 Mitarbeitende, die alle ständig mit der automatisierten Verarbeitung personenbezogener Daten befasst sind.',
    text: 'Welche Aussage zur Benennung eines Datenschutzbeauftragten ist korrekt?',
    points: 2,
    difficulty: 2,
    options: [
      { id: 'a', text: 'Nach § 38 BDSG muss ein Datenschutzbeauftragter benannt werden, da in der Regel mindestens 20 Personen ständig mit der automatisierten Verarbeitung personenbezogener Daten beschäftigt sind.' },
      { id: 'b', text: 'Ein Datenschutzbeauftragter ist erst ab 250 Mitarbeitenden Pflicht.' },
      { id: 'c', text: 'Der Datenschutzbeauftragte muss zwingend der Geschäftsführer sein, da er die Verantwortung trägt.' },
      { id: 'd', text: 'Ein Datenschutzbeauftragter ist nur für Behörden vorgeschrieben, nicht für private Unternehmen.' },
    ],
    correct: ['a'],
    multi: false,
    explanation: 'In Deutschland konkretisiert § 38 BDSG die DSGVO: Benennungspflicht in der Regel ab 20 ständig mit automatisierter Verarbeitung beschäftigten Personen. Der DSB muss unabhängig sein; die Geschäftsführung ist wegen Interessenkonflikts ungeeignet.',
  },
  {
    id: 'si-mc-013',
    section: 'sicherheit',
    topic: 'dsgvo',
    type: 'multiple_choice',
    title: 'Privacy by Design und Privacy by Default',
    scenario: 'Das Start-up FitTrack entwickelt eine Fitness-App. In der Registrierung sind standardmäßig alle Häkchen zur Weitergabe der Standortdaten an Werbepartner gesetzt.',
    text: 'Gegen welchen Grundsatz der DSGVO verstößt diese Voreinstellung?',
    points: 2,
    difficulty: 2,
    options: [
      { id: 'a', text: 'Privacy by Default (datenschutzfreundliche Voreinstellungen, Art. 25 Abs. 2 DSGVO)' },
      { id: 'b', text: 'Meldepflicht bei Verletzungen des Schutzes personenbezogener Daten (Art. 33 DSGVO)' },
      { id: 'c', text: 'Recht auf Datenübertragbarkeit (Art. 20 DSGVO)' },
      { id: 'd', text: 'Pflicht zur Benennung eines Datenschutzbeauftragten (Art. 37 DSGVO)' },
    ],
    correct: ['a'],
    multi: false,
    explanation: 'Privacy by Default fordert, dass standardmäßig nur die für den Zweck notwendigen Daten verarbeitet werden; Zusatzfreigaben müssen aktiv (Opt-in) erteilt werden. Privacy by Design meint den Datenschutz bereits in der Systemgestaltung.',
  },

  /* =====================================================================
   * LÜCKENTEXT (2 Punkte)
   * ===================================================================== */
  {
    id: 'si-cl-001',
    section: 'sicherheit',
    topic: 'backup',
    type: 'cloze',
    title: 'Sicherungsarten',
    scenario: 'Sie dokumentieren das Sicherungskonzept für den Dateiserver der Glaserei Brandt.',
    text: 'Ergänzen Sie den Text.',
    points: 2,
    difficulty: 1,
    template:
      'Bei einer {{b1}} werden alle ausgewählten Daten vollständig gesichert. Eine {{b2}} Sicherung enthält alle Änderungen seit der letzten Vollsicherung, eine {{b3}} Sicherung nur die Änderungen seit der letzten Sicherung beliebiger Art. Den geringsten Speicherbedarf je Sicherungslauf hat die {{b4}} Sicherung.',
    blanks: [
      { id: 'b1', accepted: ['Vollsicherung', 'Komplettsicherung', 'Vollbackup', 'Voll-Sicherung'] },
      { id: 'b2', accepted: ['differenzielle', 'differentielle', 'differenziell', 'differentiell'], options: ['differenzielle', 'inkrementelle', 'partielle', 'vollständige', 'synchrone'] },
      { id: 'b3', accepted: ['inkrementelle', 'inkrementell'], options: ['differenzielle', 'inkrementelle', 'partielle', 'vollständige', 'synchrone'] },
      { id: 'b4', accepted: ['inkrementelle', 'inkrementell'], options: ['differenzielle', 'inkrementelle', 'vollständige', 'partielle', 'synchrone'] },
    ],
    explanation: 'Differenziell bezieht sich immer auf die letzte Vollsicherung (wachsend), inkrementell auf die jeweils letzte Sicherung (klein, aber Kette nötig).',
  },
  {
    id: 'si-cl-002',
    section: 'sicherheit',
    topic: 'dsgvo',
    type: 'cloze',
    title: 'Grundbegriffe der DSGVO',
    scenario: 'Sie bereiten für die Auszubildenden der Handelsgesellschaft Meyer & Sohn eine Datenschutz-Unterweisung vor.',
    text: 'Ergänzen Sie den Text.',
    points: 2,
    difficulty: 2,
    template:
      'Die DSGVO schützt {{b1}} Daten, also alle Informationen über eine identifizierte oder identifizierbare natürliche Person. Jede Verarbeitung braucht eine Rechtsgrundlage nach Art. 6 DSGVO, z. B. die {{b2}} der betroffenen Person oder die Erfüllung eines Vertrags. Eine Verletzung des Schutzes personenbezogener Daten ist der Aufsichtsbehörde möglichst binnen {{b3}} Stunden zu melden. Es dürfen nur so viele Daten erhoben werden, wie für den Zweck erforderlich sind – dieser Grundsatz heißt {{b4}}.',
    blanks: [
      { id: 'b1', accepted: ['personenbezogene', 'personenbezogenen', 'personenbezogen'] },
      { id: 'b2', accepted: ['Einwilligung', 'Zustimmung'], options: ['Einwilligung', 'Kenntnisnahme', 'Anhörung', 'Registrierung', 'Bestätigung'] },
      { id: 'b3', accepted: ['72'] },
      { id: 'b4', accepted: ['Datenminimierung', 'Datensparsamkeit'], options: ['Datenminimierung', 'Zweckbindung', 'Transparenz', 'Richtigkeit', 'Speicherbegrenzung', 'Integrität'] },
    ],
    explanation: 'Art. 5 DSGVO nennt die Grundsätze: Rechtmäßigkeit, Zweckbindung, Datenminimierung, Richtigkeit, Speicherbegrenzung, Integrität und Vertraulichkeit; Art. 33 regelt die 72-Stunden-Meldefrist.',
  },
  {
    id: 'si-cl-003',
    section: 'sicherheit',
    topic: 'verschluesselung',
    type: 'cloze',
    title: 'TLS und Zertifikate',
    scenario: 'Der Webshop der Manufaktur Seifenglück soll auf HTTPS umgestellt werden. Sie erklären der Geschäftsführung die Grundlagen.',
    text: 'Ergänzen Sie den Text.',
    points: 2,
    difficulty: 2,
    template:
      'HTTPS verwendet das Protokoll {{b1}} zur Verschlüsselung. Beim Verbindungsaufbau weist sich der Server mit einem digitalen {{b2}} aus, das von einer vertrauenswürdigen {{b3}} (CA) ausgestellt wurde. Der Austausch des Sitzungsschlüssels erfolgt {{b4}}, die eigentlichen Nutzdaten werden anschließend {{b5}} verschlüsselt.',
    blanks: [
      { id: 'b1', accepted: ['TLS', 'TLS/SSL', 'SSL/TLS', 'Transport Layer Security'] },
      { id: 'b2', accepted: ['Zertifikat', 'X.509-Zertifikat', 'Serverzertifikat', 'SSL-Zertifikat', 'TLS-Zertifikat'] },
      { id: 'b3', accepted: ['Zertifizierungsstelle', 'Certificate Authority', 'Zertifikatsstelle', 'Zertifizierungsinstanz'], options: ['Zertifizierungsstelle', 'Aufsichtsbehörde', 'Registrierungsstelle', 'Domain-Registrar', 'Internetprovider'] },
      { id: 'b4', accepted: ['asymmetrisch'], options: ['asymmetrisch', 'symmetrisch', 'unverschlüsselt', 'gehasht'] },
      { id: 'b5', accepted: ['symmetrisch'], options: ['asymmetrisch', 'symmetrisch', 'unverschlüsselt', 'gehasht'] },
    ],
    explanation: 'TLS ist ein Hybridverfahren: Authentifizierung und Schlüsselaustausch asymmetrisch über Zertifikate einer CA, Datenverschlüsselung symmetrisch (z. B. AES) wegen der höheren Geschwindigkeit.',
  },
  {
    id: 'si-cl-004',
    section: 'sicherheit',
    topic: 'hashing',
    type: 'cloze',
    title: 'Hashverfahren und Passwortspeicherung',
    scenario: 'Für das Kundenportal der Fitnessstudio-Kette FitZone soll die Speicherung der Passwörter überprüft werden.',
    text: 'Ergänzen Sie den Text.',
    points: 2,
    difficulty: 2,
    template:
      'Passwörter werden nicht im Klartext, sondern nur als {{b1}} gespeichert. Eine Hashfunktion ist eine {{b2}}-Funktion: Aus dem Hashwert lässt sich das Passwort nicht zurückrechnen. Damit gleiche Passwörter unterschiedliche Hashwerte ergeben und vorberechnete Tabellen (Rainbow Tables) nutzlos werden, wird jedem Passwort vor dem Hashen ein zufälliger {{b3}} hinzugefügt. Um die Integrität einer heruntergeladenen Installationsdatei zu prüfen, vergleicht man die vom Hersteller veröffentlichte {{b4}} mit dem selbst berechneten Hashwert.',
    blanks: [
      { id: 'b1', accepted: ['Hashwert', 'Hash'], options: ['Hashwert', 'Chiffrat', 'Zertifikat', 'Token', 'Base64-Text'] },
      { id: 'b2', accepted: ['Einweg', 'Einwegfunktion', 'nicht umkehrbare'], options: ['Einweg', 'symmetrische', 'asymmetrische', 'umkehrbare', 'lineare'] },
      { id: 'b3', accepted: ['Salt', 'Salt-Wert', 'Salz'] },
      { id: 'b4', accepted: ['Prüfsumme', 'Checksumme', 'Hashwert'], options: ['Prüfsumme', 'Signaturdatei', 'Seriennummer', 'Lizenznummer', 'Versionsnummer'] },
    ],
    explanation: 'Hashfunktionen (z. B. SHA-256, für Passwörter bcrypt/Argon2) sind Einwegfunktionen. Ein Salt macht identische Passwörter unterscheidbar; Prüfsummen sichern die Integrität von Downloads.',
  },
  {
    id: 'si-cl-005',
    section: 'sicherheit',
    topic: 'schutzbedarf',
    type: 'cloze',
    title: 'Schutzbedarfsfeststellung nach BSI',
    scenario: 'Die Stadtwerke Lindau führen eine Schutzbedarfsfeststellung nach IT-Grundschutz des BSI durch.',
    text: 'Ergänzen Sie den Text.',
    points: 2,
    difficulty: 3,
    template:
      'Der IT-Grundschutz wird vom {{b1}} herausgegeben. Der Schutzbedarf wird für die Schutzziele Vertraulichkeit, Integrität und {{b2}} getrennt bestimmt und in die Kategorien "normal", "hoch" und {{b3}} eingeteilt. Setzt sich ein System aus mehreren Anwendungen zusammen, bestimmt nach dem {{b4}} die Anwendung mit dem höchsten Schutzbedarf den Schutzbedarf des Systems.',
    blanks: [
      { id: 'b1', accepted: ['BSI', 'Bundesamt für Sicherheit in der Informationstechnik'] },
      { id: 'b2', accepted: ['Verfügbarkeit'], options: ['Verfügbarkeit', 'Authentizität', 'Anonymität', 'Zuverlässigkeit', 'Transparenz'] },
      { id: 'b3', accepted: ['sehr hoch', '"sehr hoch"'], options: ['sehr hoch', 'kritisch', 'extrem', 'maximal', 'gering'] },
      { id: 'b4', accepted: ['Maximumprinzip', 'Maximum-Prinzip'], options: ['Maximumprinzip', 'Kumulationseffekt', 'Verteilungseffekt', 'Minimalprinzip', 'Generationenprinzip'] },
    ],
    explanation: 'Das BSI definiert im IT-Grundschutz die Schutzbedarfskategorien normal/hoch/sehr hoch; Für die Übertragung des Schutzbedarfs auf Systeme gelten Maximumprinzip, Kumulations- und Verteilungseffekt.',
  },
  {
    id: 'si-cl-006',
    section: 'sicherheit',
    topic: 'datenschutz',
    type: 'cloze',
    title: 'Anonymisierung und Pseudonymisierung',
    scenario: 'Die Marktforschungsagentur Trendwerk möchte Kundendaten für statistische Auswertungen an ein Partnerunternehmen weitergeben.',
    text: 'Ergänzen Sie den Text.',
    points: 2,
    difficulty: 2,
    template:
      'Bei der {{b1}} werden identifizierende Merkmale (z. B. Name) durch ein Kennzeichen wie eine Kundennummer ersetzt; mit einer getrennt aufbewahrten Zuordnungstabelle bleibt die Person wieder identifizierbar. Solche Daten gelten im Sinne der DSGVO weiterhin als {{b2}}. Bei der {{b3}} wird der Personenbezug dagegen unwiederbringlich entfernt, sodass die DSGVO nicht mehr anwendbar ist. Der Grundsatz, nur so viele personenbezogene Daten zu verarbeiten, wie für den Zweck erforderlich sind, heißt {{b4}}.',
    blanks: [
      { id: 'b1', accepted: ['Pseudonymisierung'], options: ['Pseudonymisierung', 'Anonymisierung', 'Verschlüsselung', 'Aggregation', 'Archivierung'] },
      { id: 'b2', accepted: ['personenbezogen', 'personenbezogene Daten'], options: ['personenbezogen', 'anonym', 'öffentlich', 'statistisch', 'unkritisch'] },
      { id: 'b3', accepted: ['Anonymisierung'], options: ['Pseudonymisierung', 'Anonymisierung', 'Verschlüsselung', 'Aggregation', 'Archivierung'] },
      { id: 'b4', accepted: ['Datenminimierung', 'Datensparsamkeit'], options: ['Datenminimierung', 'Zweckbindung', 'Transparenz', 'Speicherbegrenzung', 'Richtigkeit'] },
    ],
    explanation: 'Pseudonymisierte Daten bleiben personenbezogen (Art. 4 Nr. 5 DSGVO), anonymisierte Daten nicht. Datenminimierung ist einer der Grundsätze aus Art. 5 DSGVO.',
  },
  {
    id: 'si-ft-006',
    section: 'sicherheit',
    topic: 'dsgvo',
    type: 'free_text',
    title: 'Betroffenenrechte nach der DSGVO',
    scenario: 'Der Online-Shop Nordlicht Trading erhält von einer Kundin eine E-Mail: Sie möchte wissen, welche Daten über sie gespeichert sind, und verlangt anschließend die Löschung ihres Kontos.',
    text: 'Nennen Sie drei Betroffenenrechte nach der DSGVO, die in dieser Situation relevant sind, und erläutern Sie zu jedem Recht kurz, was das Unternehmen konkret tun muss. Gehen Sie auch auf die Frist für die Beantwortung ein.',
    points: 4,
    difficulty: 2,
    solution:
      'Auskunftsrecht (Art. 15): Das Unternehmen muss mitteilen, welche personenbezogenen Daten zu welchem Zweck verarbeitet werden, woher sie stammen und an wen sie weitergegeben wurden, und eine Kopie der Daten bereitstellen.\nRecht auf Löschung / "Recht auf Vergessenwerden" (Art. 17): Das Konto und die Daten sind zu löschen, sofern keine gesetzlichen Aufbewahrungspflichten (z. B. Rechnungen 10 Jahre nach HGB/AO) entgegenstehen; dann sind die Daten zu sperren bzw. auf die Aufbewahrungspflicht zu beschränken.\nWeitere relevante Rechte: Recht auf Berichtigung (Art. 16), Recht auf Datenübertragbarkeit (Art. 20), Widerspruchsrecht (Art. 21), Recht auf Einschränkung der Verarbeitung (Art. 18).\nFrist: Anfragen sind unverzüglich, spätestens innerhalb eines Monats zu beantworten (verlängerbar um zwei Monate bei komplexen Anfragen); die Identität der anfragenden Person ist vorher zu prüfen.',
    rubric: [
      { criterion: 'Drei zutreffende Betroffenenrechte korrekt benannt (z. B. Auskunft, Löschung, Berichtigung, Datenübertragbarkeit, Widerspruch)', points: 1.5 },
      { criterion: 'Konkrete Umsetzung je Recht erläutert (Auskunft erteilen, löschen bzw. bei Aufbewahrungspflicht einschränken, Identität prüfen)', points: 1.5 },
      { criterion: 'Frist von einem Monat genannt', points: 1 },
    ],
    explanation: 'Die Betroffenenrechte stehen in Kapitel III der DSGVO (Art. 12–23). Aufbewahrungspflichten aus HGB/AO gehen dem Löschanspruch vor, die Daten sind dann in der Verarbeitung einzuschränken.',
  },
];
